/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.job;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Enumeration of job activity states.
 */
@JsonDeserialize(using = JobActivityState.Deserializer.class)
public class JobActivityState extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * The activity has not started.
    */
    public static JobActivityState JasNotStarted = new JobActivityState("jasNotStarted");
    /**
     * The activity has started.
    */
    public static JobActivityState JasStarted = new JobActivityState("jasStarted");
    /**
     * The activity has completed.
    */
    public static JobActivityState JasCompleted = new JobActivityState("jasCompleted");

    protected static Hashtable<String, JobActivityState> definitions;
    
    static {
        definitions = new Hashtable<String, JobActivityState> ();
        definitions.put(JasNotStarted.getValue(), JasNotStarted);
        definitions.put(JasStarted.getValue(), JasStarted);
        definitions.put(JasCompleted.getValue(), JasCompleted);
    }

    private JobActivityState() {
        this(null);
    }

    private JobActivityState(String name) {
        this(name, name);
    }

    private JobActivityState(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = JobTypesManifest.getInstance().MajorVersion;
        typeName = "jobActivityState";
        typeGUN = "com.hp.ext.types.job.version.1.type.jobActivityState";
    }

    public static JobActivityState Parse(String name)
    {
        JobActivityState instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  JobActivityState(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<JobActivityState> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public JobActivityState deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return JobActivityState.Parse(node.asText());
        }
    }
}
