/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.job;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Enumeration of job destinations.
 */
@JsonDeserialize(using = JobDestination.Deserializer.class)
public class JobDestination extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * The mass storage of the device used to receive, hold, and release stored jobs.
    */
    public static JobDestination JdInternalStorage = new JobDestination("jdInternalStorage");
    /**
     * USB mass storage devices that provide print data for the walkup print or is a recipient of scan 
         * data for walk-up copy to USB.
    */
    public static JobDestination JdRemovableStorage = new JobDestination("jdRemovableStorage");
    /**
     * Data sent to the print engine.
    */
    public static JobDestination JdPrintEngine = new JobDestination("jdPrintEngine");
    /**
     * Data sent to an SMTP server configured in the E-mail application.
    */
    public static JobDestination JdEmail = new JobDestination("jdEmail");
    /**
     * Data sent to a network folder configured in the Send to Folder application.
    */
    public static JobDestination JdNetworkFolder = new JobDestination("jdNetworkFolder");
    /**
     * Data sent to an FTP folder configured in the Send to Folder application.
    */
    public static JobDestination JdFtp = new JobDestination("jdFtp");
    /**
     * Data sent to an HTTP destination whether sent by an internal application, OXPd based application 
         * or embedded third party application.
    */
    public static JobDestination JdHttp = new JobDestination("jdHttp");
    /**
     * Data sent via the analog fax card.
    */
    public static JobDestination JdFaxCard = new JobDestination("jdFaxCard");
    /**
     * For most job types, the scanner is the source of the job data (for example, scanned image). In the 
         * case of scanner calibration, calibrations are scheduled as a job to insure that the calibration 
         * does not interfere with any other job and the scanner shows as a destination.
    */
    public static JobDestination JdScanner = new JobDestination("jdScanner");
    /**
     * Reserved for future use.
    */
    public static JobDestination JdWebService = new JobDestination("jdWebService");
    /**
     * Data sent directly to a device's in-memory image queue, intended for future consumption by another job.
    */
    public static JobDestination JdImageQueue = new JobDestination("jdImageQueue");
    /**
     * A destination not represented by another value in this enumeration.
    */
    public static JobDestination JdOther = new JobDestination("jdOther");

    protected static Hashtable<String, JobDestination> definitions;
    
    static {
        definitions = new Hashtable<String, JobDestination> ();
        definitions.put(JdInternalStorage.getValue(), JdInternalStorage);
        definitions.put(JdRemovableStorage.getValue(), JdRemovableStorage);
        definitions.put(JdPrintEngine.getValue(), JdPrintEngine);
        definitions.put(JdEmail.getValue(), JdEmail);
        definitions.put(JdNetworkFolder.getValue(), JdNetworkFolder);
        definitions.put(JdFtp.getValue(), JdFtp);
        definitions.put(JdHttp.getValue(), JdHttp);
        definitions.put(JdFaxCard.getValue(), JdFaxCard);
        definitions.put(JdScanner.getValue(), JdScanner);
        definitions.put(JdWebService.getValue(), JdWebService);
        definitions.put(JdImageQueue.getValue(), JdImageQueue);
        definitions.put(JdOther.getValue(), JdOther);
    }

    private JobDestination() {
        this(null);
    }

    private JobDestination(String name) {
        this(name, name);
    }

    private JobDestination(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = JobTypesManifest.getInstance().MajorVersion;
        typeName = "jobDestination";
        typeGUN = "com.hp.ext.types.job.version.1.type.jobDestination";
    }

    public static JobDestination Parse(String name)
    {
        JobDestination instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  JobDestination(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<JobDestination> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public JobDestination deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return JobDestination.Parse(node.asText());
        }
    }
}
