/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.job;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Enumeration of job completion status values.
 */
@JsonDeserialize(using = JobDoneStatus.Deserializer.class)
public class JobDoneStatus extends E2Enumeration {

    public static boolean isSealed() { return true; }

    /**
     * The job is still active (not yet complete).
    */
    public static JobDoneStatus JdsActive = new JobDoneStatus("jdsActive");
    /**
     * The job completed successfully.
    */
    public static JobDoneStatus JdsSucceeded = new JobDoneStatus("jdsSucceeded");
    /**
     * Parts of the job succeeded, but others failed. For example, a fax job was sent to at least one 
         * fax number, but the device was unable to deliver it to another fax number.
    */
    public static JobDoneStatus JdsPartiallySucceeded = new JobDoneStatus("jdsPartiallySucceeded");
    /**
     * The job failed.
    */
    public static JobDoneStatus JdsFailed = new JobDoneStatus("jdsFailed");
    /**
     * The job was canceled.
    */
    public static JobDoneStatus JdsCanceled = new JobDoneStatus("jdsCanceled");

    protected static Hashtable<String, JobDoneStatus> definitions;
    
    static {
        definitions = new Hashtable<String, JobDoneStatus> ();
        definitions.put(JdsActive.getValue(), JdsActive);
        definitions.put(JdsSucceeded.getValue(), JdsSucceeded);
        definitions.put(JdsPartiallySucceeded.getValue(), JdsPartiallySucceeded);
        definitions.put(JdsFailed.getValue(), JdsFailed);
        definitions.put(JdsCanceled.getValue(), JdsCanceled);
    }

    private JobDoneStatus() {
        this(null);
    }

    private JobDoneStatus(String name) {
        this(name, name);
    }

    private JobDoneStatus(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = JobTypesManifest.getInstance().MajorVersion;
        typeName = "jobDoneStatus";
        typeGUN = "com.hp.ext.types.job.version.1.type.jobDoneStatus";
    }

    public static JobDoneStatus Parse(String name)
    {
        JobDoneStatus instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  JobDoneStatus(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<JobDoneStatus> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public JobDoneStatus deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return JobDoneStatus.Parse(node.asText());
        }
    }
}
