/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.application;

import com.hp.ext.types.common.E2Type;

/**
 * The content part of the programmatic operation to terminate an app and release the context.
 */
public class ExitRequest extends E2Type
{
    
    public ExitRequest()
    {
        majorVersion = ApplicationManifest.getInstance().MajorVersion;
        typeName = "exitRequest";
        typeGUN = "com.hp.ext.service.application.version.1.type.exitRequest";
    }
}
