/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the <homescreen> resource.
 */
public class Homescreen extends E2Type
{
    private com.hp.ext.types.base.OperationMeta opMeta;
    private java.util.List<com.hp.ext.types.base.Link> links;
    private java.util.UUID defaultApplicationId;
    private com.hp.ext.types.application.HomescreenCustomMessageContent homescreenCustomMessage;
    
    @JsonProperty("$opMeta")
    public com.hp.ext.types.base.OperationMeta getopMeta() {
        return opMeta;
    }

    @JsonProperty("$opMeta")
    public void setopMeta(com.hp.ext.types.base.OperationMeta opMeta) {
        this.opMeta = opMeta;
    }
    @JsonProperty("links")
    public java.util.List<com.hp.ext.types.base.Link> getLinks() {
        return links;
    }

    @JsonProperty("links")
    public void setLinks(java.util.List<com.hp.ext.types.base.Link> links) {
        this.links = links;
    }
    @JsonProperty("defaultApplicationId")
    public java.util.UUID getDefaultApplicationId() {
        return defaultApplicationId;
    }

    @JsonProperty("defaultApplicationId")
    public void setDefaultApplicationId(java.util.UUID defaultApplicationId) {
        this.defaultApplicationId = defaultApplicationId;
    }
    @JsonProperty("homescreenCustomMessage")
    public com.hp.ext.types.application.HomescreenCustomMessageContent getHomescreenCustomMessage() {
        return homescreenCustomMessage;
    }

    @JsonProperty("homescreenCustomMessage")
    public void setHomescreenCustomMessage(com.hp.ext.types.application.HomescreenCustomMessageContent homescreenCustomMessage) {
        this.homescreenCustomMessage = homescreenCustomMessage;
    }
    public Homescreen()
    {
        majorVersion = ApplicationManifest.getInstance().MajorVersion;
        typeName = "homescreen";
        typeGUN = "com.hp.ext.service.application.version.1.type.homescreen";
    }
}
