/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the <messageCenterAgents>/{agentId} resource.
 */
public class MessageCenterAgent extends E2Type
{
    private com.hp.ext.types.base.OperationMeta opMeta;
    private java.util.List<com.hp.ext.types.base.Link> links;
    private com.hp.ext.types.agent.AgentId resourceId;
    private com.hp.ext.types.agent.AgentId agentId;
    private com.hp.ext.types.localization.LocalizedStringReference localizedDescription;
    private com.hp.ext.types.localization.LocalizedStringReference localizedName;
    private com.hp.ext.types.agent.AgentName name;
    private com.hp.ext.types.agent.SolutionId solutionId;
    
    @JsonProperty("$opMeta")
    public com.hp.ext.types.base.OperationMeta getopMeta() {
        return opMeta;
    }

    @JsonProperty("$opMeta")
    public void setopMeta(com.hp.ext.types.base.OperationMeta opMeta) {
        this.opMeta = opMeta;
    }
    @JsonProperty("links")
    public java.util.List<com.hp.ext.types.base.Link> getLinks() {
        return links;
    }

    @JsonProperty("links")
    public void setLinks(java.util.List<com.hp.ext.types.base.Link> links) {
        this.links = links;
    }
    @JsonProperty("resourceId")
    public com.hp.ext.types.agent.AgentId getResourceId() {
        return resourceId;
    }

    @JsonProperty("resourceId")
    public void setResourceId(com.hp.ext.types.agent.AgentId resourceId) {
        this.resourceId = resourceId;
    }
    @JsonProperty("agentId")
    public com.hp.ext.types.agent.AgentId getAgentId() {
        return agentId;
    }

    @JsonProperty("agentId")
    public void setAgentId(com.hp.ext.types.agent.AgentId agentId) {
        this.agentId = agentId;
    }
    @JsonProperty("localizedDescription")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedDescription() {
        return localizedDescription;
    }

    @JsonProperty("localizedDescription")
    public void setLocalizedDescription(com.hp.ext.types.localization.LocalizedStringReference localizedDescription) {
        this.localizedDescription = localizedDescription;
    }
    @JsonProperty("localizedName")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedName() {
        return localizedName;
    }

    @JsonProperty("localizedName")
    public void setLocalizedName(com.hp.ext.types.localization.LocalizedStringReference localizedName) {
        this.localizedName = localizedName;
    }
    @JsonProperty("name")
    public com.hp.ext.types.agent.AgentName getName() {
        return name;
    }

    @JsonProperty("name")
    public void setName(com.hp.ext.types.agent.AgentName name) {
        this.name = name;
    }
    @JsonProperty("solutionId")
    public com.hp.ext.types.agent.SolutionId getSolutionId() {
        return solutionId;
    }

    @JsonProperty("solutionId")
    public void setSolutionId(com.hp.ext.types.agent.SolutionId solutionId) {
        this.solutionId = solutionId;
    }
    public MessageCenterAgent()
    {
        majorVersion = ApplicationManifest.getInstance().MajorVersion;
        typeName = "messageCenterAgent";
        typeGUN = "com.hp.ext.service.application.version.1.type.messageCenterAgent";
    }
}
