/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the JSON body parameters for the Modify operation of the <applicationRuntime>/currentContext/runtimeChrome resource.
 */
public class RuntimeChrome_Modify extends E2Type
{
    private com.hp.ext.types.application.ApplicationRuntimeChrome applicationChrome;
    
    @JsonProperty("applicationChrome")
    public com.hp.ext.types.application.ApplicationRuntimeChrome getApplicationChrome() {
        return applicationChrome;
    }

    @JsonProperty("applicationChrome")
    public void setApplicationChrome(com.hp.ext.types.application.ApplicationRuntimeChrome applicationChrome) {
        this.applicationChrome = applicationChrome;
    }
    public RuntimeChrome_Modify()
    {
        majorVersion = ApplicationManifest.getInstance().MajorVersion;
        typeName = "runtimeChrome_modify";
        typeGUN = "com.hp.ext.service.application.version.1.type.runtimeChrome_modify";
    }
}
