/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.common;



import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Holds a boolean value or a value corresponding to 'automatic'
 */
@JsonDeserialize(using = BooleanOrAuto.Deserializer.class)
public class BooleanOrAuto extends E2Enumeration {

    public static boolean isSealed() { return true; }

    /**
     * Indicates to perform automatic determination of the value
    */
    public static BooleanOrAuto Auto = new BooleanOrAuto("auto");
    /**
     * Represents an explicit true, yes, or 'on' value.
    */
    public static BooleanOrAuto True = new BooleanOrAuto("true");
    /**
     * Represents an explicit false, no, or 'off' value.
    */
    public static BooleanOrAuto False = new BooleanOrAuto("false");

    protected static Hashtable<String, BooleanOrAuto> definitions;
    
    static {
        definitions = new Hashtable<String, BooleanOrAuto> ();
        definitions.put(Auto.getValue(), Auto);
        definitions.put(True.getValue(), True);
        definitions.put(False.getValue(), False);
    }

    private BooleanOrAuto() {
        this(null);
    }

    private BooleanOrAuto(String name) {
        this(name, name);
    }

    private BooleanOrAuto(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = CommonTypesManifest.getInstance().MajorVersion;
        typeName = "booleanOrAuto";
        typeGUN = "com.hp.ext.types.commonTypes.version.1.type.booleanOrAuto";
    }

    public static BooleanOrAuto Parse(String name)
    {
        BooleanOrAuto instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  BooleanOrAuto(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<BooleanOrAuto> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public BooleanOrAuto deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return BooleanOrAuto.Parse(node.asText());
        }
    }
}
