/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.common;



import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Holds a boolean value or a value corresponding to 'none', which might represent an unspecified or default value.
 */
@JsonDeserialize(using = BooleanOrNone.Deserializer.class)
public class BooleanOrNone extends E2Enumeration {

    public static boolean isSealed() { return true; }

    /**
     * Represents no explicit value
    */
    public static BooleanOrNone None = new BooleanOrNone("none");
    /**
     * Represents an explicit true, yes, or 'on' value.
    */
    public static BooleanOrNone True = new BooleanOrNone("true");
    /**
     * Represents an explicit false, no, or 'off' value.
    */
    public static BooleanOrNone False = new BooleanOrNone("false");

    protected static Hashtable<String, BooleanOrNone> definitions;
    
    static {
        definitions = new Hashtable<String, BooleanOrNone> ();
        definitions.put(None.getValue(), None);
        definitions.put(True.getValue(), True);
        definitions.put(False.getValue(), False);
    }

    private BooleanOrNone() {
        this(null);
    }

    private BooleanOrNone(String name) {
        this(name, name);
    }

    private BooleanOrNone(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = CommonTypesManifest.getInstance().MajorVersion;
        typeName = "booleanOrNone";
        typeGUN = "com.hp.ext.types.commonTypes.version.1.type.booleanOrNone";
    }

    public static BooleanOrNone Parse(String name)
    {
        BooleanOrNone instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  BooleanOrNone(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<BooleanOrNone> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public BooleanOrNone deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return BooleanOrNone.Parse(node.asText());
        }
    }
}
