/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.common;



/**
 * The provided context token does not authorize access to current resource/operation.
 */
public class ContextError extends E2Type
{
    
    public ContextError()
    {
        majorVersion = CommonTypesManifest.getInstance().MajorVersion;
        typeName = "contextError";
        typeGUN = "com.hp.ext.types.commonTypes.version.1.type.contextError";
    }
}
