/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.common;



/**
 * A local file path, for use only by applications with access to the device's local file system.
 */
public class LocalFilePath extends E2Alias<String> 
{
    public LocalFilePath() 
    {
        this(null);
    }

    public LocalFilePath(String value)
    {
        super(value);
        majorVersion = CommonTypesManifest.getInstance().MajorVersion;
        typeName = "localFilePath";
        typeGUN = "com.hp.ext.types.commonTypes.version.1.type.localFilePath";
    }

    public LocalFilePath valueOf(String value) { return new LocalFilePath(value); }

    @Override public String toString() { return value.toString(); }
}
