/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.common;



/**
 * Holds an integral percent value
 */
public class Percent extends E2Alias<java.lang.Byte> 
{
    public Percent() 
    {
        this(java.lang.Byte.valueOf((byte) 0));
    }

    public Percent(java.lang.Byte value)
    {
        super(value);
        majorVersion = CommonTypesManifest.getInstance().MajorVersion;
        typeName = "percent";
        typeGUN = "com.hp.ext.types.commonTypes.version.1.type.percent";
    }

    public Percent valueOf(java.lang.Byte value) { return new Percent(value); }

    @Override public String toString() { return value.toString(); }
}
