/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.security;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * An enumeration of authentication types supported at the front panel
 */
@JsonDeserialize(using = AuthenticationKind.Deserializer.class)
public class AuthenticationKind extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * An authentication type not represented by another value in this enumeration. Note that future extensions to this 
         * type might cause authentication mechanisms that were previously designated as 'other' to be designated as a new, 
         * specific kind.
    */
    public static AuthenticationKind AkOther = new AuthenticationKind("akOther");
    /**
     * Authentication via local admin account
    */
    public static AuthenticationKind AkDeviceAdmin = new AuthenticationKind("akDeviceAdmin");
    /**
     * Authentication via local user account
    */
    public static AuthenticationKind AkDeviceUser = new AuthenticationKind("akDeviceUser");
    /**
     * Personal Identification Number (numeric or alphanumeric)
    */
    public static AuthenticationKind AkPIN = new AuthenticationKind("akPIN");
    /**
     * Authentication as the device service account
    */
    public static AuthenticationKind AkDeviceService = new AuthenticationKind("akDeviceService");
    /**
     * Authentication using push-button authentication
    */
    public static AuthenticationKind AkPushButton = new AuthenticationKind("akPushButton");
    /**
     * Lightweight Directory Access Protocol (to Active Directory)
    */
    public static AuthenticationKind AkLDAP = new AuthenticationKind("akLDAP");
    /**
     * Includes NTLM, Windows Negotiated, and Kerberos.
    */
    public static AuthenticationKind AkWindows = new AuthenticationKind("akWindows");
    /**
     * Smart Card Integrated with Windows Kerberos.
    */
    public static AuthenticationKind AkWindowsSmartCard = new AuthenticationKind("akWindowsSmartCard");
    /**
     * The authentication access point is provided by an extension to the device.
    */
    public static AuthenticationKind AkCustom = new AuthenticationKind("akCustom");

    protected static Hashtable<String, AuthenticationKind> definitions;
    
    static {
        definitions = new Hashtable<String, AuthenticationKind> ();
        definitions.put(AkOther.getValue(), AkOther);
        definitions.put(AkDeviceAdmin.getValue(), AkDeviceAdmin);
        definitions.put(AkDeviceUser.getValue(), AkDeviceUser);
        definitions.put(AkPIN.getValue(), AkPIN);
        definitions.put(AkDeviceService.getValue(), AkDeviceService);
        definitions.put(AkPushButton.getValue(), AkPushButton);
        definitions.put(AkLDAP.getValue(), AkLDAP);
        definitions.put(AkWindows.getValue(), AkWindows);
        definitions.put(AkWindowsSmartCard.getValue(), AkWindowsSmartCard);
        definitions.put(AkCustom.getValue(), AkCustom);
    }

    private AuthenticationKind() {
        this(null);
    }

    private AuthenticationKind(String name) {
        this(name, name);
    }

    private AuthenticationKind(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = SecurityTypesManifest.getInstance().MajorVersion;
        typeName = "authenticationKind";
        typeGUN = "com.hp.ext.types.security.version.1.type.authenticationKind";
    }

    public static AuthenticationKind Parse(String name)
    {
        AuthenticationKind instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  AuthenticationKind(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<AuthenticationKind> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public AuthenticationKind deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return AuthenticationKind.Parse(node.asText());
        }
    }
}
