/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.security;

import com.hp.ext.types.common.E2Alias;

/**
 * The value of the item as a string.
 */
public class KeyValuePairValue extends E2Alias<String> 
{
    public KeyValuePairValue() 
    {
        this(null);
    }

    public KeyValuePairValue(String value)
    {
        super(value);
        majorVersion = SecurityTypesManifest.getInstance().MajorVersion;
        typeName = "keyValuePairValue";
        typeGUN = "com.hp.ext.types.security.version.1.type.keyValuePairValue";
    }

    public KeyValuePairValue valueOf(String value) { return new KeyValuePairValue(value); }

    @Override public String toString() { return value.toString(); }
}
