/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.security;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A subset of information for a given user policy agent. Used by the authenticationUserInfo object to
 * track the one-or-more user policy agents involved in defining the policy and permissions for the
 * authenticated user.
 */
public class UserPolicyAgentInfo extends E2Type
{
    private com.hp.ext.types.agent.AgentId agentId;
    private com.hp.ext.types.agent.AgentName agentName;
    
    @JsonProperty("agentId")
    public com.hp.ext.types.agent.AgentId getAgentId() {
        return agentId;
    }

    @JsonProperty("agentId")
    public void setAgentId(com.hp.ext.types.agent.AgentId agentId) {
        this.agentId = agentId;
    }
    @JsonProperty("agentName")
    public com.hp.ext.types.agent.AgentName getAgentName() {
        return agentName;
    }

    @JsonProperty("agentName")
    public void setAgentName(com.hp.ext.types.agent.AgentName agentName) {
        this.agentName = agentName;
    }
    public UserPolicyAgentInfo()
    {
        majorVersion = SecurityTypesManifest.getInstance().MajorVersion;
        typeName = "userPolicyAgentInfo";
        typeGUN = "com.hp.ext.types.security.version.1.type.userPolicyAgentInfo";
    }
}
