/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.copy;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * This variant holds an explicit value for the bindable parameter.
 */
public class ReleaseStoredJobRequest_SolutionContext_Value extends E2Type
{
    private com.hp.ext.types.common.SolutionContext explicitValue;
    
    @JsonProperty("explicitValue")
    public com.hp.ext.types.common.SolutionContext getExplicitValue() {
        return explicitValue;
    }

    @JsonProperty("explicitValue")
    public void setExplicitValue(com.hp.ext.types.common.SolutionContext explicitValue) {
        this.explicitValue = explicitValue;
    }
    public ReleaseStoredJobRequest_SolutionContext_Value()
    {
        majorVersion = CopyManifest.getInstance().MajorVersion;
        typeName = "releaseStoredJobRequest_solutionContext_value";
        typeGUN = "com.hp.ext.service.copy.version.1.type.releaseStoredJobRequest_solutionContext_value";
    }
}
