/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.printJob;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A registration record that indicates the solution will use features of the PrintJob service. Providing a
 * registration record of this type gives the solution the right to use priority printing
 * features as provided through IPP when such IPP requests are authenticated with an access token associated
 * with this solution.
 */
public class PrintJobAgentRegistrationRecord extends E2Type
{
    private com.hp.ext.types.agent.AgentId agentId;
    private com.hp.ext.types.localization.LocalizedStringReference localizedDescription;
    private com.hp.ext.types.localization.LocalizedStringReference localizedName;
    private com.hp.ext.types.agent.AgentName name;
    
    @JsonProperty("agentId")
    public com.hp.ext.types.agent.AgentId getAgentId() {
        return agentId;
    }

    @JsonProperty("agentId")
    public void setAgentId(com.hp.ext.types.agent.AgentId agentId) {
        this.agentId = agentId;
    }
    @JsonProperty("localizedDescription")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedDescription() {
        return localizedDescription;
    }

    @JsonProperty("localizedDescription")
    public void setLocalizedDescription(com.hp.ext.types.localization.LocalizedStringReference localizedDescription) {
        this.localizedDescription = localizedDescription;
    }
    @JsonProperty("localizedName")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedName() {
        return localizedName;
    }

    @JsonProperty("localizedName")
    public void setLocalizedName(com.hp.ext.types.localization.LocalizedStringReference localizedName) {
        this.localizedName = localizedName;
    }
    @JsonProperty("name")
    public com.hp.ext.types.agent.AgentName getName() {
        return name;
    }

    @JsonProperty("name")
    public void setName(com.hp.ext.types.agent.AgentName name) {
        this.name = name;
    }
    public PrintJobAgentRegistrationRecord()
    {
        majorVersion = PrintJobManifest.getInstance().MajorVersion;
        typeName = "printJobAgentRegistrationRecord";
        typeGUN = "com.hp.ext.service.printJob.version.1.type.printJobAgentRegistrationRecord";
    }
}
