/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.authentication;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Authentication succeeded.
 */
public class AuthenticationSuccess extends E2Type
{
    private com.hp.ext.types.security.WritableAuthenticatedUserDetails details;
    
    @JsonProperty("details")
    public com.hp.ext.types.security.WritableAuthenticatedUserDetails getDetails() {
        return details;
    }

    @JsonProperty("details")
    public void setDetails(com.hp.ext.types.security.WritableAuthenticatedUserDetails details) {
        this.details = details;
    }
    public AuthenticationSuccess()
    {
        majorVersion = AuthenticationTypesManifest.getInstance().MajorVersion;
        typeName = "authenticationSuccess";
        typeGUN = "com.hp.ext.types.authentication.version.1.type.authenticationSuccess";
    }
}
