/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.authentication;

import com.hp.ext.types.common.E2Type;
import com.hp.ext.types.common.IE2Polymorph;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;

/**
 * The set of target types that are allowed for service definitions.
 */
@JsonSerialize(using = AuthenticationTarget.Serializer.class)
public class AuthenticationTarget extends E2Type implements IE2Polymorph
{
    private Object polymorphInstance;

    public Object getInstance() {
        return polymorphInstance;
    }

    public void setInstance(Object o) {
        polymorphInstance = o;
    }

    public boolean isHttp()
    { 
        return polymorphInstance instanceof com.hp.ext.types.target.HttpServiceClientTarget;
    }

    public void setHttp(com.hp.ext.types.target.HttpServiceClientTarget value) {
        polymorphInstance = value;
    }

    public com.hp.ext.types.target.HttpServiceClientTarget getHttp() {
        return (com.hp.ext.types.target.HttpServiceClientTarget)polymorphInstance;
    }
    public boolean isWorkpath()
    { 
        return polymorphInstance instanceof com.hp.ext.types.target.WorkpathPlatformClientTarget;
    }

    public void setWorkpath(com.hp.ext.types.target.WorkpathPlatformClientTarget value) {
        polymorphInstance = value;
    }

    public com.hp.ext.types.target.WorkpathPlatformClientTarget getWorkpath() {
        return (com.hp.ext.types.target.WorkpathPlatformClientTarget)polymorphInstance;
    }

    public AuthenticationTarget()
    {
        this(null);
    }

    public AuthenticationTarget(Object obj)
    {
        polymorphInstance = obj;
        majorVersion = AuthenticationTypesManifest.getInstance().MajorVersion;
        typeName = "authenticationTarget";
        typeGUN = "com.hp.ext.types.authentication.version.1.type.authenticationTarget";
    }

    public static class Serializer extends StdSerializer<AuthenticationTarget> {
    
        public Serializer() {
            this(null);
        }
      
        public Serializer(Class<AuthenticationTarget> t) {
            super(t);
        }
    
        @Override
        public void serialize(AuthenticationTarget value, JsonGenerator jgen, SerializerProvider provider) 
          throws IOException, JsonProcessingException {
     
            jgen.writeStartObject();
            if (value.isHttp()) {
                jgen.writeObjectField("http", value.getHttp());
            }
            if (value.isWorkpath()) {
                jgen.writeObjectField("workpath", value.getWorkpath());
            }
            jgen.writeEndObject();
        }
    }
};
