/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.authentication;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Authentication failed.
 */
public class AuthenticationFailed extends E2Type
{
    private String message;
    
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    @JsonProperty("message")
    public void setMessage(String message) {
        this.message = message;
    }
    public AuthenticationFailed()
    {
        majorVersion = AuthenticationTypesManifest.getInstance().MajorVersion;
        typeName = "authenticationFailed";
        typeGUN = "com.hp.ext.types.authentication.version.1.type.authenticationFailed";
    }
}
