/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.authentication;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Parameters to the POST operation on the postPromptResult target
 */
public class PostPromptResultRequest extends E2Type
{
    private com.hp.ext.types.localization.LanguageTag languageCode;
    private com.hp.ext.types.authentication.SessionToken sessionAccessToken;
    private com.hp.ext.types.authentication.SessionId sessionId;
    
    @JsonProperty("languageCode")
    public com.hp.ext.types.localization.LanguageTag getLanguageCode() {
        return languageCode;
    }

    @JsonProperty("languageCode")
    public void setLanguageCode(com.hp.ext.types.localization.LanguageTag languageCode) {
        this.languageCode = languageCode;
    }
    @JsonProperty("sessionAccessToken")
    public com.hp.ext.types.authentication.SessionToken getSessionAccessToken() {
        return sessionAccessToken;
    }

    @JsonProperty("sessionAccessToken")
    public void setSessionAccessToken(com.hp.ext.types.authentication.SessionToken sessionAccessToken) {
        this.sessionAccessToken = sessionAccessToken;
    }
    @JsonProperty("sessionId")
    public com.hp.ext.types.authentication.SessionId getSessionId() {
        return sessionId;
    }

    @JsonProperty("sessionId")
    public void setSessionId(com.hp.ext.types.authentication.SessionId sessionId) {
        this.sessionId = sessionId;
    }
    public PostPromptResultRequest()
    {
        majorVersion = AuthenticationTypesManifest.getInstance().MajorVersion;
        typeName = "postPromptResultRequest";
        typeGUN = "com.hp.ext.types.authentication.version.1.type.postPromptResultRequest";
    }
}
