/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.authentication;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * An identifier for an authentication session.
 */
public class SessionId extends com.hp.ext.types.common.UniqueIdentifier {
    
    public SessionId() 
    {
        this(null);
    }

    public SessionId(String value)
    {
        super(value);
        majorVersion = AuthenticationTypesManifest.getInstance().MajorVersion;
        typeName = "sessionId";
        typeGUN = "com.hp.ext.types.authentication.version.1.type.sessionId";
    }

    @Override public String toString() { return value.toString(); }
}
