/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.usbAccessories;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Parameters to the hid open operation.
 */
public class Accessories_Accessory_Hid_Open_Params extends E2Type
{
    private com.hp.ext.service.usbAccessories.Accessories_Accessory_Hid_Open_Params_OperationContext_Binding operationContext;
    private Boolean reportReadingActive;
    
    @JsonProperty("operationContext")
    public com.hp.ext.service.usbAccessories.Accessories_Accessory_Hid_Open_Params_OperationContext_Binding getOperationContext() {
        return operationContext;
    }

    @JsonProperty("operationContext")
    public void setOperationContext(com.hp.ext.service.usbAccessories.Accessories_Accessory_Hid_Open_Params_OperationContext_Binding operationContext) {
        this.operationContext = operationContext;
    }
    @JsonProperty("reportReadingActive")
    public Boolean getReportReadingActive() {
        return reportReadingActive;
    }

    @JsonProperty("reportReadingActive")
    public void setReportReadingActive(Boolean reportReadingActive) {
        this.reportReadingActive = reportReadingActive;
    }
    public Accessories_Accessory_Hid_Open_Params()
    {
        majorVersion = UsbAccessoriesManifest.getInstance().MajorVersion;
        typeName = "accessories_accessory_hid_open_params";
        typeGUN = "com.hp.ext.service.usbAccessories.version.1.type.accessories_accessory_hid_open_params";
    }
}
