/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.usbAccessories;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the <accessories>/{accessoryID} resource.
 */
public class Accessory extends E2Type
{
    private com.hp.ext.types.base.OperationMeta opMeta;
    private java.util.UUID accessoryID;
    private com.hp.ext.types.protocol.Byte activeConfiguration;
    private java.util.List<com.hp.ext.types.base.Link> links;
    private com.hp.ext.service.usbAccessories.RegistrationKind registration;
    private java.util.UUID resourceId;
    private com.hp.ext.types.protocol.Byte deviceClass;
    private com.hp.ext.types.protocol.Byte deviceProtocol;
    private com.hp.ext.types.protocol.Byte deviceSubclass;
    private com.hp.ext.types.protocol.Unsigned16 deviceVersion;
    private java.util.List<com.hp.ext.types.usb.UsbLanguageId> languagesSupported;
    private com.hp.ext.types.usb.UsbString manufacturerName;
    private com.hp.ext.types.protocol.Unsigned16 productId;
    private com.hp.ext.types.usb.UsbString productName;
    private com.hp.ext.types.usb.UsbString serialNumber;
    private com.hp.ext.types.protocol.Unsigned16 usbVersion;
    private com.hp.ext.types.protocol.Unsigned16 vendorId;
    
    @JsonProperty("$opMeta")
    public com.hp.ext.types.base.OperationMeta getopMeta() {
        return opMeta;
    }

    @JsonProperty("$opMeta")
    public void setopMeta(com.hp.ext.types.base.OperationMeta opMeta) {
        this.opMeta = opMeta;
    }
    @JsonProperty("accessoryID")
    public java.util.UUID getAccessoryID() {
        return accessoryID;
    }

    @JsonProperty("accessoryID")
    public void setAccessoryID(java.util.UUID accessoryID) {
        this.accessoryID = accessoryID;
    }
    @JsonProperty("activeConfiguration")
    public com.hp.ext.types.protocol.Byte getActiveConfiguration() {
        return activeConfiguration;
    }

    @JsonProperty("activeConfiguration")
    public void setActiveConfiguration(com.hp.ext.types.protocol.Byte activeConfiguration) {
        this.activeConfiguration = activeConfiguration;
    }
    @JsonProperty("links")
    public java.util.List<com.hp.ext.types.base.Link> getLinks() {
        return links;
    }

    @JsonProperty("links")
    public void setLinks(java.util.List<com.hp.ext.types.base.Link> links) {
        this.links = links;
    }
    @JsonProperty("registration")
    public com.hp.ext.service.usbAccessories.RegistrationKind getRegistration() {
        return registration;
    }

    @JsonProperty("registration")
    public void setRegistration(com.hp.ext.service.usbAccessories.RegistrationKind registration) {
        this.registration = registration;
    }
    @JsonProperty("resourceId")
    public java.util.UUID getResourceId() {
        return resourceId;
    }

    @JsonProperty("resourceId")
    public void setResourceId(java.util.UUID resourceId) {
        this.resourceId = resourceId;
    }
    @JsonProperty("deviceClass")
    public com.hp.ext.types.protocol.Byte getDeviceClass() {
        return deviceClass;
    }

    @JsonProperty("deviceClass")
    public void setDeviceClass(com.hp.ext.types.protocol.Byte deviceClass) {
        this.deviceClass = deviceClass;
    }
    @JsonProperty("deviceProtocol")
    public com.hp.ext.types.protocol.Byte getDeviceProtocol() {
        return deviceProtocol;
    }

    @JsonProperty("deviceProtocol")
    public void setDeviceProtocol(com.hp.ext.types.protocol.Byte deviceProtocol) {
        this.deviceProtocol = deviceProtocol;
    }
    @JsonProperty("deviceSubclass")
    public com.hp.ext.types.protocol.Byte getDeviceSubclass() {
        return deviceSubclass;
    }

    @JsonProperty("deviceSubclass")
    public void setDeviceSubclass(com.hp.ext.types.protocol.Byte deviceSubclass) {
        this.deviceSubclass = deviceSubclass;
    }
    @JsonProperty("deviceVersion")
    public com.hp.ext.types.protocol.Unsigned16 getDeviceVersion() {
        return deviceVersion;
    }

    @JsonProperty("deviceVersion")
    public void setDeviceVersion(com.hp.ext.types.protocol.Unsigned16 deviceVersion) {
        this.deviceVersion = deviceVersion;
    }
    @JsonProperty("languagesSupported")
    public java.util.List<com.hp.ext.types.usb.UsbLanguageId> getLanguagesSupported() {
        return languagesSupported;
    }

    @JsonProperty("languagesSupported")
    public void setLanguagesSupported(java.util.List<com.hp.ext.types.usb.UsbLanguageId> languagesSupported) {
        this.languagesSupported = languagesSupported;
    }
    @JsonProperty("manufacturerName")
    public com.hp.ext.types.usb.UsbString getManufacturerName() {
        return manufacturerName;
    }

    @JsonProperty("manufacturerName")
    public void setManufacturerName(com.hp.ext.types.usb.UsbString manufacturerName) {
        this.manufacturerName = manufacturerName;
    }
    @JsonProperty("productId")
    public com.hp.ext.types.protocol.Unsigned16 getProductId() {
        return productId;
    }

    @JsonProperty("productId")
    public void setProductId(com.hp.ext.types.protocol.Unsigned16 productId) {
        this.productId = productId;
    }
    @JsonProperty("productName")
    public com.hp.ext.types.usb.UsbString getProductName() {
        return productName;
    }

    @JsonProperty("productName")
    public void setProductName(com.hp.ext.types.usb.UsbString productName) {
        this.productName = productName;
    }
    @JsonProperty("serialNumber")
    public com.hp.ext.types.usb.UsbString getSerialNumber() {
        return serialNumber;
    }

    @JsonProperty("serialNumber")
    public void setSerialNumber(com.hp.ext.types.usb.UsbString serialNumber) {
        this.serialNumber = serialNumber;
    }
    @JsonProperty("usbVersion")
    public com.hp.ext.types.protocol.Unsigned16 getUsbVersion() {
        return usbVersion;
    }

    @JsonProperty("usbVersion")
    public void setUsbVersion(com.hp.ext.types.protocol.Unsigned16 usbVersion) {
        this.usbVersion = usbVersion;
    }
    @JsonProperty("vendorId")
    public com.hp.ext.types.protocol.Unsigned16 getVendorId() {
        return vendorId;
    }

    @JsonProperty("vendorId")
    public void setVendorId(com.hp.ext.types.protocol.Unsigned16 vendorId) {
        this.vendorId = vendorId;
    }
    public Accessory()
    {
        majorVersion = UsbAccessoriesManifest.getInstance().MajorVersion;
        typeName = "accessory";
        typeGUN = "com.hp.ext.service.usbAccessories.version.1.type.accessory";
    }
}
