/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.usbAccessories;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * This indicates that data was read from the HID accessory.
 */
public class HidReadCallbackPayload extends E2Type
{
    private com.hp.ext.service.usbAccessories.UsbData data;
    private Long hidReadSequence;
    
    @JsonProperty("data")
    public com.hp.ext.service.usbAccessories.UsbData getData() {
        return data;
    }

    @JsonProperty("data")
    public void setData(com.hp.ext.service.usbAccessories.UsbData data) {
        this.data = data;
    }
    @JsonProperty("hidReadSequence")
    public Long getHidReadSequence() {
        return hidReadSequence;
    }

    @JsonProperty("hidReadSequence")
    public void setHidReadSequence(Long hidReadSequence) {
        this.hidReadSequence = hidReadSequence;
    }
    public HidReadCallbackPayload()
    {
        majorVersion = UsbAccessoriesManifest.getInstance().MajorVersion;
        typeName = "hidReadCallbackPayload";
        typeGUN = "com.hp.ext.service.usbAccessories.version.1.type.hidReadCallbackPayload";
    }
}
