/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.usbAccessories;

import com.hp.ext.types.common.E2Type;

/**
 * No callback was provided when such a callback is required.
 */
public class NoCallbackError extends E2Type
{
    
    public NoCallbackError()
    {
        majorVersion = UsbAccessoriesManifest.getInstance().MajorVersion;
        typeName = "noCallbackError";
        typeGUN = "com.hp.ext.service.usbAccessories.version.1.type.noCallbackError";
    }
}
