/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.usbAccessories;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the JSON body parameters for the Modify operation of the <accessories>/{accessoryID}/generic/{openAccessoryID} resource.
 */
public class OpenAccessory_Modify extends E2Type
{
    private com.hp.ext.types.protocol.Byte activeConfiguration;
    private com.hp.ext.types.protocol.Byte activeInterfaceId;
    private java.util.List<com.hp.ext.types.protocol.Byte> claimedInterfaces;
    
    @JsonProperty("activeConfiguration")
    public com.hp.ext.types.protocol.Byte getActiveConfiguration() {
        return activeConfiguration;
    }

    @JsonProperty("activeConfiguration")
    public void setActiveConfiguration(com.hp.ext.types.protocol.Byte activeConfiguration) {
        this.activeConfiguration = activeConfiguration;
    }
    @JsonProperty("activeInterfaceId")
    public com.hp.ext.types.protocol.Byte getActiveInterfaceId() {
        return activeInterfaceId;
    }

    @JsonProperty("activeInterfaceId")
    public void setActiveInterfaceId(com.hp.ext.types.protocol.Byte activeInterfaceId) {
        this.activeInterfaceId = activeInterfaceId;
    }
    @JsonProperty("claimedInterfaces")
    public java.util.List<com.hp.ext.types.protocol.Byte> getClaimedInterfaces() {
        return claimedInterfaces;
    }

    @JsonProperty("claimedInterfaces")
    public void setClaimedInterfaces(java.util.List<com.hp.ext.types.protocol.Byte> claimedInterfaces) {
        this.claimedInterfaces = claimedInterfaces;
    }
    public OpenAccessory_Modify()
    {
        majorVersion = UsbAccessoriesManifest.getInstance().MajorVersion;
        typeName = "openAccessory_modify";
        typeGUN = "com.hp.ext.service.usbAccessories.version.1.type.openAccessory_modify";
    }
}
