/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.usbAccessories;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The envelope for the USB callback message
 */
public class UsbCallbackEnvelope extends E2Type
{
    private String operationContext;
    private com.hp.ext.service.usbAccessories.UsbCallback usbCallback;
    
    @JsonProperty("operationContext")
    public String getOperationContext() {
        return operationContext;
    }

    @JsonProperty("operationContext")
    public void setOperationContext(String operationContext) {
        this.operationContext = operationContext;
    }
    @JsonProperty("usbCallback")
    public com.hp.ext.service.usbAccessories.UsbCallback getUsbCallback() {
        return usbCallback;
    }

    @JsonProperty("usbCallback")
    public void setUsbCallback(com.hp.ext.service.usbAccessories.UsbCallback usbCallback) {
        this.usbCallback = usbCallback;
    }
    public UsbCallbackEnvelope()
    {
        majorVersion = UsbAccessoriesManifest.getInstance().MajorVersion;
        typeName = "usbCallbackEnvelope";
        typeGUN = "com.hp.ext.service.usbAccessories.version.1.type.usbCallbackEnvelope";
    }
}
