/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.usbAccessories;

import com.hp.ext.types.common.E2Alias;

/**
 * Binary data acquired from or destined for a USB request.
 */
public class UsbData extends E2Alias<String> 
{
    public UsbData() 
    {
        this(null);
    }

    public UsbData(String value)
    {
        super(value);
        majorVersion = UsbAccessoriesManifest.getInstance().MajorVersion;
        typeName = "usbData";
        typeGUN = "com.hp.ext.service.usbAccessories.version.1.type.usbData";
    }

    public UsbData valueOf(String value) { return new UsbData(value); }

    @Override public String toString() { return value.toString(); }
}
