/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.usbAccessories;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Describes one USB endpoint
 */
public class UsbEndpoint extends E2Type
{
    private com.hp.ext.service.usbAccessories.EndpointNumber endpointAddress;
    private com.hp.ext.types.protocol.Byte endpointAttributes;
    private com.hp.ext.types.protocol.Unsigned16 packetSize;
    
    @JsonProperty("endpointAddress")
    public com.hp.ext.service.usbAccessories.EndpointNumber getEndpointAddress() {
        return endpointAddress;
    }

    @JsonProperty("endpointAddress")
    public void setEndpointAddress(com.hp.ext.service.usbAccessories.EndpointNumber endpointAddress) {
        this.endpointAddress = endpointAddress;
    }
    @JsonProperty("endpointAttributes")
    public com.hp.ext.types.protocol.Byte getEndpointAttributes() {
        return endpointAttributes;
    }

    @JsonProperty("endpointAttributes")
    public void setEndpointAttributes(com.hp.ext.types.protocol.Byte endpointAttributes) {
        this.endpointAttributes = endpointAttributes;
    }
    @JsonProperty("packetSize")
    public com.hp.ext.types.protocol.Unsigned16 getPacketSize() {
        return packetSize;
    }

    @JsonProperty("packetSize")
    public void setPacketSize(com.hp.ext.types.protocol.Unsigned16 packetSize) {
        this.packetSize = packetSize;
    }
    public UsbEndpoint()
    {
        majorVersion = UsbAccessoriesManifest.getInstance().MajorVersion;
        typeName = "usbEndpoint";
        typeGUN = "com.hp.ext.service.usbAccessories.version.1.type.usbEndpoint";
    }
}
