/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.usbAccessories;

import com.hp.ext.types.common.E2Type;
import com.hp.ext.types.common.IE2Polymorph;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;

/**
 * The payload carried with a USB registration notification.
 */
@JsonSerialize(using = UsbRegistrationPayload.Serializer.class)
public class UsbRegistrationPayload extends E2Type implements IE2Polymorph
{
    private Object polymorphInstance;

    public Object getInstance() {
        return polymorphInstance;
    }

    public void setInstance(Object o) {
        polymorphInstance = o;
    }

    public boolean isUsbAttached()
    { 
        return polymorphInstance instanceof com.hp.ext.service.usbAccessories.UsbAttached;
    }

    public void setUsbAttached(com.hp.ext.service.usbAccessories.UsbAttached value) {
        polymorphInstance = value;
    }

    public com.hp.ext.service.usbAccessories.UsbAttached getUsbAttached() {
        return (com.hp.ext.service.usbAccessories.UsbAttached)polymorphInstance;
    }
    public boolean isUsbDetached()
    { 
        return polymorphInstance instanceof com.hp.ext.service.usbAccessories.UsbDetached;
    }

    public void setUsbDetached(com.hp.ext.service.usbAccessories.UsbDetached value) {
        polymorphInstance = value;
    }

    public com.hp.ext.service.usbAccessories.UsbDetached getUsbDetached() {
        return (com.hp.ext.service.usbAccessories.UsbDetached)polymorphInstance;
    }

    public UsbRegistrationPayload()
    {
        this(null);
    }

    public UsbRegistrationPayload(Object obj)
    {
        polymorphInstance = obj;
        majorVersion = UsbAccessoriesManifest.getInstance().MajorVersion;
        typeName = "usbRegistrationPayload";
        typeGUN = "com.hp.ext.service.usbAccessories.version.1.type.usbRegistrationPayload";
    }

    public static class Serializer extends StdSerializer<UsbRegistrationPayload> {
    
        public Serializer() {
            this(null);
        }
      
        public Serializer(Class<UsbRegistrationPayload> t) {
            super(t);
        }
    
        @Override
        public void serialize(UsbRegistrationPayload value, JsonGenerator jgen, SerializerProvider provider) 
          throws IOException, JsonProcessingException {
     
            jgen.writeStartObject();
            if (value.isUsbAttached()) {
                jgen.writeObjectField("usbAttached", value.getUsbAttached());
            }
            if (value.isUsbDetached()) {
                jgen.writeObjectField("usbDetached", value.getUsbDetached());
            }
            jgen.writeEndObject();
        }
    }
};
