/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.usbAccessories;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Callback payload for read callbacks.
 */
public class UsbReadCallbackPayload extends E2Type
{
    private com.hp.ext.service.usbAccessories.UsbData data;
    private String operationId;
    private com.hp.ext.service.usbAccessories.UsbTransferStatus usbTransferStatus;
    
    @JsonProperty("data")
    public com.hp.ext.service.usbAccessories.UsbData getData() {
        return data;
    }

    @JsonProperty("data")
    public void setData(com.hp.ext.service.usbAccessories.UsbData data) {
        this.data = data;
    }
    @JsonProperty("operationId")
    public String getOperationId() {
        return operationId;
    }

    @JsonProperty("operationId")
    public void setOperationId(String operationId) {
        this.operationId = operationId;
    }
    @JsonProperty("usbTransferStatus")
    public com.hp.ext.service.usbAccessories.UsbTransferStatus getUsbTransferStatus() {
        return usbTransferStatus;
    }

    @JsonProperty("usbTransferStatus")
    public void setUsbTransferStatus(com.hp.ext.service.usbAccessories.UsbTransferStatus usbTransferStatus) {
        this.usbTransferStatus = usbTransferStatus;
    }
    public UsbReadCallbackPayload()
    {
        majorVersion = UsbAccessoriesManifest.getInstance().MajorVersion;
        typeName = "usbReadCallbackPayload";
        typeGUN = "com.hp.ext.service.usbAccessories.version.1.type.usbReadCallbackPayload";
    }
}
