/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.usbAccessories;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * The status of a USB transfer.
 */
@JsonDeserialize(using = UsbTransferStatus.Deserializer.class)
public class UsbTransferStatus extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * Transfer successful.
    */
    public static UsbTransferStatus UtsOk = new UsbTransferStatus("utsOk");
    /**
     * Fewer bytes than requested were transferred.
    */
    public static UsbTransferStatus UtsStall = new UsbTransferStatus("utsStall");
    /**
     * More bytes than requested were attempted to be transferred.
    */
    public static UsbTransferStatus UtsBabble = new UsbTransferStatus("utsBabble");

    protected static Hashtable<String, UsbTransferStatus> definitions;
    
    static {
        definitions = new Hashtable<String, UsbTransferStatus> ();
        definitions.put(UtsOk.getValue(), UtsOk);
        definitions.put(UtsStall.getValue(), UtsStall);
        definitions.put(UtsBabble.getValue(), UtsBabble);
    }

    private UsbTransferStatus() {
        this(null);
    }

    private UsbTransferStatus(String name) {
        this(name, name);
    }

    private UsbTransferStatus(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = UsbAccessoriesManifest.getInstance().MajorVersion;
        typeName = "usbTransferStatus";
        typeGUN = "com.hp.ext.service.usbAccessories.version.1.type.usbTransferStatus";
    }

    public static UsbTransferStatus Parse(String name)
    {
        UsbTransferStatus instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  UsbTransferStatus(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<UsbTransferStatus> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public UsbTransferStatus deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return UsbTransferStatus.Parse(node.asText());
        }
    }
}
