/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.usbAccessories;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Callback payload for write callbacks.
 */
public class UsbWriteCallbackPayload extends E2Type
{
    private com.hp.ext.types.protocol.Unsigned16 bytesWritten;
    private String operationId;
    private com.hp.ext.service.usbAccessories.UsbTransferStatus usbTransferStatus;
    
    @JsonProperty("bytesWritten")
    public com.hp.ext.types.protocol.Unsigned16 getBytesWritten() {
        return bytesWritten;
    }

    @JsonProperty("bytesWritten")
    public void setBytesWritten(com.hp.ext.types.protocol.Unsigned16 bytesWritten) {
        this.bytesWritten = bytesWritten;
    }
    @JsonProperty("operationId")
    public String getOperationId() {
        return operationId;
    }

    @JsonProperty("operationId")
    public void setOperationId(String operationId) {
        this.operationId = operationId;
    }
    @JsonProperty("usbTransferStatus")
    public com.hp.ext.service.usbAccessories.UsbTransferStatus getUsbTransferStatus() {
        return usbTransferStatus;
    }

    @JsonProperty("usbTransferStatus")
    public void setUsbTransferStatus(com.hp.ext.service.usbAccessories.UsbTransferStatus usbTransferStatus) {
        this.usbTransferStatus = usbTransferStatus;
    }
    public UsbWriteCallbackPayload()
    {
        majorVersion = UsbAccessoriesManifest.getInstance().MajorVersion;
        typeName = "usbWriteCallbackPayload";
        typeGUN = "com.hp.ext.service.usbAccessories.version.1.type.usbWriteCallbackPayload";
    }
}
