/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.usb;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * This type groups the set of fields that describe a HID device.
 */
public class HidDescriptionFields extends E2Type
{
    private com.hp.ext.types.protocol.Byte featureReportLength;
    private com.hp.ext.types.protocol.Byte hardwareCountryCode;
    private com.hp.ext.types.protocol.Byte inputReportLength;
    private com.hp.ext.types.protocol.Byte outputReportLength;
    
    @JsonProperty("featureReportLength")
    public com.hp.ext.types.protocol.Byte getFeatureReportLength() {
        return featureReportLength;
    }

    @JsonProperty("featureReportLength")
    public void setFeatureReportLength(com.hp.ext.types.protocol.Byte featureReportLength) {
        this.featureReportLength = featureReportLength;
    }
    @JsonProperty("hardwareCountryCode")
    public com.hp.ext.types.protocol.Byte getHardwareCountryCode() {
        return hardwareCountryCode;
    }

    @JsonProperty("hardwareCountryCode")
    public void setHardwareCountryCode(com.hp.ext.types.protocol.Byte hardwareCountryCode) {
        this.hardwareCountryCode = hardwareCountryCode;
    }
    @JsonProperty("inputReportLength")
    public com.hp.ext.types.protocol.Byte getInputReportLength() {
        return inputReportLength;
    }

    @JsonProperty("inputReportLength")
    public void setInputReportLength(com.hp.ext.types.protocol.Byte inputReportLength) {
        this.inputReportLength = inputReportLength;
    }
    @JsonProperty("outputReportLength")
    public com.hp.ext.types.protocol.Byte getOutputReportLength() {
        return outputReportLength;
    }

    @JsonProperty("outputReportLength")
    public void setOutputReportLength(com.hp.ext.types.protocol.Byte outputReportLength) {
        this.outputReportLength = outputReportLength;
    }
    public HidDescriptionFields()
    {
        majorVersion = UsbTypesManifest.getInstance().MajorVersion;
        typeName = "hidDescriptionFields";
        typeGUN = "com.hp.ext.types.usbTypes.version.1.type.hidDescriptionFields";
    }
}
