/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.usb;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * This type groups the set of fields that describe a USB device.
 */
public class UsbDescriptionFields extends E2Type
{
    private com.hp.ext.types.protocol.Byte deviceClass;
    private com.hp.ext.types.protocol.Byte deviceProtocol;
    private com.hp.ext.types.protocol.Byte deviceSubclass;
    private com.hp.ext.types.protocol.Unsigned16 deviceVersion;
    private java.util.List<com.hp.ext.types.usb.UsbLanguageId> languagesSupported;
    private com.hp.ext.types.usb.UsbString manufacturerName;
    private com.hp.ext.types.protocol.Unsigned16 productId;
    private com.hp.ext.types.usb.UsbString productName;
    private com.hp.ext.types.usb.UsbString serialNumber;
    private com.hp.ext.types.protocol.Unsigned16 usbVersion;
    private com.hp.ext.types.protocol.Unsigned16 vendorId;
    
    @JsonProperty("deviceClass")
    public com.hp.ext.types.protocol.Byte getDeviceClass() {
        return deviceClass;
    }

    @JsonProperty("deviceClass")
    public void setDeviceClass(com.hp.ext.types.protocol.Byte deviceClass) {
        this.deviceClass = deviceClass;
    }
    @JsonProperty("deviceProtocol")
    public com.hp.ext.types.protocol.Byte getDeviceProtocol() {
        return deviceProtocol;
    }

    @JsonProperty("deviceProtocol")
    public void setDeviceProtocol(com.hp.ext.types.protocol.Byte deviceProtocol) {
        this.deviceProtocol = deviceProtocol;
    }
    @JsonProperty("deviceSubclass")
    public com.hp.ext.types.protocol.Byte getDeviceSubclass() {
        return deviceSubclass;
    }

    @JsonProperty("deviceSubclass")
    public void setDeviceSubclass(com.hp.ext.types.protocol.Byte deviceSubclass) {
        this.deviceSubclass = deviceSubclass;
    }
    @JsonProperty("deviceVersion")
    public com.hp.ext.types.protocol.Unsigned16 getDeviceVersion() {
        return deviceVersion;
    }

    @JsonProperty("deviceVersion")
    public void setDeviceVersion(com.hp.ext.types.protocol.Unsigned16 deviceVersion) {
        this.deviceVersion = deviceVersion;
    }
    @JsonProperty("languagesSupported")
    public java.util.List<com.hp.ext.types.usb.UsbLanguageId> getLanguagesSupported() {
        return languagesSupported;
    }

    @JsonProperty("languagesSupported")
    public void setLanguagesSupported(java.util.List<com.hp.ext.types.usb.UsbLanguageId> languagesSupported) {
        this.languagesSupported = languagesSupported;
    }
    @JsonProperty("manufacturerName")
    public com.hp.ext.types.usb.UsbString getManufacturerName() {
        return manufacturerName;
    }

    @JsonProperty("manufacturerName")
    public void setManufacturerName(com.hp.ext.types.usb.UsbString manufacturerName) {
        this.manufacturerName = manufacturerName;
    }
    @JsonProperty("productId")
    public com.hp.ext.types.protocol.Unsigned16 getProductId() {
        return productId;
    }

    @JsonProperty("productId")
    public void setProductId(com.hp.ext.types.protocol.Unsigned16 productId) {
        this.productId = productId;
    }
    @JsonProperty("productName")
    public com.hp.ext.types.usb.UsbString getProductName() {
        return productName;
    }

    @JsonProperty("productName")
    public void setProductName(com.hp.ext.types.usb.UsbString productName) {
        this.productName = productName;
    }
    @JsonProperty("serialNumber")
    public com.hp.ext.types.usb.UsbString getSerialNumber() {
        return serialNumber;
    }

    @JsonProperty("serialNumber")
    public void setSerialNumber(com.hp.ext.types.usb.UsbString serialNumber) {
        this.serialNumber = serialNumber;
    }
    @JsonProperty("usbVersion")
    public com.hp.ext.types.protocol.Unsigned16 getUsbVersion() {
        return usbVersion;
    }

    @JsonProperty("usbVersion")
    public void setUsbVersion(com.hp.ext.types.protocol.Unsigned16 usbVersion) {
        this.usbVersion = usbVersion;
    }
    @JsonProperty("vendorId")
    public com.hp.ext.types.protocol.Unsigned16 getVendorId() {
        return vendorId;
    }

    @JsonProperty("vendorId")
    public void setVendorId(com.hp.ext.types.protocol.Unsigned16 vendorId) {
        this.vendorId = vendorId;
    }
    public UsbDescriptionFields()
    {
        majorVersion = UsbTypesManifest.getInstance().MajorVersion;
        typeName = "usbDescriptionFields";
        typeGUN = "com.hp.ext.types.usbTypes.version.1.type.usbDescriptionFields";
    }
}
