/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.sdkSupport;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type returned by the execute operation of the <echo> resource.
 */
public class Echo_Execute extends E2Type
{
    private com.hp.ext.types.base.OperationMeta opMeta;
    private Object echoData;
    private java.util.List<com.hp.ext.types.base.Link> links;
    private Object queryParameters;
    
    @JsonProperty("$opMeta")
    public com.hp.ext.types.base.OperationMeta getopMeta() {
        return opMeta;
    }

    @JsonProperty("$opMeta")
    public void setopMeta(com.hp.ext.types.base.OperationMeta opMeta) {
        this.opMeta = opMeta;
    }
    @JsonProperty("echoData")
    public Object getEchoData() {
        return echoData;
    }

    @JsonProperty("echoData")
    public void setEchoData(Object echoData) {
        this.echoData = echoData;
    }
    @JsonProperty("links")
    public java.util.List<com.hp.ext.types.base.Link> getLinks() {
        return links;
    }

    @JsonProperty("links")
    public void setLinks(java.util.List<com.hp.ext.types.base.Link> links) {
        this.links = links;
    }
    @JsonProperty("queryParameters")
    public Object getQueryParameters() {
        return queryParameters;
    }

    @JsonProperty("queryParameters")
    public void setQueryParameters(Object queryParameters) {
        this.queryParameters = queryParameters;
    }
    public Echo_Execute()
    {
        majorVersion = SdkSupportManifest.getInstance().MajorVersion;
        typeName = "echo_execute";
        typeGUN = "com.hp.ext.service.sdkSupport.version.1.type.echo_execute";
    }
}
