/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.sdkSupport;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * An error type used when requested for some echo responses.
 */
public class EchoError extends E2Type
{
    private java.lang.Byte errorCode;
    
    @JsonProperty("errorCode")
    public java.lang.Byte getErrorCode() {
        return errorCode;
    }

    @JsonProperty("errorCode")
    public void setErrorCode(java.lang.Byte errorCode) {
        this.errorCode = errorCode;
    }
    public EchoError()
    {
        majorVersion = SdkSupportManifest.getInstance().MajorVersion;
        typeName = "echoError";
        typeGUN = "com.hp.ext.service.sdkSupport.version.1.type.echoError";
    }
}
