/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.sdkSupport;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The primary content includes the configured echo data and any query parameters.
 */
public class Echo_Execute_Params extends E2Type
{
    private Object echoData;
    
    @JsonProperty("echoData")
    public Object getEchoData() {
        return echoData;
    }

    @JsonProperty("echoData")
    public void setEchoData(Object echoData) {
        this.echoData = echoData;
    }
    public Echo_Execute_Params()
    {
        majorVersion = SdkSupportManifest.getInstance().MajorVersion;
        typeName = "echo_execute_params";
        typeGUN = "com.hp.ext.service.sdkSupport.version.1.type.echo_execute_params";
    }
}
