/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.sdkSupport;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * An object used to carry JavaScript content for use with the execute script operation.
 */
public class JavaScriptContent extends E2Type
{
    private String encodedContent;
    
    @JsonProperty("encodedContent")
    public String getEncodedContent() {
        return encodedContent;
    }

    @JsonProperty("encodedContent")
    public void setEncodedContent(String encodedContent) {
        this.encodedContent = encodedContent;
    }
    public JavaScriptContent()
    {
        majorVersion = SdkSupportManifest.getInstance().MajorVersion;
        typeName = "javaScriptContent";
        typeGUN = "com.hp.ext.service.sdkSupport.version.1.type.javaScriptContent";
    }
}
