/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.sdkSupport;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * The enumerated set of all supported key codes.
 */
@JsonDeserialize(using = KeyCode.Deserializer.class)
public class KeyCode extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * The A key
    */
    public static KeyCode KcA = new KeyCode("kcA");
    /**
     * The B key
    */
    public static KeyCode KcB = new KeyCode("kcB");
    /**
     * The C key
    */
    public static KeyCode KcC = new KeyCode("kcC");
    /**
     * The D key
    */
    public static KeyCode KcD = new KeyCode("kcD");
    /**
     * The E key
    */
    public static KeyCode KcE = new KeyCode("kcE");
    /**
     * The F key
    */
    public static KeyCode KcF = new KeyCode("kcF");
    /**
     * The G key
    */
    public static KeyCode KcG = new KeyCode("kcG");
    /**
     * The H key
    */
    public static KeyCode KcH = new KeyCode("kcH");
    /**
     * The I key
    */
    public static KeyCode KcI = new KeyCode("kcI");
    /**
     * The J key
    */
    public static KeyCode KcJ = new KeyCode("kcJ");
    /**
     * The K key
    */
    public static KeyCode KcK = new KeyCode("kcK");
    /**
     * The L key
    */
    public static KeyCode KcL = new KeyCode("kcL");
    /**
     * The M key
    */
    public static KeyCode KcM = new KeyCode("kcM");
    /**
     * The N key
    */
    public static KeyCode KcN = new KeyCode("kcN");
    /**
     * The O key
    */
    public static KeyCode KcO = new KeyCode("kcO");
    /**
     * The P key
    */
    public static KeyCode KcP = new KeyCode("kcP");
    /**
     * The Q key
    */
    public static KeyCode KcQ = new KeyCode("kcQ");
    /**
     * The R key
    */
    public static KeyCode KcR = new KeyCode("kcR");
    /**
     * The S key
    */
    public static KeyCode KcS = new KeyCode("kcS");
    /**
     * The T key
    */
    public static KeyCode KcT = new KeyCode("kcT");
    /**
     * The U key
    */
    public static KeyCode KcU = new KeyCode("kcU");
    /**
     * The V key
    */
    public static KeyCode KcV = new KeyCode("kcV");
    /**
     * The W key
    */
    public static KeyCode KcW = new KeyCode("kcW");
    /**
     * The X key
    */
    public static KeyCode KcX = new KeyCode("kcX");
    /**
     * The Y key
    */
    public static KeyCode KcY = new KeyCode("kcY");
    /**
     * The Z key
    */
    public static KeyCode KcZ = new KeyCode("kcZ");
    /**
     * The 0 (zero) key
    */
    public static KeyCode KcZero = new KeyCode("kcZero");
    /**
     * The 1 key
    */
    public static KeyCode KcOne = new KeyCode("kcOne");
    /**
     * The 2 key
    */
    public static KeyCode KcTwo = new KeyCode("kcTwo");
    /**
     * The 3 key
    */
    public static KeyCode KcThree = new KeyCode("kcThree");
    /**
     * The 4 key
    */
    public static KeyCode KcFour = new KeyCode("kcFour");
    /**
     * The 5  key
    */
    public static KeyCode KcFive = new KeyCode("kcFive");
    /**
     * The 6 key
    */
    public static KeyCode KcSix = new KeyCode("kcSix");
    /**
     * The 7 key
    */
    public static KeyCode KcSeven = new KeyCode("kcSeven");
    /**
     * The 8 key
    */
    public static KeyCode KcEight = new KeyCode("kcEight");
    /**
     * The 9 key
    */
    public static KeyCode KcNine = new KeyCode("kcNine");
    /**
     * The BackQuote key
    */
    public static KeyCode KcBackQuote = new KeyCode("kcBackQuote");
    /**
     * The Minus key
    */
    public static KeyCode KcMinus = new KeyCode("kcMinus");
    /**
     * The Equals key
    */
    public static KeyCode KcEquals = new KeyCode("kcEquals");
    /**
     * The LeftBracket key
    */
    public static KeyCode KcLeftBracket = new KeyCode("kcLeftBracket");
    /**
     * The RightBracket key
    */
    public static KeyCode KcRightBracket = new KeyCode("kcRightBracket");
    /**
     * The Backslash key
    */
    public static KeyCode KcBackslash = new KeyCode("kcBackslash");
    /**
     * The Semicolon key
    */
    public static KeyCode KcSemicolon = new KeyCode("kcSemicolon");
    /**
     * The SingleQuote key
    */
    public static KeyCode KcSingleQuote = new KeyCode("kcSingleQuote");
    /**
     * The Comma key
    */
    public static KeyCode KcComma = new KeyCode("kcComma");
    /**
     * The Period key
    */
    public static KeyCode KcPeriod = new KeyCode("kcPeriod");
    /**
     * The Forwardslash key
    */
    public static KeyCode KcForwardslash = new KeyCode("kcForwardslash");
    /**
     * The Space key
    */
    public static KeyCode KcSpace = new KeyCode("kcSpace");
    /**
     * The Escape key
    */
    public static KeyCode KcEscape = new KeyCode("kcEscape");
    /**
     * The Delete key
    */
    public static KeyCode KcDelete = new KeyCode("kcDelete");
    /**
     * The Backspace key
    */
    public static KeyCode KcBackspace = new KeyCode("kcBackspace");
    /**
     * The Tab key
    */
    public static KeyCode KcTab = new KeyCode("kcTab");
    /**
     * The CapsLock key
    */
    public static KeyCode KcCapsLock = new KeyCode("kcCapsLock");
    /**
     * The Enter key
    */
    public static KeyCode KcEnter = new KeyCode("kcEnter");
    /**
     * The UpArrow key
    */
    public static KeyCode KcUpArrow = new KeyCode("kcUpArrow");
    /**
     * The DownArrow key
    */
    public static KeyCode KcDownArrow = new KeyCode("kcDownArrow");
    /**
     * The LeftArrow key
    */
    public static KeyCode KcLeftArrow = new KeyCode("kcLeftArrow");
    /**
     * The RightArrow key
    */
    public static KeyCode KcRightArrow = new KeyCode("kcRightArrow");
    /**
     * The Start key
    */
    public static KeyCode KcStart = new KeyCode("kcStart");
    /**
     * The Reset key
    */
    public static KeyCode KcResetKey = new KeyCode("kcResetKey");
    /**
     * The Stop key
    */
    public static KeyCode KcStop = new KeyCode("kcStop");
    /**
     * The At-sign (@) key
    */
    public static KeyCode KcAtSign = new KeyCode("kcAtSign");
    /**
     * The Asterisk (*) key
    */
    public static KeyCode KcAsterisk = new KeyCode("kcAsterisk");
    /**
     * The Pound (#) key
    */
    public static KeyCode KcPound = new KeyCode("kcPound");
    /**
     * The Clear key
    */
    public static KeyCode KcClear = new KeyCode("kcClear");
    /**
     * The Help key
    */
    public static KeyCode KcHelp = new KeyCode("kcHelp");
    /**
     * The OK key
    */
    public static KeyCode KcOK = new KeyCode("kcOK");
    /**
     * The Info key
    */
    public static KeyCode KcInfo = new KeyCode("kcInfo");
    /**
     * The Message key
    */
    public static KeyCode KcMessage = new KeyCode("kcMessage");
    /**
     * The SignIn/Out key
    */
    public static KeyCode KcSignInOut = new KeyCode("kcSignInOut");
    /**
     * The Plus (+) key
    */
    public static KeyCode KcPlus = new KeyCode("kcPlus");

    protected static Hashtable<String, KeyCode> definitions;
    
    static {
        definitions = new Hashtable<String, KeyCode> ();
        definitions.put(KcA.getValue(), KcA);
        definitions.put(KcB.getValue(), KcB);
        definitions.put(KcC.getValue(), KcC);
        definitions.put(KcD.getValue(), KcD);
        definitions.put(KcE.getValue(), KcE);
        definitions.put(KcF.getValue(), KcF);
        definitions.put(KcG.getValue(), KcG);
        definitions.put(KcH.getValue(), KcH);
        definitions.put(KcI.getValue(), KcI);
        definitions.put(KcJ.getValue(), KcJ);
        definitions.put(KcK.getValue(), KcK);
        definitions.put(KcL.getValue(), KcL);
        definitions.put(KcM.getValue(), KcM);
        definitions.put(KcN.getValue(), KcN);
        definitions.put(KcO.getValue(), KcO);
        definitions.put(KcP.getValue(), KcP);
        definitions.put(KcQ.getValue(), KcQ);
        definitions.put(KcR.getValue(), KcR);
        definitions.put(KcS.getValue(), KcS);
        definitions.put(KcT.getValue(), KcT);
        definitions.put(KcU.getValue(), KcU);
        definitions.put(KcV.getValue(), KcV);
        definitions.put(KcW.getValue(), KcW);
        definitions.put(KcX.getValue(), KcX);
        definitions.put(KcY.getValue(), KcY);
        definitions.put(KcZ.getValue(), KcZ);
        definitions.put(KcZero.getValue(), KcZero);
        definitions.put(KcOne.getValue(), KcOne);
        definitions.put(KcTwo.getValue(), KcTwo);
        definitions.put(KcThree.getValue(), KcThree);
        definitions.put(KcFour.getValue(), KcFour);
        definitions.put(KcFive.getValue(), KcFive);
        definitions.put(KcSix.getValue(), KcSix);
        definitions.put(KcSeven.getValue(), KcSeven);
        definitions.put(KcEight.getValue(), KcEight);
        definitions.put(KcNine.getValue(), KcNine);
        definitions.put(KcBackQuote.getValue(), KcBackQuote);
        definitions.put(KcMinus.getValue(), KcMinus);
        definitions.put(KcEquals.getValue(), KcEquals);
        definitions.put(KcLeftBracket.getValue(), KcLeftBracket);
        definitions.put(KcRightBracket.getValue(), KcRightBracket);
        definitions.put(KcBackslash.getValue(), KcBackslash);
        definitions.put(KcSemicolon.getValue(), KcSemicolon);
        definitions.put(KcSingleQuote.getValue(), KcSingleQuote);
        definitions.put(KcComma.getValue(), KcComma);
        definitions.put(KcPeriod.getValue(), KcPeriod);
        definitions.put(KcForwardslash.getValue(), KcForwardslash);
        definitions.put(KcSpace.getValue(), KcSpace);
        definitions.put(KcEscape.getValue(), KcEscape);
        definitions.put(KcDelete.getValue(), KcDelete);
        definitions.put(KcBackspace.getValue(), KcBackspace);
        definitions.put(KcTab.getValue(), KcTab);
        definitions.put(KcCapsLock.getValue(), KcCapsLock);
        definitions.put(KcEnter.getValue(), KcEnter);
        definitions.put(KcUpArrow.getValue(), KcUpArrow);
        definitions.put(KcDownArrow.getValue(), KcDownArrow);
        definitions.put(KcLeftArrow.getValue(), KcLeftArrow);
        definitions.put(KcRightArrow.getValue(), KcRightArrow);
        definitions.put(KcStart.getValue(), KcStart);
        definitions.put(KcResetKey.getValue(), KcResetKey);
        definitions.put(KcStop.getValue(), KcStop);
        definitions.put(KcAtSign.getValue(), KcAtSign);
        definitions.put(KcAsterisk.getValue(), KcAsterisk);
        definitions.put(KcPound.getValue(), KcPound);
        definitions.put(KcClear.getValue(), KcClear);
        definitions.put(KcHelp.getValue(), KcHelp);
        definitions.put(KcOK.getValue(), KcOK);
        definitions.put(KcInfo.getValue(), KcInfo);
        definitions.put(KcMessage.getValue(), KcMessage);
        definitions.put(KcSignInOut.getValue(), KcSignInOut);
        definitions.put(KcPlus.getValue(), KcPlus);
    }

    private KeyCode() {
        this(null);
    }

    private KeyCode(String name) {
        this(name, name);
    }

    private KeyCode(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = SdkSupportManifest.getInstance().MajorVersion;
        typeName = "keyCode";
        typeGUN = "com.hp.ext.service.sdkSupport.version.1.type.keyCode";
    }

    public static KeyCode Parse(String name)
    {
        KeyCode instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  KeyCode(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<KeyCode> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public KeyCode deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return KeyCode.Parse(node.asText());
        }
    }
}
