/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.sdkSupport;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type returned by the collect operation of the <platformStatistics> resource.
 */
public class PlatformStatistics_Collect extends E2Type
{
    private com.hp.ext.types.base.OperationMeta opMeta;
    private java.util.List<com.hp.ext.types.base.Link> links;
    
    @JsonProperty("$opMeta")
    public com.hp.ext.types.base.OperationMeta getopMeta() {
        return opMeta;
    }

    @JsonProperty("$opMeta")
    public void setopMeta(com.hp.ext.types.base.OperationMeta opMeta) {
        this.opMeta = opMeta;
    }
    @JsonProperty("links")
    public java.util.List<com.hp.ext.types.base.Link> getLinks() {
        return links;
    }

    @JsonProperty("links")
    public void setLinks(java.util.List<com.hp.ext.types.base.Link> links) {
        this.links = links;
    }
    public PlatformStatistics_Collect()
    {
        majorVersion = SdkSupportManifest.getInstance().MajorVersion;
        typeName = "platformStatistics_collect";
        typeGUN = "com.hp.ext.service.sdkSupport.version.1.type.platformStatistics_collect";
    }
}
