/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.sdkSupport;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Provides a description of how to respond to a single report read/write requests.
 */
public class ReportDetails extends E2Type
{
    private byte[] data;
    private com.hp.ext.types.protocol.Byte reportId;
    private com.hp.ext.types.usb.HidReportType reportType;
    private Boolean writable;
    
    @JsonProperty("data")
    public byte[] getData() {
        return data;
    }

    @JsonProperty("data")
    public void setData(byte[] data) {
        this.data = data;
    }
    @JsonProperty("reportId")
    public com.hp.ext.types.protocol.Byte getReportId() {
        return reportId;
    }

    @JsonProperty("reportId")
    public void setReportId(com.hp.ext.types.protocol.Byte reportId) {
        this.reportId = reportId;
    }
    @JsonProperty("reportType")
    public com.hp.ext.types.usb.HidReportType getReportType() {
        return reportType;
    }

    @JsonProperty("reportType")
    public void setReportType(com.hp.ext.types.usb.HidReportType reportType) {
        this.reportType = reportType;
    }
    @JsonProperty("writable")
    public Boolean getWritable() {
        return writable;
    }

    @JsonProperty("writable")
    public void setWritable(Boolean writable) {
        this.writable = writable;
    }
    public ReportDetails()
    {
        majorVersion = SdkSupportManifest.getInstance().MajorVersion;
        typeName = "reportDetails";
        typeGUN = "com.hp.ext.service.sdkSupport.version.1.type.reportDetails";
    }
}
