/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.protocol;

import com.hp.ext.types.common.E2Alias;

/**
 * A 64-bit signed value.
 */
public class Signed64 extends E2Alias<Long> 
{
    public Signed64() 
    {
        this(Long.valueOf(0));
    }

    public Signed64(Long value)
    {
        super(value);
        majorVersion = ProtocolTypesManifest.getInstance().MajorVersion;
        typeName = "signed64";
        typeGUN = "com.hp.ext.types.protocolTypes.version.1.type.signed64";
    }

    public Signed64 valueOf(Long value) { return new Signed64(value); }

    @Override public String toString() { return value.toString(); }
}
