/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.protocol;

import com.hp.ext.types.common.E2Alias;

/**
 * An 8-bit signed value.
 */
public class Signed8 extends E2Alias<java.lang.Byte> 
{
    public Signed8() 
    {
        this(java.lang.Byte.valueOf((byte) 0));
    }

    public Signed8(java.lang.Byte value)
    {
        super(value);
        majorVersion = ProtocolTypesManifest.getInstance().MajorVersion;
        typeName = "signed8";
        typeGUN = "com.hp.ext.types.protocolTypes.version.1.type.signed8";
    }

    public Signed8 valueOf(java.lang.Byte value) { return new Signed8(value); }

    @Override public String toString() { return value.toString(); }
}
