/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.device;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * An enumeration of alert levels.
 */
@JsonDeserialize(using = AlertLevel.Deserializer.class)
public class AlertLevel extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * An alert with basic information.
    */
    public static AlertLevel AlInformation = new AlertLevel("alInformation");
    /**
     * An alert that represents a warning.
    */
    public static AlertLevel AlWarning = new AlertLevel("alWarning");
    /**
     * An alert that represents an error.
    */
    public static AlertLevel AlError = new AlertLevel("alError");
    /**
     * A critical alert.
    */
    public static AlertLevel AlCritical = new AlertLevel("alCritical");

    protected static Hashtable<String, AlertLevel> definitions;
    
    static {
        definitions = new Hashtable<String, AlertLevel> ();
        definitions.put(AlInformation.getValue(), AlInformation);
        definitions.put(AlWarning.getValue(), AlWarning);
        definitions.put(AlError.getValue(), AlError);
        definitions.put(AlCritical.getValue(), AlCritical);
    }

    private AlertLevel() {
        this(null);
    }

    private AlertLevel(String name) {
        this(name, name);
    }

    private AlertLevel(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = DeviceManifest.getInstance().MajorVersion;
        typeName = "alertLevel";
        typeGUN = "com.hp.ext.service.device.version.1.type.alertLevel";
    }

    public static AlertLevel Parse(String name)
    {
        AlertLevel instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  AlertLevel(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<AlertLevel> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public AlertLevel deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return AlertLevel.Parse(node.asText());
        }
    }
}
