/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.device;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * device Information as configured by the owner/administrator. Note that this data may be configured via the device's
 * EWS or other supported device management tools.
 */
public class OwnerConfiguredInformation extends E2Type
{
    private String assetNumber;
    private String companyName;
    private String contactName;
    private String deviceLocation;
    private String deviceName;
    
    @JsonProperty("assetNumber")
    public String getAssetNumber() {
        return assetNumber;
    }

    @JsonProperty("assetNumber")
    public void setAssetNumber(String assetNumber) {
        this.assetNumber = assetNumber;
    }
    @JsonProperty("companyName")
    public String getCompanyName() {
        return companyName;
    }

    @JsonProperty("companyName")
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    @JsonProperty("contactName")
    public String getContactName() {
        return contactName;
    }

    @JsonProperty("contactName")
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }
    @JsonProperty("deviceLocation")
    public String getDeviceLocation() {
        return deviceLocation;
    }

    @JsonProperty("deviceLocation")
    public void setDeviceLocation(String deviceLocation) {
        this.deviceLocation = deviceLocation;
    }
    @JsonProperty("deviceName")
    public String getDeviceName() {
        return deviceName;
    }

    @JsonProperty("deviceName")
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName;
    }
    public OwnerConfiguredInformation()
    {
        majorVersion = DeviceManifest.getInstance().MajorVersion;
        typeName = "ownerConfiguredInformation";
        typeGUN = "com.hp.ext.service.device.version.1.type.ownerConfiguredInformation";
    }
}
