/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.device;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the <scanner> resource.
 */
public class Scanner extends E2Type
{
    private com.hp.ext.types.base.OperationMeta opMeta;
    private com.hp.ext.types.common.BooleanOrUnknown adfOutputBinIsFull;
    private com.hp.ext.types.common.BooleanOrUnknown hasPaperInAdf;
    private com.hp.ext.types.common.BooleanOrUnknown hasPaperOnFlatbed;
    private Boolean isBusy;
    private Boolean isOnline;
    private java.util.List<com.hp.ext.types.base.Link> links;
    
    @JsonProperty("$opMeta")
    public com.hp.ext.types.base.OperationMeta getopMeta() {
        return opMeta;
    }

    @JsonProperty("$opMeta")
    public void setopMeta(com.hp.ext.types.base.OperationMeta opMeta) {
        this.opMeta = opMeta;
    }
    @JsonProperty("adfOutputBinIsFull")
    public com.hp.ext.types.common.BooleanOrUnknown getAdfOutputBinIsFull() {
        return adfOutputBinIsFull;
    }

    @JsonProperty("adfOutputBinIsFull")
    public void setAdfOutputBinIsFull(com.hp.ext.types.common.BooleanOrUnknown adfOutputBinIsFull) {
        this.adfOutputBinIsFull = adfOutputBinIsFull;
    }
    @JsonProperty("hasPaperInAdf")
    public com.hp.ext.types.common.BooleanOrUnknown getHasPaperInAdf() {
        return hasPaperInAdf;
    }

    @JsonProperty("hasPaperInAdf")
    public void setHasPaperInAdf(com.hp.ext.types.common.BooleanOrUnknown hasPaperInAdf) {
        this.hasPaperInAdf = hasPaperInAdf;
    }
    @JsonProperty("hasPaperOnFlatbed")
    public com.hp.ext.types.common.BooleanOrUnknown getHasPaperOnFlatbed() {
        return hasPaperOnFlatbed;
    }

    @JsonProperty("hasPaperOnFlatbed")
    public void setHasPaperOnFlatbed(com.hp.ext.types.common.BooleanOrUnknown hasPaperOnFlatbed) {
        this.hasPaperOnFlatbed = hasPaperOnFlatbed;
    }
    @JsonProperty("isBusy")
    public Boolean getIsBusy() {
        return isBusy;
    }

    @JsonProperty("isBusy")
    public void setIsBusy(Boolean isBusy) {
        this.isBusy = isBusy;
    }
    @JsonProperty("isOnline")
    public Boolean getIsOnline() {
        return isOnline;
    }

    @JsonProperty("isOnline")
    public void setIsOnline(Boolean isOnline) {
        this.isOnline = isOnline;
    }
    @JsonProperty("links")
    public java.util.List<com.hp.ext.types.base.Link> getLinks() {
        return links;
    }

    @JsonProperty("links")
    public void setLinks(java.util.List<com.hp.ext.types.base.Link> links) {
        this.links = links;
    }
    public Scanner()
    {
        majorVersion = DeviceManifest.getInstance().MajorVersion;
        typeName = "scanner";
        typeGUN = "com.hp.ext.service.device.version.1.type.scanner";
    }
}
