/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.base;

import com.hp.ext.types.common.E2Type;

/**
 * Indicates that the specified parameters exceed the capabilities of the implementation. There are currently no properties/fields associated with this value,
 * which therefore serves simply as the source of a unique type GUN that identifies the kind of error that has occurred.
 */
public class CapabilitiesExceededError extends E2Type
{
    
    public CapabilitiesExceededError()
    {
        majorVersion = BaseTypesManifest.getInstance().MajorVersion;
        typeName = "capabilitiesExceededError";
        typeGUN = "com.hp.ext.types.baseTypes.version.1.type.capabilitiesExceededError";
    }
}
