/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.base;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A description of a single error.
 */
public class ErrorDescription extends E2Type
{
    private String code;
    private com.hp.ext.types.common.TypedObject errorDetails;
    private String message;
    
    @JsonProperty("code")
    public String getCode() {
        return code;
    }

    @JsonProperty("code")
    public void setCode(String code) {
        this.code = code;
    }
    @JsonProperty("errorDetails")
    public com.hp.ext.types.common.TypedObject getErrorDetails() {
        return errorDetails;
    }

    @JsonProperty("errorDetails")
    public void setErrorDetails(com.hp.ext.types.common.TypedObject errorDetails) {
        this.errorDetails = errorDetails;
    }
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    @JsonProperty("message")
    public void setMessage(String message) {
        this.message = message;
    }
    public ErrorDescription()
    {
        majorVersion = BaseTypesManifest.getInstance().MajorVersion;
        typeName = "errorDescription";
        typeGUN = "com.hp.ext.types.baseTypes.version.1.type.errorDescription";
    }
}
