/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.base;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Operation meta information.
 */
public class OperationMeta extends E2Type
{
    private com.hp.ext.types.base.ContentFilter contentFilter;
    private java.util.List<com.hp.ext.types.common.TypedObject> warnings;
    
    @JsonProperty("contentFilter")
    public com.hp.ext.types.base.ContentFilter getContentFilter() {
        return contentFilter;
    }

    @JsonProperty("contentFilter")
    public void setContentFilter(com.hp.ext.types.base.ContentFilter contentFilter) {
        this.contentFilter = contentFilter;
    }
    @JsonProperty("warnings")
    public java.util.List<com.hp.ext.types.common.TypedObject> getWarnings() {
        return warnings;
    }

    @JsonProperty("warnings")
    public void setWarnings(java.util.List<com.hp.ext.types.common.TypedObject> warnings) {
        this.warnings = warnings;
    }
    public OperationMeta()
    {
        majorVersion = BaseTypesManifest.getInstance().MajorVersion;
        typeName = "operationMeta";
        typeGUN = "com.hp.ext.types.baseTypes.version.1.type.operationMeta";
    }
}
