/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.deviceUsage;

import com.hp.ext.types.common.IE2NamespaceManifest;
public class DeviceUsageManifest implements IE2NamespaceManifest
{
    public final String ToolVersion = "2.19.0.202505142133";
    public final String Name = "deviceUsage";
    public final String Description = "APIs to acquire device usage information and statistics";
    public final String Title = "Device Usage Service";
    public final short MajorVersion = 1;
    public final String Revision = "";
    public final String ReleaseLevel = "";
    public final String ReleaseSequence = "";
    public final String RevisionDetail = String.format("%s (%s %s)", this.Revision, this.ReleaseLevel, this.ReleaseSequence);
    public final String BaseGUN = "com.hp.ext.service.deviceUsage";
    public final String VersionedGUN = String.format("%s.%s", this.BaseGUN, this.MajorVersion);

    private static DeviceUsageManifest instance;

    private DeviceUsageManifest() { }

    public static DeviceUsageManifest getInstance()
    {
            if (null == instance)
            {
                instance = new DeviceUsageManifest();
            }
            return instance;
    }
}