/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.deviceUsage;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Provides details related to overall print usage.
 */
public class PrintUsage extends E2Type
{
    private com.hp.ext.types.usage.FixedPointImpressionCounter a4EquivalentCopyImpressions;
    private com.hp.ext.types.usage.FixedPointImpressionCounter a4EquivalentFaxInImpressions;
    private com.hp.ext.types.usage.FixedPointImpressionCounter a4EquivalentPrintImpressions;
    private com.hp.ext.types.usage.FixedPointImpressionCounter a4EquivalentPrintOtherImpressions;
    private com.hp.ext.types.usage.ImpressionCounter copyImpressions;
    private com.hp.ext.types.usage.PrintAreaUsage dimensionalUsage;
    private java.util.List<com.hp.ext.types.usage.MediaKeyedPrintAreaUsage> dimensionalUsageByMediaKey;
    private com.hp.ext.types.usage.ImpressionCounter faxInImpressions;
    private java.util.List<com.hp.ext.types.usage.MediaSizeImpressionSet> impressionsByMediaSize;
    private com.hp.ext.types.usage.ImpressionCounter printImpressions;
    private com.hp.ext.types.usage.ImpressionCounter printOtherImpressions;
    private com.hp.ext.types.usage.SheetCounter printSheets;
    private java.util.List<com.hp.ext.types.usage.MediaInputSheetSet> sheetsByMediaInput;
    private java.util.List<com.hp.ext.types.usage.MediaOutputSheetSet> sheetsByMediaOutput;
    private java.util.List<com.hp.ext.types.usage.MediaSizeSheetSet> sheetsByMediaSize;
    private java.util.List<com.hp.ext.types.usage.MediaTypeSheetSet> sheetsByMediaType;
    private java.util.List<com.hp.ext.types.usage.PrintCategoryUsage> usageByPrintCategory;
    
    @JsonProperty("a4EquivalentCopyImpressions")
    public com.hp.ext.types.usage.FixedPointImpressionCounter getA4EquivalentCopyImpressions() {
        return a4EquivalentCopyImpressions;
    }

    @JsonProperty("a4EquivalentCopyImpressions")
    public void setA4EquivalentCopyImpressions(com.hp.ext.types.usage.FixedPointImpressionCounter a4EquivalentCopyImpressions) {
        this.a4EquivalentCopyImpressions = a4EquivalentCopyImpressions;
    }
    @JsonProperty("a4EquivalentFaxInImpressions")
    public com.hp.ext.types.usage.FixedPointImpressionCounter getA4EquivalentFaxInImpressions() {
        return a4EquivalentFaxInImpressions;
    }

    @JsonProperty("a4EquivalentFaxInImpressions")
    public void setA4EquivalentFaxInImpressions(com.hp.ext.types.usage.FixedPointImpressionCounter a4EquivalentFaxInImpressions) {
        this.a4EquivalentFaxInImpressions = a4EquivalentFaxInImpressions;
    }
    @JsonProperty("a4EquivalentPrintImpressions")
    public com.hp.ext.types.usage.FixedPointImpressionCounter getA4EquivalentPrintImpressions() {
        return a4EquivalentPrintImpressions;
    }

    @JsonProperty("a4EquivalentPrintImpressions")
    public void setA4EquivalentPrintImpressions(com.hp.ext.types.usage.FixedPointImpressionCounter a4EquivalentPrintImpressions) {
        this.a4EquivalentPrintImpressions = a4EquivalentPrintImpressions;
    }
    @JsonProperty("a4EquivalentPrintOtherImpressions")
    public com.hp.ext.types.usage.FixedPointImpressionCounter getA4EquivalentPrintOtherImpressions() {
        return a4EquivalentPrintOtherImpressions;
    }

    @JsonProperty("a4EquivalentPrintOtherImpressions")
    public void setA4EquivalentPrintOtherImpressions(com.hp.ext.types.usage.FixedPointImpressionCounter a4EquivalentPrintOtherImpressions) {
        this.a4EquivalentPrintOtherImpressions = a4EquivalentPrintOtherImpressions;
    }
    @JsonProperty("copyImpressions")
    public com.hp.ext.types.usage.ImpressionCounter getCopyImpressions() {
        return copyImpressions;
    }

    @JsonProperty("copyImpressions")
    public void setCopyImpressions(com.hp.ext.types.usage.ImpressionCounter copyImpressions) {
        this.copyImpressions = copyImpressions;
    }
    @JsonProperty("dimensionalUsage")
    public com.hp.ext.types.usage.PrintAreaUsage getDimensionalUsage() {
        return dimensionalUsage;
    }

    @JsonProperty("dimensionalUsage")
    public void setDimensionalUsage(com.hp.ext.types.usage.PrintAreaUsage dimensionalUsage) {
        this.dimensionalUsage = dimensionalUsage;
    }
    @JsonProperty("dimensionalUsageByMediaKey")
    public java.util.List<com.hp.ext.types.usage.MediaKeyedPrintAreaUsage> getDimensionalUsageByMediaKey() {
        return dimensionalUsageByMediaKey;
    }

    @JsonProperty("dimensionalUsageByMediaKey")
    public void setDimensionalUsageByMediaKey(java.util.List<com.hp.ext.types.usage.MediaKeyedPrintAreaUsage> dimensionalUsageByMediaKey) {
        this.dimensionalUsageByMediaKey = dimensionalUsageByMediaKey;
    }
    @JsonProperty("faxInImpressions")
    public com.hp.ext.types.usage.ImpressionCounter getFaxInImpressions() {
        return faxInImpressions;
    }

    @JsonProperty("faxInImpressions")
    public void setFaxInImpressions(com.hp.ext.types.usage.ImpressionCounter faxInImpressions) {
        this.faxInImpressions = faxInImpressions;
    }
    @JsonProperty("impressionsByMediaSize")
    public java.util.List<com.hp.ext.types.usage.MediaSizeImpressionSet> getImpressionsByMediaSize() {
        return impressionsByMediaSize;
    }

    @JsonProperty("impressionsByMediaSize")
    public void setImpressionsByMediaSize(java.util.List<com.hp.ext.types.usage.MediaSizeImpressionSet> impressionsByMediaSize) {
        this.impressionsByMediaSize = impressionsByMediaSize;
    }
    @JsonProperty("printImpressions")
    public com.hp.ext.types.usage.ImpressionCounter getPrintImpressions() {
        return printImpressions;
    }

    @JsonProperty("printImpressions")
    public void setPrintImpressions(com.hp.ext.types.usage.ImpressionCounter printImpressions) {
        this.printImpressions = printImpressions;
    }
    @JsonProperty("printOtherImpressions")
    public com.hp.ext.types.usage.ImpressionCounter getPrintOtherImpressions() {
        return printOtherImpressions;
    }

    @JsonProperty("printOtherImpressions")
    public void setPrintOtherImpressions(com.hp.ext.types.usage.ImpressionCounter printOtherImpressions) {
        this.printOtherImpressions = printOtherImpressions;
    }
    @JsonProperty("printSheets")
    public com.hp.ext.types.usage.SheetCounter getPrintSheets() {
        return printSheets;
    }

    @JsonProperty("printSheets")
    public void setPrintSheets(com.hp.ext.types.usage.SheetCounter printSheets) {
        this.printSheets = printSheets;
    }
    @JsonProperty("sheetsByMediaInput")
    public java.util.List<com.hp.ext.types.usage.MediaInputSheetSet> getSheetsByMediaInput() {
        return sheetsByMediaInput;
    }

    @JsonProperty("sheetsByMediaInput")
    public void setSheetsByMediaInput(java.util.List<com.hp.ext.types.usage.MediaInputSheetSet> sheetsByMediaInput) {
        this.sheetsByMediaInput = sheetsByMediaInput;
    }
    @JsonProperty("sheetsByMediaOutput")
    public java.util.List<com.hp.ext.types.usage.MediaOutputSheetSet> getSheetsByMediaOutput() {
        return sheetsByMediaOutput;
    }

    @JsonProperty("sheetsByMediaOutput")
    public void setSheetsByMediaOutput(java.util.List<com.hp.ext.types.usage.MediaOutputSheetSet> sheetsByMediaOutput) {
        this.sheetsByMediaOutput = sheetsByMediaOutput;
    }
    @JsonProperty("sheetsByMediaSize")
    public java.util.List<com.hp.ext.types.usage.MediaSizeSheetSet> getSheetsByMediaSize() {
        return sheetsByMediaSize;
    }

    @JsonProperty("sheetsByMediaSize")
    public void setSheetsByMediaSize(java.util.List<com.hp.ext.types.usage.MediaSizeSheetSet> sheetsByMediaSize) {
        this.sheetsByMediaSize = sheetsByMediaSize;
    }
    @JsonProperty("sheetsByMediaType")
    public java.util.List<com.hp.ext.types.usage.MediaTypeSheetSet> getSheetsByMediaType() {
        return sheetsByMediaType;
    }

    @JsonProperty("sheetsByMediaType")
    public void setSheetsByMediaType(java.util.List<com.hp.ext.types.usage.MediaTypeSheetSet> sheetsByMediaType) {
        this.sheetsByMediaType = sheetsByMediaType;
    }
    @JsonProperty("usageByPrintCategory")
    public java.util.List<com.hp.ext.types.usage.PrintCategoryUsage> getUsageByPrintCategory() {
        return usageByPrintCategory;
    }

    @JsonProperty("usageByPrintCategory")
    public void setUsageByPrintCategory(java.util.List<com.hp.ext.types.usage.PrintCategoryUsage> usageByPrintCategory) {
        this.usageByPrintCategory = usageByPrintCategory;
    }
    public PrintUsage()
    {
        majorVersion = DeviceUsageManifest.getInstance().MajorVersion;
        typeName = "printUsage";
        typeGUN = "com.hp.ext.service.deviceUsage.version.1.type.printUsage";
    }
}
