/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.scanJob;

import com.hp.ext.types.common.E2Type;
import com.hp.ext.types.common.IE2Polymorph;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;

/**
 * The bindable value for the field. This may either be a macro pattern or an explicit value.
 */
@JsonSerialize(using = FtpProtocolOptions_Path_Binding.Serializer.class)
public class FtpProtocolOptions_Path_Binding extends E2Type implements IE2Polymorph
{
    private Object polymorphInstance;

    public Object getInstance() {
        return polymorphInstance;
    }

    public void setInstance(Object o) {
        polymorphInstance = o;
    }

    public boolean isExpression()
    { 
        return polymorphInstance instanceof com.hp.ext.service.scanJob.FtpProtocolOptions_Path_Expression;
    }

    public void setExpression(com.hp.ext.service.scanJob.FtpProtocolOptions_Path_Expression value) {
        polymorphInstance = value;
    }

    public com.hp.ext.service.scanJob.FtpProtocolOptions_Path_Expression getExpression() {
        return (com.hp.ext.service.scanJob.FtpProtocolOptions_Path_Expression)polymorphInstance;
    }
    public boolean isExplicit()
    { 
        return polymorphInstance instanceof com.hp.ext.service.scanJob.FtpProtocolOptions_Path_Value;
    }

    public void setExplicit(com.hp.ext.service.scanJob.FtpProtocolOptions_Path_Value value) {
        polymorphInstance = value;
    }

    public com.hp.ext.service.scanJob.FtpProtocolOptions_Path_Value getExplicit() {
        return (com.hp.ext.service.scanJob.FtpProtocolOptions_Path_Value)polymorphInstance;
    }

    public FtpProtocolOptions_Path_Binding()
    {
        this(null);
    }

    public FtpProtocolOptions_Path_Binding(Object obj)
    {
        polymorphInstance = obj;
        majorVersion = ScanJobManifest.getInstance().MajorVersion;
        typeName = "ftpProtocolOptions_path_binding";
        typeGUN = "com.hp.ext.service.scanJob.version.1.type.ftpProtocolOptions_path_binding";
    }

    public static class Serializer extends StdSerializer<FtpProtocolOptions_Path_Binding> {
    
        public Serializer() {
            this(null);
        }
      
        public Serializer(Class<FtpProtocolOptions_Path_Binding> t) {
            super(t);
        }
    
        @Override
        public void serialize(FtpProtocolOptions_Path_Binding value, JsonGenerator jgen, SerializerProvider provider) 
          throws IOException, JsonProcessingException {
     
            jgen.writeStartObject();
            if (value.isExpression()) {
                jgen.writeObjectField("expression", value.getExpression());
            }
            if (value.isExplicit()) {
                jgen.writeObjectField("explicit", value.getExplicit());
            }
            jgen.writeEndObject();
        }
    }
};
