/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.scanJob;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Options that control the delivery of scan job data to an HTTP/HTTPS endpoint.
 */
public class HttpOptions extends E2Type
{
    private com.hp.ext.service.scanJob.HttpDestination destination;
    
    @JsonProperty("destination")
    public com.hp.ext.service.scanJob.HttpDestination getDestination() {
        return destination;
    }

    @JsonProperty("destination")
    public void setDestination(com.hp.ext.service.scanJob.HttpDestination destination) {
        this.destination = destination;
    }
    public HttpOptions()
    {
        majorVersion = ScanJobManifest.getInstance().MajorVersion;
        typeName = "httpOptions";
        typeGUN = "com.hp.ext.service.scanJob.version.1.type.httpOptions";
    }
}
