/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.scanJob;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the <profile> resource.
 */
public class Profile extends E2Type
{
    private com.hp.ext.types.base.OperationMeta opMeta;
    private com.hp.ext.types.optionProfile.OptionProfile base;
    private com.hp.ext.types.optionProfile.OptionProfile email;
    private com.hp.ext.types.optionProfile.OptionProfile http;
    private com.hp.ext.types.optionProfile.OptionProfile jobStorage;
    private java.util.List<com.hp.ext.types.base.Link> links;
    private com.hp.ext.types.optionProfile.OptionProfile localFolder;
    private com.hp.ext.types.optionProfile.OptionProfile networkFolder;
    
    @JsonProperty("$opMeta")
    public com.hp.ext.types.base.OperationMeta getopMeta() {
        return opMeta;
    }

    @JsonProperty("$opMeta")
    public void setopMeta(com.hp.ext.types.base.OperationMeta opMeta) {
        this.opMeta = opMeta;
    }
    @JsonProperty("base")
    public com.hp.ext.types.optionProfile.OptionProfile getBase() {
        return base;
    }

    @JsonProperty("base")
    public void setBase(com.hp.ext.types.optionProfile.OptionProfile base) {
        this.base = base;
    }
    @JsonProperty("email")
    public com.hp.ext.types.optionProfile.OptionProfile getEmail() {
        return email;
    }

    @JsonProperty("email")
    public void setEmail(com.hp.ext.types.optionProfile.OptionProfile email) {
        this.email = email;
    }
    @JsonProperty("http")
    public com.hp.ext.types.optionProfile.OptionProfile getHttp() {
        return http;
    }

    @JsonProperty("http")
    public void setHttp(com.hp.ext.types.optionProfile.OptionProfile http) {
        this.http = http;
    }
    @JsonProperty("jobStorage")
    public com.hp.ext.types.optionProfile.OptionProfile getJobStorage() {
        return jobStorage;
    }

    @JsonProperty("jobStorage")
    public void setJobStorage(com.hp.ext.types.optionProfile.OptionProfile jobStorage) {
        this.jobStorage = jobStorage;
    }
    @JsonProperty("links")
    public java.util.List<com.hp.ext.types.base.Link> getLinks() {
        return links;
    }

    @JsonProperty("links")
    public void setLinks(java.util.List<com.hp.ext.types.base.Link> links) {
        this.links = links;
    }
    @JsonProperty("localFolder")
    public com.hp.ext.types.optionProfile.OptionProfile getLocalFolder() {
        return localFolder;
    }

    @JsonProperty("localFolder")
    public void setLocalFolder(com.hp.ext.types.optionProfile.OptionProfile localFolder) {
        this.localFolder = localFolder;
    }
    @JsonProperty("networkFolder")
    public com.hp.ext.types.optionProfile.OptionProfile getNetworkFolder() {
        return networkFolder;
    }

    @JsonProperty("networkFolder")
    public void setNetworkFolder(com.hp.ext.types.optionProfile.OptionProfile networkFolder) {
        this.networkFolder = networkFolder;
    }
    public Profile()
    {
        majorVersion = ScanJobManifest.getInstance().MajorVersion;
        typeName = "profile";
        typeGUN = "com.hp.ext.service.scanJob.version.1.type.profile";
    }
}
