/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.scanJob;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * This variant holds a macro value for the bindable parameter.
 */
public class ScanJobCreateContent_SolutionContext_Expression extends E2Type
{
    private com.hp.ext.types.common.SolutionContext expressedValue;
    private String expressionPattern;
    
    @JsonProperty("expressedValue")
    public com.hp.ext.types.common.SolutionContext getExpressedValue() {
        return expressedValue;
    }

    @JsonProperty("expressedValue")
    public void setExpressedValue(com.hp.ext.types.common.SolutionContext expressedValue) {
        this.expressedValue = expressedValue;
    }
    @JsonProperty("expressionPattern")
    public String getExpressionPattern() {
        return expressionPattern;
    }

    @JsonProperty("expressionPattern")
    public void setExpressionPattern(String expressionPattern) {
        this.expressionPattern = expressionPattern;
    }
    public ScanJobCreateContent_SolutionContext_Expression()
    {
        majorVersion = ScanJobManifest.getInstance().MajorVersion;
        typeName = "scanJobCreateContent_solutionContext_expression";
        typeGUN = "com.hp.ext.service.scanJob.version.1.type.scanJobCreateContent_solutionContext_expression";
    }
}
