/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.scanJob;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The ticket for a scan request.
 */
public class ScanTicket extends E2Type
{
    private com.hp.ext.service.scanJob.DestinationOptions destinationOptions;
    private com.hp.ext.service.scanJob.ScanMetadataOptions metadataOptions;
    private com.hp.ext.service.scanJob.ScanRetryOptions retryOptions;
    private com.hp.ext.service.scanJob.ScanOptions scanOptions;
    
    @JsonProperty("destinationOptions")
    public com.hp.ext.service.scanJob.DestinationOptions getDestinationOptions() {
        return destinationOptions;
    }

    @JsonProperty("destinationOptions")
    public void setDestinationOptions(com.hp.ext.service.scanJob.DestinationOptions destinationOptions) {
        this.destinationOptions = destinationOptions;
    }
    @JsonProperty("metadataOptions")
    public com.hp.ext.service.scanJob.ScanMetadataOptions getMetadataOptions() {
        return metadataOptions;
    }

    @JsonProperty("metadataOptions")
    public void setMetadataOptions(com.hp.ext.service.scanJob.ScanMetadataOptions metadataOptions) {
        this.metadataOptions = metadataOptions;
    }
    @JsonProperty("retryOptions")
    public com.hp.ext.service.scanJob.ScanRetryOptions getRetryOptions() {
        return retryOptions;
    }

    @JsonProperty("retryOptions")
    public void setRetryOptions(com.hp.ext.service.scanJob.ScanRetryOptions retryOptions) {
        this.retryOptions = retryOptions;
    }
    @JsonProperty("scanOptions")
    public com.hp.ext.service.scanJob.ScanOptions getScanOptions() {
        return scanOptions;
    }

    @JsonProperty("scanOptions")
    public void setScanOptions(com.hp.ext.service.scanJob.ScanOptions scanOptions) {
        this.scanOptions = scanOptions;
    }
    public ScanTicket()
    {
        majorVersion = ScanJobManifest.getInstance().MajorVersion;
        typeName = "scanTicket";
        typeGUN = "com.hp.ext.service.scanJob.version.1.type.scanTicket";
    }
}
