/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.scanJob;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * This variant holds an explicit value for the bindable parameter.
 */
public class ScanMetadataOptions_FileContentType_Value extends E2Type
{
    private com.hp.ext.types.base.InternetMediaType explicitValue;
    
    @JsonProperty("explicitValue")
    public com.hp.ext.types.base.InternetMediaType getExplicitValue() {
        return explicitValue;
    }

    @JsonProperty("explicitValue")
    public void setExplicitValue(com.hp.ext.types.base.InternetMediaType explicitValue) {
        this.explicitValue = explicitValue;
    }
    public ScanMetadataOptions_FileContentType_Value()
    {
        majorVersion = ScanJobManifest.getInstance().MajorVersion;
        typeName = "scanMetadataOptions_fileContentType_value";
        typeGUN = "com.hp.ext.service.scanJob.version.1.type.scanMetadataOptions_fileContentType_value";
    }
}
