/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.scanJob;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * An object used to define options for an SMTP interaction.
 */
public class SmtpServerOptions extends E2Type
{
    private com.hp.ext.service.scanJob.SmtpServerCredential credential;
    private com.hp.ext.types.security.CredentialSourceType credentialSource;
    private com.hp.ext.service.scanJob.SmtpServerOptions_MaxAttachmentSize_Binding maxAttachmentSize;
    private com.hp.ext.service.scanJob.SmtpServerOptions_ServerAuthenticationRequired_Binding serverAuthenticationRequired;
    private com.hp.ext.service.scanJob.SmtpServerOptions_ServerName_Binding serverName;
    private com.hp.ext.service.scanJob.SmtpServerOptions_ServerPort_Binding serverPort;
    private com.hp.ext.service.scanJob.SmtpServerOptions_ServerValidationRequired_Binding serverValidationRequired;
    private com.hp.ext.service.scanJob.SmtpServerOptions_UseTls_Binding useTls;
    
    @JsonProperty("credential")
    public com.hp.ext.service.scanJob.SmtpServerCredential getCredential() {
        return credential;
    }

    @JsonProperty("credential")
    public void setCredential(com.hp.ext.service.scanJob.SmtpServerCredential credential) {
        this.credential = credential;
    }
    @JsonProperty("credentialSource")
    public com.hp.ext.types.security.CredentialSourceType getCredentialSource() {
        return credentialSource;
    }

    @JsonProperty("credentialSource")
    public void setCredentialSource(com.hp.ext.types.security.CredentialSourceType credentialSource) {
        this.credentialSource = credentialSource;
    }
    @JsonProperty("maxAttachmentSize")
    public com.hp.ext.service.scanJob.SmtpServerOptions_MaxAttachmentSize_Binding getMaxAttachmentSize() {
        return maxAttachmentSize;
    }

    @JsonProperty("maxAttachmentSize")
    public void setMaxAttachmentSize(com.hp.ext.service.scanJob.SmtpServerOptions_MaxAttachmentSize_Binding maxAttachmentSize) {
        this.maxAttachmentSize = maxAttachmentSize;
    }
    @JsonProperty("serverAuthenticationRequired")
    public com.hp.ext.service.scanJob.SmtpServerOptions_ServerAuthenticationRequired_Binding getServerAuthenticationRequired() {
        return serverAuthenticationRequired;
    }

    @JsonProperty("serverAuthenticationRequired")
    public void setServerAuthenticationRequired(com.hp.ext.service.scanJob.SmtpServerOptions_ServerAuthenticationRequired_Binding serverAuthenticationRequired) {
        this.serverAuthenticationRequired = serverAuthenticationRequired;
    }
    @JsonProperty("serverName")
    public com.hp.ext.service.scanJob.SmtpServerOptions_ServerName_Binding getServerName() {
        return serverName;
    }

    @JsonProperty("serverName")
    public void setServerName(com.hp.ext.service.scanJob.SmtpServerOptions_ServerName_Binding serverName) {
        this.serverName = serverName;
    }
    @JsonProperty("serverPort")
    public com.hp.ext.service.scanJob.SmtpServerOptions_ServerPort_Binding getServerPort() {
        return serverPort;
    }

    @JsonProperty("serverPort")
    public void setServerPort(com.hp.ext.service.scanJob.SmtpServerOptions_ServerPort_Binding serverPort) {
        this.serverPort = serverPort;
    }
    @JsonProperty("serverValidationRequired")
    public com.hp.ext.service.scanJob.SmtpServerOptions_ServerValidationRequired_Binding getServerValidationRequired() {
        return serverValidationRequired;
    }

    @JsonProperty("serverValidationRequired")
    public void setServerValidationRequired(com.hp.ext.service.scanJob.SmtpServerOptions_ServerValidationRequired_Binding serverValidationRequired) {
        this.serverValidationRequired = serverValidationRequired;
    }
    @JsonProperty("useTls")
    public com.hp.ext.service.scanJob.SmtpServerOptions_UseTls_Binding getUseTls() {
        return useTls;
    }

    @JsonProperty("useTls")
    public void setUseTls(com.hp.ext.service.scanJob.SmtpServerOptions_UseTls_Binding useTls) {
        this.useTls = useTls;
    }
    public SmtpServerOptions()
    {
        majorVersion = ScanJobManifest.getInstance().MajorVersion;
        typeName = "smtpServerOptions";
        typeGUN = "com.hp.ext.service.scanJob.version.1.type.smtpServerOptions";
    }
}
