/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.scanJob;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * An enumeration of supported transmission-modes available for HTTP jobs.
 */
@JsonDeserialize(using = TransmissionMode.Deserializer.class)
public class TransmissionMode extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * The device will deliver all of the scan job data in a single HTTP request.
    */
    public static TransmissionMode TmJob = new TransmissionMode("tmJob");
    /**
     * The device will deliver the scan job data in 1-or-more HTTP requests as the scan files as they become available.
    */
    public static TransmissionMode TmImage = new TransmissionMode("tmImage");

    protected static Hashtable<String, TransmissionMode> definitions;
    
    static {
        definitions = new Hashtable<String, TransmissionMode> ();
        definitions.put(TmJob.getValue(), TmJob);
        definitions.put(TmImage.getValue(), TmImage);
    }

    private TransmissionMode() {
        this(null);
    }

    private TransmissionMode(String name) {
        this(name, name);
    }

    private TransmissionMode(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = ScanJobManifest.getInstance().MajorVersion;
        typeName = "transmissionMode";
        typeGUN = "com.hp.ext.service.scanJob.version.1.type.transmissionMode";
    }

    public static TransmissionMode Parse(String name)
    {
        TransmissionMode instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  TransmissionMode(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<TransmissionMode> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public TransmissionMode deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return TransmissionMode.Parse(node.asText());
        }
    }
}
