/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.actions;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * This action is used to initiate a login session. Refer to the initiateLogin operation implemented by 
 * the authentication access point resources in the Authentication Service for additional details.
 */
public class InitiateLoginAction extends E2Type
{
    private com.hp.ext.types.common.AccessToken accessToken;
    private java.util.UUID agentAccessPointId;
    
    @JsonProperty("accessToken")
    public com.hp.ext.types.common.AccessToken getAccessToken() {
        return accessToken;
    }

    @JsonProperty("accessToken")
    public void setAccessToken(com.hp.ext.types.common.AccessToken accessToken) {
        this.accessToken = accessToken;
    }
    @JsonProperty("agentAccessPointId")
    public java.util.UUID getAgentAccessPointId() {
        return agentAccessPointId;
    }

    @JsonProperty("agentAccessPointId")
    public void setAgentAccessPointId(java.util.UUID agentAccessPointId) {
        this.agentAccessPointId = agentAccessPointId;
    }
    public InitiateLoginAction()
    {
        majorVersion = ActionTypesManifest.getInstance().MajorVersion;
        typeName = "initiateLoginAction";
        typeGUN = "com.hp.ext.types.actions.version.1.type.initiateLoginAction";
    }
}
