/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.imaging;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Enumeration of auto color detection modes
 */
@JsonDeserialize(using = AutoColorDetectMode.Deserializer.class)
public class AutoColorDetectMode extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * Basic auto color detection mode
    */
    public static AutoColorDetectMode AcdmDetectOnly = new AutoColorDetectMode("acdmDetectOnly");
    /**
     * Auto detect with non-color treated as 1-bit monochrome
    */
    public static AutoColorDetectMode AcdmTreatNonColorAsMonochrome = new AutoColorDetectMode("acdmTreatNonColorAsMonochrome");
    /**
     * Auto detect with non-color treated as 8-bit gray
    */
    public static AutoColorDetectMode AcdmTreatNonColorAsGrayscale = new AutoColorDetectMode("acdmTreatNonColorAsGrayscale");

    protected static Hashtable<String, AutoColorDetectMode> definitions;
    
    static {
        definitions = new Hashtable<String, AutoColorDetectMode> ();
        definitions.put(AcdmDetectOnly.getValue(), AcdmDetectOnly);
        definitions.put(AcdmTreatNonColorAsMonochrome.getValue(), AcdmTreatNonColorAsMonochrome);
        definitions.put(AcdmTreatNonColorAsGrayscale.getValue(), AcdmTreatNonColorAsGrayscale);
    }

    private AutoColorDetectMode() {
        this(null);
    }

    private AutoColorDetectMode(String name) {
        this(name, name);
    }

    private AutoColorDetectMode(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = ImagingTypesManifest.getInstance().MajorVersion;
        typeName = "autoColorDetectMode";
        typeGUN = "com.hp.ext.types.imaging.version.1.type.autoColorDetectMode";
    }

    public static AutoColorDetectMode Parse(String name)
    {
        AutoColorDetectMode instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  AutoColorDetectMode(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<AutoColorDetectMode> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public AutoColorDetectMode deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return AutoColorDetectMode.Parse(node.asText());
        }
    }
}
