/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.imaging;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Enumeration of binary rendering types.
 */
@JsonDeserialize(using = BinaryRenderingType.Deserializer.class)
public class BinaryRenderingType extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * Halftone
    */
    public static BinaryRenderingType BrHalftone = new BinaryRenderingType("brHalftone");
    /**
     * Threshold
    */
    public static BinaryRenderingType BrThreshold = new BinaryRenderingType("brThreshold");
    /**
     * Error Diffusion
    */
    public static BinaryRenderingType BrErrorDiffusion = new BinaryRenderingType("brErrorDiffusion");

    protected static Hashtable<String, BinaryRenderingType> definitions;
    
    static {
        definitions = new Hashtable<String, BinaryRenderingType> ();
        definitions.put(BrHalftone.getValue(), BrHalftone);
        definitions.put(BrThreshold.getValue(), BrThreshold);
        definitions.put(BrErrorDiffusion.getValue(), BrErrorDiffusion);
    }

    private BinaryRenderingType() {
        this(null);
    }

    private BinaryRenderingType(String name) {
        this(name, name);
    }

    private BinaryRenderingType(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = ImagingTypesManifest.getInstance().MajorVersion;
        typeName = "binaryRenderingType";
        typeGUN = "com.hp.ext.types.imaging.version.1.type.binaryRenderingType";
    }

    public static BinaryRenderingType Parse(String name)
    {
        BinaryRenderingType instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  BinaryRenderingType(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<BinaryRenderingType> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public BinaryRenderingType deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return BinaryRenderingType.Parse(node.asText());
        }
    }
}
