/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.imaging;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Enumeration of CCD-Channels.
 */
@JsonDeserialize(using = CcdChannelType.Deserializer.class)
public class CcdChannelType extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * NTSC
    */
    public static CcdChannelType CctNtsc = new CcdChannelType("cctNtsc");
    /**
     * Gray CCD
    */
    public static CcdChannelType CctGray = new CcdChannelType("cctGray");
    /**
     * Gray CCD (Emulated)
    */
    public static CcdChannelType CctGrayEmulated = new CcdChannelType("cctGrayEmulated");
    /**
     * Red
    */
    public static CcdChannelType CctRed = new CcdChannelType("cctRed");
    /**
     * Green
    */
    public static CcdChannelType CctGreen = new CcdChannelType("cctGreen");
    /**
     * Blue
    */
    public static CcdChannelType CctBlue = new CcdChannelType("cctBlue");

    protected static Hashtable<String, CcdChannelType> definitions;
    
    static {
        definitions = new Hashtable<String, CcdChannelType> ();
        definitions.put(CctNtsc.getValue(), CctNtsc);
        definitions.put(CctGray.getValue(), CctGray);
        definitions.put(CctGrayEmulated.getValue(), CctGrayEmulated);
        definitions.put(CctRed.getValue(), CctRed);
        definitions.put(CctGreen.getValue(), CctGreen);
        definitions.put(CctBlue.getValue(), CctBlue);
    }

    private CcdChannelType() {
        this(null);
    }

    private CcdChannelType(String name) {
        this(name, name);
    }

    private CcdChannelType(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = ImagingTypesManifest.getInstance().MajorVersion;
        typeName = "ccdChannelType";
        typeGUN = "com.hp.ext.types.imaging.version.1.type.ccdChannelType";
    }

    public static CcdChannelType Parse(String name)
    {
        CcdChannelType instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  CcdChannelType(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<CcdChannelType> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public CcdChannelType deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return CcdChannelType.Parse(node.asText());
        }
    }
}
