/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.imaging;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Enumeration of the output document binding format.
 */
@JsonDeserialize(using = DuplexBindingFormat.Deserializer.class)
public class DuplexBindingFormat extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * One-sided
    */
    public static DuplexBindingFormat DbfOneSided = new DuplexBindingFormat("dbfOneSided");
    /**
     * Two-sided long edge
    */
    public static DuplexBindingFormat DbfDuplexLongEdge = new DuplexBindingFormat("dbfDuplexLongEdge");
    /**
     * Two-sided short edge
    */
    public static DuplexBindingFormat DbfDuplexShortEdge = new DuplexBindingFormat("dbfDuplexShortEdge");

    protected static Hashtable<String, DuplexBindingFormat> definitions;
    
    static {
        definitions = new Hashtable<String, DuplexBindingFormat> ();
        definitions.put(DbfOneSided.getValue(), DbfOneSided);
        definitions.put(DbfDuplexLongEdge.getValue(), DbfDuplexLongEdge);
        definitions.put(DbfDuplexShortEdge.getValue(), DbfDuplexShortEdge);
    }

    private DuplexBindingFormat() {
        this(null);
    }

    private DuplexBindingFormat(String name) {
        this(name, name);
    }

    private DuplexBindingFormat(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = ImagingTypesManifest.getInstance().MajorVersion;
        typeName = "duplexBindingFormat";
        typeGUN = "com.hp.ext.types.imaging.version.1.type.duplexBindingFormat";
    }

    public static DuplexBindingFormat Parse(String name)
    {
        DuplexBindingFormat instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  DuplexBindingFormat(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<DuplexBindingFormat> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public DuplexBindingFormat deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return DuplexBindingFormat.Parse(node.asText());
        }
    }
}
