/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.imaging;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Defines common input/output scaling modes.
 */
@JsonDeserialize(using = ScaleSelectionType.Deserializer.class)
public class ScaleSelectionType extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * No scaling
    */
    public static ScaleSelectionType SstNone = new ScaleSelectionType("sstNone");
    /**
     * Custom scaling
    */
    public static ScaleSelectionType SstCustom = new ScaleSelectionType("sstCustom");
    /**
     * Fit to page scaling
    */
    public static ScaleSelectionType SstFitToPage = new ScaleSelectionType("sstFitToPage");
    /**
     * Full page scaling
    */
    public static ScaleSelectionType SstFullPage = new ScaleSelectionType("sstFullPage");
    /**
     * Commonly used legal-to-letter scaling
    */
    public static ScaleSelectionType SstLegalToLetter = new ScaleSelectionType("sstLegalToLetter");
    /**
     * Commonly used A4-to-letter scaling
    */
    public static ScaleSelectionType SstA4ToLetter = new ScaleSelectionType("sstA4ToLetter");
    /**
     * Commonly used letter-to-A4 scaling
    */
    public static ScaleSelectionType SstLetterToA4 = new ScaleSelectionType("sstLetterToA4");
    /**
     * Standard size scaling
    */
    public static ScaleSelectionType SstStandardSize = new ScaleSelectionType("sstStandardSize");
    /**
     * Scale to selected output size
    */
    public static ScaleSelectionType SstScaleToOutput = new ScaleSelectionType("sstScaleToOutput");

    protected static Hashtable<String, ScaleSelectionType> definitions;
    
    static {
        definitions = new Hashtable<String, ScaleSelectionType> ();
        definitions.put(SstNone.getValue(), SstNone);
        definitions.put(SstCustom.getValue(), SstCustom);
        definitions.put(SstFitToPage.getValue(), SstFitToPage);
        definitions.put(SstFullPage.getValue(), SstFullPage);
        definitions.put(SstLegalToLetter.getValue(), SstLegalToLetter);
        definitions.put(SstA4ToLetter.getValue(), SstA4ToLetter);
        definitions.put(SstLetterToA4.getValue(), SstLetterToA4);
        definitions.put(SstStandardSize.getValue(), SstStandardSize);
        definitions.put(SstScaleToOutput.getValue(), SstScaleToOutput);
    }

    private ScaleSelectionType() {
        this(null);
    }

    private ScaleSelectionType(String name) {
        this(name, name);
    }

    private ScaleSelectionType(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = ImagingTypesManifest.getInstance().MajorVersion;
        typeName = "scaleSelectionType";
        typeGUN = "com.hp.ext.types.imaging.version.1.type.scaleSelectionType";
    }

    public static ScaleSelectionType Parse(String name)
    {
        ScaleSelectionType instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  ScaleSelectionType(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<ScaleSelectionType> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public ScaleSelectionType deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return ScaleSelectionType.Parse(node.asText());
        }
    }
}
