/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.imaging;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Enumeration of sheet collation styles.
 */
@JsonDeserialize(using = SheetCollationType.Deserializer.class)
public class SheetCollationType extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * Collated
    */
    public static SheetCollationType SctCollated = new SheetCollationType("sctCollated");
    /**
     * Un-collated
    */
    public static SheetCollationType SctUncollated = new SheetCollationType("sctUncollated");

    protected static Hashtable<String, SheetCollationType> definitions;
    
    static {
        definitions = new Hashtable<String, SheetCollationType> ();
        definitions.put(SctCollated.getValue(), SctCollated);
        definitions.put(SctUncollated.getValue(), SctUncollated);
    }

    private SheetCollationType() {
        this(null);
    }

    private SheetCollationType(String name) {
        this(name, name);
    }

    private SheetCollationType(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = ImagingTypesManifest.getInstance().MajorVersion;
        typeName = "sheetCollationType";
        typeGUN = "com.hp.ext.types.imaging.version.1.type.sheetCollationType";
    }

    public static SheetCollationType Parse(String name)
    {
        SheetCollationType instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  SheetCollationType(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<SheetCollationType> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public SheetCollationType deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return SheetCollationType.Parse(node.asText());
        }
    }
}
