/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.imaging;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * The watermark text type.
 */
@JsonDeserialize(using = WatermarkTextType.Deserializer.class)
public class WatermarkTextType extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * None
    */
    public static WatermarkTextType WttNone = new WatermarkTextType("wttNone");
    /**
     * Draft
    */
    public static WatermarkTextType WttDraft = new WatermarkTextType("wttDraft");
    /**
     * Confidential
    */
    public static WatermarkTextType WttConfidential = new WatermarkTextType("wttConfidential");
    /**
     * Secret
    */
    public static WatermarkTextType WttSecret = new WatermarkTextType("wttSecret");
    /**
     * Top Secret
    */
    public static WatermarkTextType WttTopSecret = new WatermarkTextType("wttTopSecret");
    /**
     * Urgent
    */
    public static WatermarkTextType WttUrgent = new WatermarkTextType("wttUrgent");
    /**
     * User Defined 1
    */
    public static WatermarkTextType WttUserDefined1 = new WatermarkTextType("wttUserDefined1");
    /**
     * Admin Defined 1
    */
    public static WatermarkTextType WttAdminDefined1 = new WatermarkTextType("wttAdminDefined1");
    /**
     * Admin Defined 2
    */
    public static WatermarkTextType WttAdminDefined2 = new WatermarkTextType("wttAdminDefined2");
    /**
     * Admin Defined 3
    */
    public static WatermarkTextType WttAdminDefined3 = new WatermarkTextType("wttAdminDefined3");
    /**
     * Admin Defined 4
    */
    public static WatermarkTextType WttAdminDefined4 = new WatermarkTextType("wttAdminDefined4");
    /**
     * Admin Defined 5
    */
    public static WatermarkTextType WttAdminDefined5 = new WatermarkTextType("wttAdminDefined5");
    /**
     * Admin Defined 6
    */
    public static WatermarkTextType WttAdminDefined6 = new WatermarkTextType("wttAdminDefined6");
    /**
     * Admin Defined 7
    */
    public static WatermarkTextType WttAdminDefined7 = new WatermarkTextType("wttAdminDefined7");
    /**
     * Admin Defined 8
    */
    public static WatermarkTextType WttAdminDefined8 = new WatermarkTextType("wttAdminDefined8");

    protected static Hashtable<String, WatermarkTextType> definitions;
    
    static {
        definitions = new Hashtable<String, WatermarkTextType> ();
        definitions.put(WttNone.getValue(), WttNone);
        definitions.put(WttDraft.getValue(), WttDraft);
        definitions.put(WttConfidential.getValue(), WttConfidential);
        definitions.put(WttSecret.getValue(), WttSecret);
        definitions.put(WttTopSecret.getValue(), WttTopSecret);
        definitions.put(WttUrgent.getValue(), WttUrgent);
        definitions.put(WttUserDefined1.getValue(), WttUserDefined1);
        definitions.put(WttAdminDefined1.getValue(), WttAdminDefined1);
        definitions.put(WttAdminDefined2.getValue(), WttAdminDefined2);
        definitions.put(WttAdminDefined3.getValue(), WttAdminDefined3);
        definitions.put(WttAdminDefined4.getValue(), WttAdminDefined4);
        definitions.put(WttAdminDefined5.getValue(), WttAdminDefined5);
        definitions.put(WttAdminDefined6.getValue(), WttAdminDefined6);
        definitions.put(WttAdminDefined7.getValue(), WttAdminDefined7);
        definitions.put(WttAdminDefined8.getValue(), WttAdminDefined8);
    }

    private WatermarkTextType() {
        this(null);
    }

    private WatermarkTextType(String name) {
        this(name, name);
    }

    private WatermarkTextType(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = ImagingTypesManifest.getInstance().MajorVersion;
        typeName = "watermarkTextType";
        typeGUN = "com.hp.ext.types.imaging.version.1.type.watermarkTextType";
    }

    public static WatermarkTextType Parse(String name)
    {
        WatermarkTextType instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  WatermarkTextType(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<WatermarkTextType> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public WatermarkTextType deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return WatermarkTextType.Parse(node.asText());
        }
    }
}
