/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.imaging;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Represents a watermark to be applied to an image.
 */
public class Watermark extends E2Type
{
    private Long darkness;
    private Boolean firstPageOnly;
    private Boolean rotate45;
    private com.hp.ext.types.imaging.WatermarkBackgroundColorType secureBackgroundColor;
    private com.hp.ext.types.imaging.WatermarkBackgroundPatternType secureBackgroundPattern;
    private com.hp.ext.types.imaging.WatermarkType style;
    private com.hp.ext.types.imaging.StampWatermarkTextColorType textColor;
    private com.hp.ext.types.imaging.StampWatermarkTextFontType textFont;
    private com.hp.ext.types.imaging.StampWatermarkTextSizeType textSize;
    private com.hp.ext.types.imaging.WatermarkTextType textType;
    private String userText;
    
    @JsonProperty("darkness")
    public Long getDarkness() {
        return darkness;
    }

    @JsonProperty("darkness")
    public void setDarkness(Long darkness) {
        this.darkness = darkness;
    }
    @JsonProperty("firstPageOnly")
    public Boolean getFirstPageOnly() {
        return firstPageOnly;
    }

    @JsonProperty("firstPageOnly")
    public void setFirstPageOnly(Boolean firstPageOnly) {
        this.firstPageOnly = firstPageOnly;
    }
    @JsonProperty("rotate45")
    public Boolean getRotate45() {
        return rotate45;
    }

    @JsonProperty("rotate45")
    public void setRotate45(Boolean rotate45) {
        this.rotate45 = rotate45;
    }
    @JsonProperty("secureBackgroundColor")
    public com.hp.ext.types.imaging.WatermarkBackgroundColorType getSecureBackgroundColor() {
        return secureBackgroundColor;
    }

    @JsonProperty("secureBackgroundColor")
    public void setSecureBackgroundColor(com.hp.ext.types.imaging.WatermarkBackgroundColorType secureBackgroundColor) {
        this.secureBackgroundColor = secureBackgroundColor;
    }
    @JsonProperty("secureBackgroundPattern")
    public com.hp.ext.types.imaging.WatermarkBackgroundPatternType getSecureBackgroundPattern() {
        return secureBackgroundPattern;
    }

    @JsonProperty("secureBackgroundPattern")
    public void setSecureBackgroundPattern(com.hp.ext.types.imaging.WatermarkBackgroundPatternType secureBackgroundPattern) {
        this.secureBackgroundPattern = secureBackgroundPattern;
    }
    @JsonProperty("style")
    public com.hp.ext.types.imaging.WatermarkType getStyle() {
        return style;
    }

    @JsonProperty("style")
    public void setStyle(com.hp.ext.types.imaging.WatermarkType style) {
        this.style = style;
    }
    @JsonProperty("textColor")
    public com.hp.ext.types.imaging.StampWatermarkTextColorType getTextColor() {
        return textColor;
    }

    @JsonProperty("textColor")
    public void setTextColor(com.hp.ext.types.imaging.StampWatermarkTextColorType textColor) {
        this.textColor = textColor;
    }
    @JsonProperty("textFont")
    public com.hp.ext.types.imaging.StampWatermarkTextFontType getTextFont() {
        return textFont;
    }

    @JsonProperty("textFont")
    public void setTextFont(com.hp.ext.types.imaging.StampWatermarkTextFontType textFont) {
        this.textFont = textFont;
    }
    @JsonProperty("textSize")
    public com.hp.ext.types.imaging.StampWatermarkTextSizeType getTextSize() {
        return textSize;
    }

    @JsonProperty("textSize")
    public void setTextSize(com.hp.ext.types.imaging.StampWatermarkTextSizeType textSize) {
        this.textSize = textSize;
    }
    @JsonProperty("textType")
    public com.hp.ext.types.imaging.WatermarkTextType getTextType() {
        return textType;
    }

    @JsonProperty("textType")
    public void setTextType(com.hp.ext.types.imaging.WatermarkTextType textType) {
        this.textType = textType;
    }
    @JsonProperty("userText")
    public String getUserText() {
        return userText;
    }

    @JsonProperty("userText")
    public void setUserText(String userText) {
        this.userText = userText;
    }
    public Watermark()
    {
        majorVersion = ImagingTypesManifest.getInstance().MajorVersion;
        typeName = "watermark";
        typeGUN = "com.hp.ext.types.imaging.version.1.type.watermark";
    }
}
