/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.usage;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * An enumeration of possible counter unit types.
 */
@JsonDeserialize(using = CounterUnit.Deserializer.class)
public class CounterUnit extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * Centimeters
    */
    public static CounterUnit CuCentimeters = new CounterUnit("cuCentimeters");
    /**
     * Cycles
    */
    public static CounterUnit CuCycles = new CounterUnit("cuCycles");
    /**
     * Dots
    */
    public static CounterUnit CuDots = new CounterUnit("cuDots");
    /**
     * Decimicrograms
    */
    public static CounterUnit CuDecimicrograms = new CounterUnit("cuDecimicrograms");
    /**
     * Hundred impressions
    */
    public static CounterUnit CuHundredImpressions = new CounterUnit("cuHundredImpressions");
    /**
     * Hundred-Thousands of pixels
    */
    public static CounterUnit CuHundredThousandsOfPixels = new CounterUnit("cuHundredThousandsOfPixels");
    /**
     * Impressions
    */
    public static CounterUnit CuImpressions = new CounterUnit("cuImpressions");
    /**
     * Microliters
    */
    public static CounterUnit CuMicroliters = new CounterUnit("cuMicroliters");
    /**
     * Microns
    */
    public static CounterUnit CuMicrons = new CounterUnit("cuMicrons");
    /**
     * Micrograms
    */
    public static CounterUnit CuMicrograms = new CounterUnit("cuMicrograms");
    /**
     * Milligrams
    */
    public static CounterUnit CuMilligrams = new CounterUnit("cuMilligrams");
    /**
     * milliliters
    */
    public static CounterUnit CuMilliliters = new CounterUnit("cuMilliliters");
    /**
     * millimeters
    */
    public static CounterUnit CuMillimeters = new CounterUnit("cuMillimeters");
    /**
     * Nanoliters
    */
    public static CounterUnit CuNanoliters = new CounterUnit("cuNanoliters");
    /**
     * Picoliters
    */
    public static CounterUnit CuPicoliters = new CounterUnit("cuPicoliters");
    /**
     * Pixels
    */
    public static CounterUnit CuPixels = new CounterUnit("cuPixels");
    /**
     * Pages
    */
    public static CounterUnit CuPages = new CounterUnit("cuPages");
    /**
     * Percent
    */
    public static CounterUnit CuPercent = new CounterUnit("cuPercent");
    /**
     * seconds
    */
    public static CounterUnit CuSeconds = new CounterUnit("cuSeconds");
    /**
     * Centimeters squared
    */
    public static CounterUnit CuSqcm = new CounterUnit("cuSqcm");
    /**
     * Thousands of dots
    */
    public static CounterUnit CuThousandsOfDots = new CounterUnit("cuThousandsOfDots");

    protected static Hashtable<String, CounterUnit> definitions;
    
    static {
        definitions = new Hashtable<String, CounterUnit> ();
        definitions.put(CuCentimeters.getValue(), CuCentimeters);
        definitions.put(CuCycles.getValue(), CuCycles);
        definitions.put(CuDots.getValue(), CuDots);
        definitions.put(CuDecimicrograms.getValue(), CuDecimicrograms);
        definitions.put(CuHundredImpressions.getValue(), CuHundredImpressions);
        definitions.put(CuHundredThousandsOfPixels.getValue(), CuHundredThousandsOfPixels);
        definitions.put(CuImpressions.getValue(), CuImpressions);
        definitions.put(CuMicroliters.getValue(), CuMicroliters);
        definitions.put(CuMicrons.getValue(), CuMicrons);
        definitions.put(CuMicrograms.getValue(), CuMicrograms);
        definitions.put(CuMilligrams.getValue(), CuMilligrams);
        definitions.put(CuMilliliters.getValue(), CuMilliliters);
        definitions.put(CuMillimeters.getValue(), CuMillimeters);
        definitions.put(CuNanoliters.getValue(), CuNanoliters);
        definitions.put(CuPicoliters.getValue(), CuPicoliters);
        definitions.put(CuPixels.getValue(), CuPixels);
        definitions.put(CuPages.getValue(), CuPages);
        definitions.put(CuPercent.getValue(), CuPercent);
        definitions.put(CuSeconds.getValue(), CuSeconds);
        definitions.put(CuSqcm.getValue(), CuSqcm);
        definitions.put(CuThousandsOfDots.getValue(), CuThousandsOfDots);
    }

    private CounterUnit() {
        this(null);
    }

    private CounterUnit(String name) {
        this(name, name);
    }

    private CounterUnit(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = UsageTypesManifest.getInstance().MajorVersion;
        typeName = "counterUnit";
        typeGUN = "com.hp.ext.types.usage.version.1.type.counterUnit";
    }

    public static CounterUnit Parse(String name)
    {
        CounterUnit instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  CounterUnit(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<CounterUnit> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public CounterUnit deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return CounterUnit.Parse(node.asText());
        }
    }
}
