/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.usage;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Defines a fixed point number. For examples, a significand of 20000 and exponent of -4 represents the number 2.
 */
public class FixedPointCounter extends E2Type
{
    private Integer exponent;
    private Integer significand;
    
    @JsonProperty("exponent")
    public Integer getExponent() {
        return exponent;
    }

    @JsonProperty("exponent")
    public void setExponent(Integer exponent) {
        this.exponent = exponent;
    }
    @JsonProperty("significand")
    public Integer getSignificand() {
        return significand;
    }

    @JsonProperty("significand")
    public void setSignificand(Integer significand) {
        this.significand = significand;
    }
    public FixedPointCounter()
    {
        majorVersion = UsageTypesManifest.getInstance().MajorVersion;
        typeName = "fixedPointCounter";
        typeGUN = "com.hp.ext.types.usage.version.1.type.fixedPointCounter";
    }
}
