/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.usage;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A counter object used to track printed sheets using a given media size.
 */
public class MediaSizeSheetSet extends E2Type
{
    private com.hp.ext.types.media.MediaSizeId mediaSize;
    private com.hp.ext.types.usage.SheetCounter sheets;
    
    @JsonProperty("mediaSize")
    public com.hp.ext.types.media.MediaSizeId getMediaSize() {
        return mediaSize;
    }

    @JsonProperty("mediaSize")
    public void setMediaSize(com.hp.ext.types.media.MediaSizeId mediaSize) {
        this.mediaSize = mediaSize;
    }
    @JsonProperty("sheets")
    public com.hp.ext.types.usage.SheetCounter getSheets() {
        return sheets;
    }

    @JsonProperty("sheets")
    public void setSheets(com.hp.ext.types.usage.SheetCounter sheets) {
        this.sheets = sheets;
    }
    public MediaSizeSheetSet()
    {
        majorVersion = UsageTypesManifest.getInstance().MajorVersion;
        typeName = "mediaSizeSheetSet";
        typeGUN = "com.hp.ext.types.usage.version.1.type.mediaSizeSheetSet";
    }
}
