/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.usage;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A counter object used to track print impressions using a given media size.
 */
public class MediaSizeImpressionSet extends E2Type
{
    private com.hp.ext.types.usage.ImpressionCounter copyImpressions;
    private com.hp.ext.types.usage.ImpressionCounter faxInImpressions;
    private com.hp.ext.types.media.MediaSizeId mediaSize;
    private com.hp.ext.types.usage.ImpressionCounter printImpressions;
    private com.hp.ext.types.usage.ImpressionCounter printOtherImpressions;
    
    @JsonProperty("copyImpressions")
    public com.hp.ext.types.usage.ImpressionCounter getCopyImpressions() {
        return copyImpressions;
    }

    @JsonProperty("copyImpressions")
    public void setCopyImpressions(com.hp.ext.types.usage.ImpressionCounter copyImpressions) {
        this.copyImpressions = copyImpressions;
    }
    @JsonProperty("faxInImpressions")
    public com.hp.ext.types.usage.ImpressionCounter getFaxInImpressions() {
        return faxInImpressions;
    }

    @JsonProperty("faxInImpressions")
    public void setFaxInImpressions(com.hp.ext.types.usage.ImpressionCounter faxInImpressions) {
        this.faxInImpressions = faxInImpressions;
    }
    @JsonProperty("mediaSize")
    public com.hp.ext.types.media.MediaSizeId getMediaSize() {
        return mediaSize;
    }

    @JsonProperty("mediaSize")
    public void setMediaSize(com.hp.ext.types.media.MediaSizeId mediaSize) {
        this.mediaSize = mediaSize;
    }
    @JsonProperty("printImpressions")
    public com.hp.ext.types.usage.ImpressionCounter getPrintImpressions() {
        return printImpressions;
    }

    @JsonProperty("printImpressions")
    public void setPrintImpressions(com.hp.ext.types.usage.ImpressionCounter printImpressions) {
        this.printImpressions = printImpressions;
    }
    @JsonProperty("printOtherImpressions")
    public com.hp.ext.types.usage.ImpressionCounter getPrintOtherImpressions() {
        return printOtherImpressions;
    }

    @JsonProperty("printOtherImpressions")
    public void setPrintOtherImpressions(com.hp.ext.types.usage.ImpressionCounter printOtherImpressions) {
        this.printOtherImpressions = printOtherImpressions;
    }
    public MediaSizeImpressionSet()
    {
        majorVersion = UsageTypesManifest.getInstance().MajorVersion;
        typeName = "mediaSizeImpressionSet";
        typeGUN = "com.hp.ext.types.usage.version.1.type.mediaSizeImpressionSet";
    }
}
