/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.usage;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Enumeration of print categories.
 */
@JsonDeserialize(using = PrintCategoryId.Deserializer.class)
public class PrintCategoryId extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * Blueprint
    */
    public static PrintCategoryId PcBlueprint = new PrintCategoryId("pcBlueprint");
    /**
     * Color General
    */
    public static PrintCategoryId PcColorGeneral = new PrintCategoryId("pcColorGeneral");
    /**
     * Color High Density Images
    */
    public static PrintCategoryId PcColorHighDensityImages = new PrintCategoryId("pcColorHighDensityImages");
    /**
     * Color Lines
    */
    public static PrintCategoryId PcColorLines = new PrintCategoryId("pcColorLines");
    /**
     * Color Low Density Images
    */
    public static PrintCategoryId PcColorLowDensityImages = new PrintCategoryId("pcColorLowDensityImages");
    /**
     * Color Special
    */
    public static PrintCategoryId PcColorSpecial = new PrintCategoryId("pcColorSpecial");
    /**
     * Media Class Blueprint
    */
    public static PrintCategoryId PcMediaClassBlueprint = new PrintCategoryId("pcMediaClassBlueprint");
    /**
     * Media Class General
    */
    public static PrintCategoryId PcMediaClassGeneral = new PrintCategoryId("pcMediaClassGeneral");
    /**
     * Media Class Rigid
    */
    public static PrintCategoryId PcMediaClassRigid = new PrintCategoryId("pcMediaClassRigid");
    /**
     * Media Class Special
    */
    public static PrintCategoryId PcMediaClassSpecial = new PrintCategoryId("pcMediaClassSpecial");
    /**
     * Mono High Density Images
    */
    public static PrintCategoryId PcMonoHighDensityImages = new PrintCategoryId("pcMonoHighDensityImages");
    /**
     * Mono Lines
    */
    public static PrintCategoryId PcMonoLines = new PrintCategoryId("pcMonoLines");
    /**
     * Mono Low Density Images
    */
    public static PrintCategoryId PcMonoLowDensityImages = new PrintCategoryId("pcMonoLowDensityImages");
    /**
     * MPS Color
    */
    public static PrintCategoryId PcMpsColor = new PrintCategoryId("pcMpsColor");
    /**
     * MPS Mono
    */
    public static PrintCategoryId PcMpsMono = new PrintCategoryId("pcMpsMono");
    /**
     * MPS Pro
    */
    public static PrintCategoryId PcMpsPro = new PrintCategoryId("pcMpsPro");
    /**
     * Rigid
    */
    public static PrintCategoryId PcRigid = new PrintCategoryId("pcRigid");
    /**
     * Special
    */
    public static PrintCategoryId PcSpecial = new PrintCategoryId("pcSpecial");
    /**
     * White General
    */
    public static PrintCategoryId PcWhiteGeneral = new PrintCategoryId("pcWhiteGeneral");
    /**
     * White Special
    */
    public static PrintCategoryId PcWhiteSpecial = new PrintCategoryId("pcWhiteSpecial");

    protected static Hashtable<String, PrintCategoryId> definitions;
    
    static {
        definitions = new Hashtable<String, PrintCategoryId> ();
        definitions.put(PcBlueprint.getValue(), PcBlueprint);
        definitions.put(PcColorGeneral.getValue(), PcColorGeneral);
        definitions.put(PcColorHighDensityImages.getValue(), PcColorHighDensityImages);
        definitions.put(PcColorLines.getValue(), PcColorLines);
        definitions.put(PcColorLowDensityImages.getValue(), PcColorLowDensityImages);
        definitions.put(PcColorSpecial.getValue(), PcColorSpecial);
        definitions.put(PcMediaClassBlueprint.getValue(), PcMediaClassBlueprint);
        definitions.put(PcMediaClassGeneral.getValue(), PcMediaClassGeneral);
        definitions.put(PcMediaClassRigid.getValue(), PcMediaClassRigid);
        definitions.put(PcMediaClassSpecial.getValue(), PcMediaClassSpecial);
        definitions.put(PcMonoHighDensityImages.getValue(), PcMonoHighDensityImages);
        definitions.put(PcMonoLines.getValue(), PcMonoLines);
        definitions.put(PcMonoLowDensityImages.getValue(), PcMonoLowDensityImages);
        definitions.put(PcMpsColor.getValue(), PcMpsColor);
        definitions.put(PcMpsMono.getValue(), PcMpsMono);
        definitions.put(PcMpsPro.getValue(), PcMpsPro);
        definitions.put(PcRigid.getValue(), PcRigid);
        definitions.put(PcSpecial.getValue(), PcSpecial);
        definitions.put(PcWhiteGeneral.getValue(), PcWhiteGeneral);
        definitions.put(PcWhiteSpecial.getValue(), PcWhiteSpecial);
    }

    private PrintCategoryId() {
        this(null);
    }

    private PrintCategoryId(String name) {
        this(name, name);
    }

    private PrintCategoryId(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = UsageTypesManifest.getInstance().MajorVersion;
        typeName = "printCategoryId";
        typeGUN = "com.hp.ext.types.usage.version.1.type.printCategoryId";
    }

    public static PrintCategoryId Parse(String name)
    {
        PrintCategoryId instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  PrintCategoryId(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<PrintCategoryId> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public PrintCategoryId deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return PrintCategoryId.Parse(node.asText());
        }
    }
}
