/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.usage;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A large (UInt64) counter object qualified by a unit property.
 */
public class UnitCounter extends E2Type
{
    private Long count;
    private com.hp.ext.types.usage.CounterUnit unit;
    
    @JsonProperty("count")
    public Long getCount() {
        return count;
    }

    @JsonProperty("count")
    public void setCount(Long count) {
        this.count = count;
    }
    @JsonProperty("unit")
    public com.hp.ext.types.usage.CounterUnit getUnit() {
        return unit;
    }

    @JsonProperty("unit")
    public void setUnit(com.hp.ext.types.usage.CounterUnit unit) {
        this.unit = unit;
    }
    public UnitCounter()
    {
        majorVersion = UsageTypesManifest.getInstance().MajorVersion;
        typeName = "unitCounter";
        typeGUN = "com.hp.ext.types.usage.version.1.type.unitCounter";
    }
}
