/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.jobStatistics;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Information related to the analog fax component used to transmit the job.
 */
public class AFaxOutInfo extends E2Type
{
    private java.util.List<com.hp.ext.service.jobStatistics.FaxCall> faxCalls;
    private com.hp.ext.service.jobStatistics.MillisecondDuration totalAnalogFaxDuration;
    
    @JsonProperty("faxCalls")
    public java.util.List<com.hp.ext.service.jobStatistics.FaxCall> getFaxCalls() {
        return faxCalls;
    }

    @JsonProperty("faxCalls")
    public void setFaxCalls(java.util.List<com.hp.ext.service.jobStatistics.FaxCall> faxCalls) {
        this.faxCalls = faxCalls;
    }
    @JsonProperty("totalAnalogFaxDuration")
    public com.hp.ext.service.jobStatistics.MillisecondDuration getTotalAnalogFaxDuration() {
        return totalAnalogFaxDuration;
    }

    @JsonProperty("totalAnalogFaxDuration")
    public void setTotalAnalogFaxDuration(com.hp.ext.service.jobStatistics.MillisecondDuration totalAnalogFaxDuration) {
        this.totalAnalogFaxDuration = totalAnalogFaxDuration;
    }
    public AFaxOutInfo()
    {
        majorVersion = JobStatisticsManifest.getInstance().MajorVersion;
        typeName = "aFaxOutInfo";
        typeGUN = "com.hp.ext.service.jobStatistics.version.1.type.aFaxOutInfo";
    }
}
