/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.jobStatistics;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Information related to the result of a digital send transmission portion of a job.
 */
public class DigitalSendInfo extends E2Type
{
    private com.hp.ext.service.jobStatistics.DeliveredFiles deliveredFiles;
    private com.hp.ext.service.jobStatistics.DigitalSendResult result;
    private Long totalDataSize;
    private com.hp.ext.service.jobStatistics.MillisecondDuration totalImagingDuration;
    private com.hp.ext.service.jobStatistics.MillisecondDuration totalTransmissionDuration;
    
    @JsonProperty("deliveredFiles")
    public com.hp.ext.service.jobStatistics.DeliveredFiles getDeliveredFiles() {
        return deliveredFiles;
    }

    @JsonProperty("deliveredFiles")
    public void setDeliveredFiles(com.hp.ext.service.jobStatistics.DeliveredFiles deliveredFiles) {
        this.deliveredFiles = deliveredFiles;
    }
    @JsonProperty("result")
    public com.hp.ext.service.jobStatistics.DigitalSendResult getResult() {
        return result;
    }

    @JsonProperty("result")
    public void setResult(com.hp.ext.service.jobStatistics.DigitalSendResult result) {
        this.result = result;
    }
    @JsonProperty("totalDataSize")
    public Long getTotalDataSize() {
        return totalDataSize;
    }

    @JsonProperty("totalDataSize")
    public void setTotalDataSize(Long totalDataSize) {
        this.totalDataSize = totalDataSize;
    }
    @JsonProperty("totalImagingDuration")
    public com.hp.ext.service.jobStatistics.MillisecondDuration getTotalImagingDuration() {
        return totalImagingDuration;
    }

    @JsonProperty("totalImagingDuration")
    public void setTotalImagingDuration(com.hp.ext.service.jobStatistics.MillisecondDuration totalImagingDuration) {
        this.totalImagingDuration = totalImagingDuration;
    }
    @JsonProperty("totalTransmissionDuration")
    public com.hp.ext.service.jobStatistics.MillisecondDuration getTotalTransmissionDuration() {
        return totalTransmissionDuration;
    }

    @JsonProperty("totalTransmissionDuration")
    public void setTotalTransmissionDuration(com.hp.ext.service.jobStatistics.MillisecondDuration totalTransmissionDuration) {
        this.totalTransmissionDuration = totalTransmissionDuration;
    }
    public DigitalSendInfo()
    {
        majorVersion = JobStatisticsManifest.getInstance().MajorVersion;
        typeName = "digitalSendInfo";
        typeGUN = "com.hp.ext.service.jobStatistics.version.1.type.digitalSendInfo";
    }
}
