/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.jobStatistics;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Enumeration of digital send results.
 */
@JsonDeserialize(using = DigitalSendResult.Deserializer.class)
public class DigitalSendResult extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * The transmission was attempted but failed for all destinations.
    */
    public static DigitalSendResult DsrFailed = new DigitalSendResult("dsrFailed");
    /**
     * The transmission was successful to some destinations but not to others.
    */
    public static DigitalSendResult DsrPartial = new DigitalSendResult("dsrPartial");
    /**
     * The transmission was successful to all destinations.
    */
    public static DigitalSendResult DsrSuccessful = new DigitalSendResult("dsrSuccessful");
    /**
     * The transmission was canceled.
    */
    public static DigitalSendResult DsrCanceled = new DigitalSendResult("dsrCanceled");

    protected static Hashtable<String, DigitalSendResult> definitions;
    
    static {
        definitions = new Hashtable<String, DigitalSendResult> ();
        definitions.put(DsrFailed.getValue(), DsrFailed);
        definitions.put(DsrPartial.getValue(), DsrPartial);
        definitions.put(DsrSuccessful.getValue(), DsrSuccessful);
        definitions.put(DsrCanceled.getValue(), DsrCanceled);
    }

    private DigitalSendResult() {
        this(null);
    }

    private DigitalSendResult(String name) {
        this(name, name);
    }

    private DigitalSendResult(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = JobStatisticsManifest.getInstance().MajorVersion;
        typeName = "digitalSendResult";
        typeGUN = "com.hp.ext.service.jobStatistics.version.1.type.digitalSendResult";
    }

    public static DigitalSendResult Parse(String name)
    {
        DigitalSendResult instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  DigitalSendResult(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<DigitalSendResult> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public DigitalSendResult deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return DigitalSendResult.Parse(node.asText());
        }
    }
}
