/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.jobStatistics;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Information related to the CIFS component used to send files to a network folder for the job.
 */
public class FolderInfo extends E2Type
{
    private java.util.List<com.hp.ext.service.jobStatistics.DigitalFaxCall> digitalFaxCalls;
    private com.hp.ext.service.jobStatistics.DigitalSendInfo digitalSendInfo;
    private com.hp.ext.types.common.FilePath uncPath;
    private com.hp.ext.types.common.FullyQualifiedUserName userName;
    
    @JsonProperty("digitalFaxCalls")
    public java.util.List<com.hp.ext.service.jobStatistics.DigitalFaxCall> getDigitalFaxCalls() {
        return digitalFaxCalls;
    }

    @JsonProperty("digitalFaxCalls")
    public void setDigitalFaxCalls(java.util.List<com.hp.ext.service.jobStatistics.DigitalFaxCall> digitalFaxCalls) {
        this.digitalFaxCalls = digitalFaxCalls;
    }
    @JsonProperty("digitalSendInfo")
    public com.hp.ext.service.jobStatistics.DigitalSendInfo getDigitalSendInfo() {
        return digitalSendInfo;
    }

    @JsonProperty("digitalSendInfo")
    public void setDigitalSendInfo(com.hp.ext.service.jobStatistics.DigitalSendInfo digitalSendInfo) {
        this.digitalSendInfo = digitalSendInfo;
    }
    @JsonProperty("uncPath")
    public com.hp.ext.types.common.FilePath getUncPath() {
        return uncPath;
    }

    @JsonProperty("uncPath")
    public void setUncPath(com.hp.ext.types.common.FilePath uncPath) {
        this.uncPath = uncPath;
    }
    @JsonProperty("userName")
    public com.hp.ext.types.common.FullyQualifiedUserName getUserName() {
        return userName;
    }

    @JsonProperty("userName")
    public void setUserName(com.hp.ext.types.common.FullyQualifiedUserName userName) {
        this.userName = userName;
    }
    public FolderInfo()
    {
        majorVersion = JobStatisticsManifest.getInstance().MajorVersion;
        typeName = "folderInfo";
        typeGUN = "com.hp.ext.service.jobStatistics.version.1.type.folderInfo";
    }
}
