/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.jobStatistics;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Information related to calls made by the IP fax component.
 */
public class IpFaxCall extends E2Type
{
    private com.hp.ext.service.jobStatistics.FaxCall faxCall;
    private com.hp.ext.service.jobStatistics.IpFaxConfiguration ipFaxConfiguration;
    
    @JsonProperty("faxCall")
    public com.hp.ext.service.jobStatistics.FaxCall getFaxCall() {
        return faxCall;
    }

    @JsonProperty("faxCall")
    public void setFaxCall(com.hp.ext.service.jobStatistics.FaxCall faxCall) {
        this.faxCall = faxCall;
    }
    @JsonProperty("ipFaxConfiguration")
    public com.hp.ext.service.jobStatistics.IpFaxConfiguration getIpFaxConfiguration() {
        return ipFaxConfiguration;
    }

    @JsonProperty("ipFaxConfiguration")
    public void setIpFaxConfiguration(com.hp.ext.service.jobStatistics.IpFaxConfiguration ipFaxConfiguration) {
        this.ipFaxConfiguration = ipFaxConfiguration;
    }
    public IpFaxCall()
    {
        majorVersion = JobStatisticsManifest.getInstance().MajorVersion;
        typeName = "ipFaxCall";
        typeGUN = "com.hp.ext.service.jobStatistics.version.1.type.ipFaxCall";
    }
}
