/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.jobStatistics;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The IP Fax configuration.
 */
public class IpFaxConfiguration extends E2Type
{
    private com.hp.ext.types.fax.SipServer sipServer;
    private com.hp.ext.types.fax.SipTransport sipTransport;
    private com.hp.ext.types.fax.T38Transport t38Transport;
    
    @JsonProperty("sipServer")
    public com.hp.ext.types.fax.SipServer getSipServer() {
        return sipServer;
    }

    @JsonProperty("sipServer")
    public void setSipServer(com.hp.ext.types.fax.SipServer sipServer) {
        this.sipServer = sipServer;
    }
    @JsonProperty("sipTransport")
    public com.hp.ext.types.fax.SipTransport getSipTransport() {
        return sipTransport;
    }

    @JsonProperty("sipTransport")
    public void setSipTransport(com.hp.ext.types.fax.SipTransport sipTransport) {
        this.sipTransport = sipTransport;
    }
    @JsonProperty("t38Transport")
    public com.hp.ext.types.fax.T38Transport getT38Transport() {
        return t38Transport;
    }

    @JsonProperty("t38Transport")
    public void setT38Transport(com.hp.ext.types.fax.T38Transport t38Transport) {
        this.t38Transport = t38Transport;
    }
    public IpFaxConfiguration()
    {
        majorVersion = JobStatisticsManifest.getInstance().MajorVersion;
        typeName = "ipFaxConfiguration";
        typeGUN = "com.hp.ext.service.jobStatistics.version.1.type.ipFaxConfiguration";
    }
}
