/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.jobStatistics;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A job filter selects a subset of jobs for purposes of providing job statistics.
 */
public class JobFilter extends E2Type
{
    private java.util.List<com.hp.ext.types.job.JobCategory> jobCategories;
    private com.hp.ext.types.base.ContentFilter notificationFilter;
    
    @JsonProperty("jobCategories")
    public java.util.List<com.hp.ext.types.job.JobCategory> getJobCategories() {
        return jobCategories;
    }

    @JsonProperty("jobCategories")
    public void setJobCategories(java.util.List<com.hp.ext.types.job.JobCategory> jobCategories) {
        this.jobCategories = jobCategories;
    }
    @JsonProperty("notificationFilter")
    public com.hp.ext.types.base.ContentFilter getNotificationFilter() {
        return notificationFilter;
    }

    @JsonProperty("notificationFilter")
    public void setNotificationFilter(com.hp.ext.types.base.ContentFilter notificationFilter) {
        this.notificationFilter = notificationFilter;
    }
    public JobFilter()
    {
        majorVersion = JobStatisticsManifest.getInstance().MajorVersion;
        typeName = "jobFilter";
        typeGUN = "com.hp.ext.service.jobStatistics.version.1.type.jobFilter";
    }
}
