/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.jobStatistics;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the <jobStatisticsAgents>/{agentId}/jobs resource.
 */
public class Jobs extends E2Type
{
    private com.hp.ext.types.base.OperationMeta opMeta;
    private Long availableJobEntries;
    private com.hp.ext.service.jobStatistics.SequenceNumber highestSequenceNumberCompleted;
    private Boolean jobSubmissionLocked;
    private com.hp.ext.service.jobStatistics.SequenceNumber lastSequenceNumberNotified;
    private com.hp.ext.service.jobStatistics.SequenceNumber lastSequenceNumberProcessed;
    private java.util.List<com.hp.ext.types.base.Link> links;
    private java.util.List<com.hp.ext.service.jobStatistics.SequenceNumber> memberIds;
    private java.util.List<com.hp.ext.service.jobStatistics.Job> members;
    private Long offset;
    private Long selectedCount;
    private Long totalCount;
    private Long totalJobEntries;
    
    @JsonProperty("$opMeta")
    public com.hp.ext.types.base.OperationMeta getopMeta() {
        return opMeta;
    }

    @JsonProperty("$opMeta")
    public void setopMeta(com.hp.ext.types.base.OperationMeta opMeta) {
        this.opMeta = opMeta;
    }
    @JsonProperty("availableJobEntries")
    public Long getAvailableJobEntries() {
        return availableJobEntries;
    }

    @JsonProperty("availableJobEntries")
    public void setAvailableJobEntries(Long availableJobEntries) {
        this.availableJobEntries = availableJobEntries;
    }
    @JsonProperty("highestSequenceNumberCompleted")
    public com.hp.ext.service.jobStatistics.SequenceNumber getHighestSequenceNumberCompleted() {
        return highestSequenceNumberCompleted;
    }

    @JsonProperty("highestSequenceNumberCompleted")
    public void setHighestSequenceNumberCompleted(com.hp.ext.service.jobStatistics.SequenceNumber highestSequenceNumberCompleted) {
        this.highestSequenceNumberCompleted = highestSequenceNumberCompleted;
    }
    @JsonProperty("jobSubmissionLocked")
    public Boolean getJobSubmissionLocked() {
        return jobSubmissionLocked;
    }

    @JsonProperty("jobSubmissionLocked")
    public void setJobSubmissionLocked(Boolean jobSubmissionLocked) {
        this.jobSubmissionLocked = jobSubmissionLocked;
    }
    @JsonProperty("lastSequenceNumberNotified")
    public com.hp.ext.service.jobStatistics.SequenceNumber getLastSequenceNumberNotified() {
        return lastSequenceNumberNotified;
    }

    @JsonProperty("lastSequenceNumberNotified")
    public void setLastSequenceNumberNotified(com.hp.ext.service.jobStatistics.SequenceNumber lastSequenceNumberNotified) {
        this.lastSequenceNumberNotified = lastSequenceNumberNotified;
    }
    @JsonProperty("lastSequenceNumberProcessed")
    public com.hp.ext.service.jobStatistics.SequenceNumber getLastSequenceNumberProcessed() {
        return lastSequenceNumberProcessed;
    }

    @JsonProperty("lastSequenceNumberProcessed")
    public void setLastSequenceNumberProcessed(com.hp.ext.service.jobStatistics.SequenceNumber lastSequenceNumberProcessed) {
        this.lastSequenceNumberProcessed = lastSequenceNumberProcessed;
    }
    @JsonProperty("links")
    public java.util.List<com.hp.ext.types.base.Link> getLinks() {
        return links;
    }

    @JsonProperty("links")
    public void setLinks(java.util.List<com.hp.ext.types.base.Link> links) {
        this.links = links;
    }
    @JsonProperty("memberIds")
    public java.util.List<com.hp.ext.service.jobStatistics.SequenceNumber> getMemberIds() {
        return memberIds;
    }

    @JsonProperty("memberIds")
    public void setMemberIds(java.util.List<com.hp.ext.service.jobStatistics.SequenceNumber> memberIds) {
        this.memberIds = memberIds;
    }
    @JsonProperty("members")
    public java.util.List<com.hp.ext.service.jobStatistics.Job> getMembers() {
        return members;
    }

    @JsonProperty("members")
    public void setMembers(java.util.List<com.hp.ext.service.jobStatistics.Job> members) {
        this.members = members;
    }
    @JsonProperty("offset")
    public Long getOffset() {
        return offset;
    }

    @JsonProperty("offset")
    public void setOffset(Long offset) {
        this.offset = offset;
    }
    @JsonProperty("selectedCount")
    public Long getSelectedCount() {
        return selectedCount;
    }

    @JsonProperty("selectedCount")
    public void setSelectedCount(Long selectedCount) {
        this.selectedCount = selectedCount;
    }
    @JsonProperty("totalCount")
    public Long getTotalCount() {
        return totalCount;
    }

    @JsonProperty("totalCount")
    public void setTotalCount(Long totalCount) {
        this.totalCount = totalCount;
    }
    @JsonProperty("totalJobEntries")
    public Long getTotalJobEntries() {
        return totalJobEntries;
    }

    @JsonProperty("totalJobEntries")
    public void setTotalJobEntries(Long totalJobEntries) {
        this.totalJobEntries = totalJobEntries;
    }
    public Jobs()
    {
        majorVersion = JobStatisticsManifest.getInstance().MajorVersion;
        typeName = "jobs";
        typeGUN = "com.hp.ext.service.jobStatistics.version.1.type.jobs";
    }
}
