/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.jobStatistics;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Information related to the scan device used for the job.
 */
public class ScanInfo extends E2Type
{
    private com.hp.ext.types.usage.FixedPointCounter a4EquivalentAdfDeciSheets;
    private com.hp.ext.types.usage.FixedPointCounter a4EquivalentDuplexDeciSheets;
    private com.hp.ext.types.usage.FixedPointCounter a4EquivalentFlatbedlDeciSheets;
    private com.hp.ext.types.usage.FixedPointCounter a4EquivalentSimplexDeciSheets;
    private com.hp.ext.types.usage.FixedPointCounter a4EquivalentTotalDeciSheets;
    private com.hp.ext.service.jobStatistics.MillisecondDuration activeScanDuration;
    private com.hp.ext.types.usage.Counter adfSheets;
    private com.hp.ext.types.usage.Counter duplexSheets;
    private com.hp.ext.types.usage.Counter flatbedSheets;
    private com.hp.ext.service.jobStatistics.ScannedSheetInfo scannedSheetInfo;
    private com.hp.ext.types.usage.Counter simplexSheets;
    private com.hp.ext.service.jobStatistics.MillisecondDuration totalScanDuration;
    private com.hp.ext.types.usage.Counter totalSheets;
    
    @JsonProperty("a4EquivalentAdfDeciSheets")
    public com.hp.ext.types.usage.FixedPointCounter getA4EquivalentAdfDeciSheets() {
        return a4EquivalentAdfDeciSheets;
    }

    @JsonProperty("a4EquivalentAdfDeciSheets")
    public void setA4EquivalentAdfDeciSheets(com.hp.ext.types.usage.FixedPointCounter a4EquivalentAdfDeciSheets) {
        this.a4EquivalentAdfDeciSheets = a4EquivalentAdfDeciSheets;
    }
    @JsonProperty("a4EquivalentDuplexDeciSheets")
    public com.hp.ext.types.usage.FixedPointCounter getA4EquivalentDuplexDeciSheets() {
        return a4EquivalentDuplexDeciSheets;
    }

    @JsonProperty("a4EquivalentDuplexDeciSheets")
    public void setA4EquivalentDuplexDeciSheets(com.hp.ext.types.usage.FixedPointCounter a4EquivalentDuplexDeciSheets) {
        this.a4EquivalentDuplexDeciSheets = a4EquivalentDuplexDeciSheets;
    }
    @JsonProperty("a4EquivalentFlatbedlDeciSheets")
    public com.hp.ext.types.usage.FixedPointCounter getA4EquivalentFlatbedlDeciSheets() {
        return a4EquivalentFlatbedlDeciSheets;
    }

    @JsonProperty("a4EquivalentFlatbedlDeciSheets")
    public void setA4EquivalentFlatbedlDeciSheets(com.hp.ext.types.usage.FixedPointCounter a4EquivalentFlatbedlDeciSheets) {
        this.a4EquivalentFlatbedlDeciSheets = a4EquivalentFlatbedlDeciSheets;
    }
    @JsonProperty("a4EquivalentSimplexDeciSheets")
    public com.hp.ext.types.usage.FixedPointCounter getA4EquivalentSimplexDeciSheets() {
        return a4EquivalentSimplexDeciSheets;
    }

    @JsonProperty("a4EquivalentSimplexDeciSheets")
    public void setA4EquivalentSimplexDeciSheets(com.hp.ext.types.usage.FixedPointCounter a4EquivalentSimplexDeciSheets) {
        this.a4EquivalentSimplexDeciSheets = a4EquivalentSimplexDeciSheets;
    }
    @JsonProperty("a4EquivalentTotalDeciSheets")
    public com.hp.ext.types.usage.FixedPointCounter getA4EquivalentTotalDeciSheets() {
        return a4EquivalentTotalDeciSheets;
    }

    @JsonProperty("a4EquivalentTotalDeciSheets")
    public void setA4EquivalentTotalDeciSheets(com.hp.ext.types.usage.FixedPointCounter a4EquivalentTotalDeciSheets) {
        this.a4EquivalentTotalDeciSheets = a4EquivalentTotalDeciSheets;
    }
    @JsonProperty("activeScanDuration")
    public com.hp.ext.service.jobStatistics.MillisecondDuration getActiveScanDuration() {
        return activeScanDuration;
    }

    @JsonProperty("activeScanDuration")
    public void setActiveScanDuration(com.hp.ext.service.jobStatistics.MillisecondDuration activeScanDuration) {
        this.activeScanDuration = activeScanDuration;
    }
    @JsonProperty("adfSheets")
    public com.hp.ext.types.usage.Counter getAdfSheets() {
        return adfSheets;
    }

    @JsonProperty("adfSheets")
    public void setAdfSheets(com.hp.ext.types.usage.Counter adfSheets) {
        this.adfSheets = adfSheets;
    }
    @JsonProperty("duplexSheets")
    public com.hp.ext.types.usage.Counter getDuplexSheets() {
        return duplexSheets;
    }

    @JsonProperty("duplexSheets")
    public void setDuplexSheets(com.hp.ext.types.usage.Counter duplexSheets) {
        this.duplexSheets = duplexSheets;
    }
    @JsonProperty("flatbedSheets")
    public com.hp.ext.types.usage.Counter getFlatbedSheets() {
        return flatbedSheets;
    }

    @JsonProperty("flatbedSheets")
    public void setFlatbedSheets(com.hp.ext.types.usage.Counter flatbedSheets) {
        this.flatbedSheets = flatbedSheets;
    }
    @JsonProperty("scannedSheetInfo")
    public com.hp.ext.service.jobStatistics.ScannedSheetInfo getScannedSheetInfo() {
        return scannedSheetInfo;
    }

    @JsonProperty("scannedSheetInfo")
    public void setScannedSheetInfo(com.hp.ext.service.jobStatistics.ScannedSheetInfo scannedSheetInfo) {
        this.scannedSheetInfo = scannedSheetInfo;
    }
    @JsonProperty("simplexSheets")
    public com.hp.ext.types.usage.Counter getSimplexSheets() {
        return simplexSheets;
    }

    @JsonProperty("simplexSheets")
    public void setSimplexSheets(com.hp.ext.types.usage.Counter simplexSheets) {
        this.simplexSheets = simplexSheets;
    }
    @JsonProperty("totalScanDuration")
    public com.hp.ext.service.jobStatistics.MillisecondDuration getTotalScanDuration() {
        return totalScanDuration;
    }

    @JsonProperty("totalScanDuration")
    public void setTotalScanDuration(com.hp.ext.service.jobStatistics.MillisecondDuration totalScanDuration) {
        this.totalScanDuration = totalScanDuration;
    }
    @JsonProperty("totalSheets")
    public com.hp.ext.types.usage.Counter getTotalSheets() {
        return totalSheets;
    }

    @JsonProperty("totalSheets")
    public void setTotalSheets(com.hp.ext.types.usage.Counter totalSheets) {
        this.totalSheets = totalSheets;
    }
    public ScanInfo()
    {
        majorVersion = JobStatisticsManifest.getInstance().MajorVersion;
        typeName = "scanInfo";
        typeGUN = "com.hp.ext.service.jobStatistics.version.1.type.scanInfo";
    }
}
