/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.jobStatistics;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Describes a non-empty range of sequence numbers.
 */
public class SequenceNumberRange extends E2Type
{
    private com.hp.ext.service.jobStatistics.SequenceNumber first;
    private com.hp.ext.service.jobStatistics.SequenceNumber last;
    
    @JsonProperty("first")
    public com.hp.ext.service.jobStatistics.SequenceNumber getFirst() {
        return first;
    }

    @JsonProperty("first")
    public void setFirst(com.hp.ext.service.jobStatistics.SequenceNumber first) {
        this.first = first;
    }
    @JsonProperty("last")
    public com.hp.ext.service.jobStatistics.SequenceNumber getLast() {
        return last;
    }

    @JsonProperty("last")
    public void setLast(com.hp.ext.service.jobStatistics.SequenceNumber last) {
        this.last = last;
    }
    public SequenceNumberRange()
    {
        majorVersion = JobStatisticsManifest.getInstance().MajorVersion;
        typeName = "sequenceNumberRange";
        typeGUN = "com.hp.ext.service.jobStatistics.version.1.type.sequenceNumberRange";
    }
}
