/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.jobStatistics;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the data pushed for each pushed resource
 */
public class StatisticsData extends E2Type
{
    private com.hp.ext.service.jobStatistics.AFaxInInfo aFaxInInfo;
    private com.hp.ext.service.jobStatistics.AFaxOutInfo aFaxOutInfo;
    private com.hp.ext.service.jobStatistics.DriverInfo driverInfo;
    private com.hp.ext.service.jobStatistics.EmailInfo emailInfo;
    private java.util.List<com.hp.ext.service.jobStatistics.FolderInfo> folderInfo;
    private java.util.List<com.hp.ext.service.jobStatistics.FtpInfo> ftpInfo;
    private java.util.List<com.hp.ext.service.jobStatistics.HttpInfo> httpInfo;
    private com.hp.ext.service.jobStatistics.IpFaxInInfo ipFaxInInfo;
    private com.hp.ext.service.jobStatistics.IpFaxOutInfo ipFaxOutInfo;
    private com.hp.ext.service.jobStatistics.JobIdentifier jobId;
    private com.hp.ext.service.jobStatistics.JobInfo jobInfo;
    private com.hp.ext.service.jobStatistics.PrintInfo printInfo;
    private com.hp.ext.service.jobStatistics.SequenceNumber resourceId;
    private com.hp.ext.service.jobStatistics.ScanInfo scanInfo;
    private com.hp.ext.service.jobStatistics.SequenceNumber sequenceNumber;
    private com.hp.ext.types.security.AuthenticatedUserInfo userInfo;
    
    @JsonProperty("aFaxInInfo")
    public com.hp.ext.service.jobStatistics.AFaxInInfo getAFaxInInfo() {
        return aFaxInInfo;
    }

    @JsonProperty("aFaxInInfo")
    public void setAFaxInInfo(com.hp.ext.service.jobStatistics.AFaxInInfo aFaxInInfo) {
        this.aFaxInInfo = aFaxInInfo;
    }
    @JsonProperty("aFaxOutInfo")
    public com.hp.ext.service.jobStatistics.AFaxOutInfo getAFaxOutInfo() {
        return aFaxOutInfo;
    }

    @JsonProperty("aFaxOutInfo")
    public void setAFaxOutInfo(com.hp.ext.service.jobStatistics.AFaxOutInfo aFaxOutInfo) {
        this.aFaxOutInfo = aFaxOutInfo;
    }
    @JsonProperty("driverInfo")
    public com.hp.ext.service.jobStatistics.DriverInfo getDriverInfo() {
        return driverInfo;
    }

    @JsonProperty("driverInfo")
    public void setDriverInfo(com.hp.ext.service.jobStatistics.DriverInfo driverInfo) {
        this.driverInfo = driverInfo;
    }
    @JsonProperty("emailInfo")
    public com.hp.ext.service.jobStatistics.EmailInfo getEmailInfo() {
        return emailInfo;
    }

    @JsonProperty("emailInfo")
    public void setEmailInfo(com.hp.ext.service.jobStatistics.EmailInfo emailInfo) {
        this.emailInfo = emailInfo;
    }
    @JsonProperty("folderInfo")
    public java.util.List<com.hp.ext.service.jobStatistics.FolderInfo> getFolderInfo() {
        return folderInfo;
    }

    @JsonProperty("folderInfo")
    public void setFolderInfo(java.util.List<com.hp.ext.service.jobStatistics.FolderInfo> folderInfo) {
        this.folderInfo = folderInfo;
    }
    @JsonProperty("ftpInfo")
    public java.util.List<com.hp.ext.service.jobStatistics.FtpInfo> getFtpInfo() {
        return ftpInfo;
    }

    @JsonProperty("ftpInfo")
    public void setFtpInfo(java.util.List<com.hp.ext.service.jobStatistics.FtpInfo> ftpInfo) {
        this.ftpInfo = ftpInfo;
    }
    @JsonProperty("httpInfo")
    public java.util.List<com.hp.ext.service.jobStatistics.HttpInfo> getHttpInfo() {
        return httpInfo;
    }

    @JsonProperty("httpInfo")
    public void setHttpInfo(java.util.List<com.hp.ext.service.jobStatistics.HttpInfo> httpInfo) {
        this.httpInfo = httpInfo;
    }
    @JsonProperty("ipFaxInInfo")
    public com.hp.ext.service.jobStatistics.IpFaxInInfo getIpFaxInInfo() {
        return ipFaxInInfo;
    }

    @JsonProperty("ipFaxInInfo")
    public void setIpFaxInInfo(com.hp.ext.service.jobStatistics.IpFaxInInfo ipFaxInInfo) {
        this.ipFaxInInfo = ipFaxInInfo;
    }
    @JsonProperty("ipFaxOutInfo")
    public com.hp.ext.service.jobStatistics.IpFaxOutInfo getIpFaxOutInfo() {
        return ipFaxOutInfo;
    }

    @JsonProperty("ipFaxOutInfo")
    public void setIpFaxOutInfo(com.hp.ext.service.jobStatistics.IpFaxOutInfo ipFaxOutInfo) {
        this.ipFaxOutInfo = ipFaxOutInfo;
    }
    @JsonProperty("jobId")
    public com.hp.ext.service.jobStatistics.JobIdentifier getJobId() {
        return jobId;
    }

    @JsonProperty("jobId")
    public void setJobId(com.hp.ext.service.jobStatistics.JobIdentifier jobId) {
        this.jobId = jobId;
    }
    @JsonProperty("jobInfo")
    public com.hp.ext.service.jobStatistics.JobInfo getJobInfo() {
        return jobInfo;
    }

    @JsonProperty("jobInfo")
    public void setJobInfo(com.hp.ext.service.jobStatistics.JobInfo jobInfo) {
        this.jobInfo = jobInfo;
    }
    @JsonProperty("printInfo")
    public com.hp.ext.service.jobStatistics.PrintInfo getPrintInfo() {
        return printInfo;
    }

    @JsonProperty("printInfo")
    public void setPrintInfo(com.hp.ext.service.jobStatistics.PrintInfo printInfo) {
        this.printInfo = printInfo;
    }
    @JsonProperty("resourceId")
    public com.hp.ext.service.jobStatistics.SequenceNumber getResourceId() {
        return resourceId;
    }

    @JsonProperty("resourceId")
    public void setResourceId(com.hp.ext.service.jobStatistics.SequenceNumber resourceId) {
        this.resourceId = resourceId;
    }
    @JsonProperty("scanInfo")
    public com.hp.ext.service.jobStatistics.ScanInfo getScanInfo() {
        return scanInfo;
    }

    @JsonProperty("scanInfo")
    public void setScanInfo(com.hp.ext.service.jobStatistics.ScanInfo scanInfo) {
        this.scanInfo = scanInfo;
    }
    @JsonProperty("sequenceNumber")
    public com.hp.ext.service.jobStatistics.SequenceNumber getSequenceNumber() {
        return sequenceNumber;
    }

    @JsonProperty("sequenceNumber")
    public void setSequenceNumber(com.hp.ext.service.jobStatistics.SequenceNumber sequenceNumber) {
        this.sequenceNumber = sequenceNumber;
    }
    @JsonProperty("userInfo")
    public com.hp.ext.types.security.AuthenticatedUserInfo getUserInfo() {
        return userInfo;
    }

    @JsonProperty("userInfo")
    public void setUserInfo(com.hp.ext.types.security.AuthenticatedUserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public StatisticsData()
    {
        majorVersion = JobStatisticsManifest.getInstance().MajorVersion;
        typeName = "statisticsData";
        typeGUN = "com.hp.ext.service.jobStatistics.version.1.type.statisticsData";
    }
}
