/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.network;

import com.hp.ext.types.common.E2Alias;

/**
 * An IP address in the form of a string. May contain an IPv4 or an IPv6 address,
 * but is never a host name.
 */
public class IpAddressString extends E2Alias<String> 
{
    public IpAddressString() 
    {
        this(null);
    }

    public IpAddressString(String value)
    {
        super(value);
        majorVersion = NetworkTypesManifest.getInstance().MajorVersion;
        typeName = "ipAddressString";
        typeGUN = "com.hp.ext.types.network.version.1.type.ipAddressString";
    }

    public IpAddressString valueOf(String value) { return new IpAddressString(value); }

    @Override public String toString() { return value.toString(); }
}
