/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.network;

import com.hp.ext.types.common.IE2NamespaceManifest;
public class NetworkTypesManifest implements IE2NamespaceManifest
{
    public final String ToolVersion = "2.19.0.202505142133";
    public final String Name = "NetworkTypes";
    public final String Description = "Common types for network-related definitions.";
    public final String Title = "Network Types";
    public final short MajorVersion = 1;
    public final String Revision = "";
    public final String ReleaseLevel = "";
    public final String ReleaseSequence = "";
    public final String RevisionDetail = String.format("%s (%s %s)", this.Revision, this.ReleaseLevel, this.ReleaseSequence);
    public final String BaseGUN = "com.hp.ext.types.network";
    public final String VersionedGUN = String.format("%s.%s", this.BaseGUN, this.MajorVersion);

    private static NetworkTypesManifest instance;

    private NetworkTypesManifest() { }

    public static NetworkTypesManifest getInstance()
    {
            if (null == instance)
            {
                instance = new NetworkTypesManifest();
            }
            return instance;
    }
}