/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.network;

import com.hp.ext.types.common.E2Alias;

/**
 * A network port number
 */
public class PortNumber extends E2Alias<Integer> 
{
    public PortNumber() 
    {
        this(0);
    }

    public PortNumber(Integer value)
    {
        super(value);
        majorVersion = NetworkTypesManifest.getInstance().MajorVersion;
        typeName = "portNumber";
        typeGUN = "com.hp.ext.types.network.version.1.type.portNumber";
    }

    public PortNumber valueOf(Integer value) { return new PortNumber(value); }

    @Override public String toString() { return value.toString(); }
}
