/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.network;

import com.hp.ext.types.common.E2Alias;

/**
 * A Universal Naming Convention (UNC) path
 */
public class UncPath extends E2Alias<String> 
{
    public UncPath() 
    {
        this(null);
    }

    public UncPath(String value)
    {
        super(value);
        majorVersion = NetworkTypesManifest.getInstance().MajorVersion;
        typeName = "uncPath";
        typeGUN = "com.hp.ext.types.network.version.1.type.uncPath";
    }

    public UncPath valueOf(String value) { return new UncPath(value); }

    @Override public String toString() { return value.toString(); }
}
