/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.optionProfile;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A condition operator used to combine two or more operators using logical AND behavior.
 */
public class AndOperator extends E2Type
{
    private java.util.List<com.hp.ext.types.optionProfile.ConditionOperator> operators;
    
    @JsonProperty("operators")
    public java.util.List<com.hp.ext.types.optionProfile.ConditionOperator> getOperators() {
        return operators;
    }

    @JsonProperty("operators")
    public void setOperators(java.util.List<com.hp.ext.types.optionProfile.ConditionOperator> operators) {
        this.operators = operators;
    }
    public AndOperator()
    {
        majorVersion = OptionProfileTypesManifest.getInstance().MajorVersion;
        typeName = "andOperator";
        typeGUN = "com.hp.ext.types.optionProfile.version.1.type.andOperator";
    }
}
