/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.optionProfile;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * An option rule that describes the forced setting of an option to a specific value.
 */
public class ForceSetRule extends E2Type
{
    private com.hp.ext.types.optionProfile.ConditionOperator condition;
    private String message;
    private String optionValue;
    
    @JsonProperty("condition")
    public com.hp.ext.types.optionProfile.ConditionOperator getCondition() {
        return condition;
    }

    @JsonProperty("condition")
    public void setCondition(com.hp.ext.types.optionProfile.ConditionOperator condition) {
        this.condition = condition;
    }
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    @JsonProperty("message")
    public void setMessage(String message) {
        this.message = message;
    }
    @JsonProperty("optionValue")
    public String getOptionValue() {
        return optionValue;
    }

    @JsonProperty("optionValue")
    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue;
    }
    public ForceSetRule()
    {
        majorVersion = OptionProfileTypesManifest.getInstance().MajorVersion;
        typeName = "forceSetRule";
        typeGUN = "com.hp.ext.types.optionProfile.version.1.type.forceSetRule";
    }
}
