/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.optionProfile;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * An operator to check that the indicated option's value is greater than the provided value.
 */
public class GreaterThanOperator extends E2Type
{
    private String optionName;
    private String optionValue;
    
    @JsonProperty("optionName")
    public String getOptionName() {
        return optionName;
    }

    @JsonProperty("optionName")
    public void setOptionName(String optionName) {
        this.optionName = optionName;
    }
    @JsonProperty("optionValue")
    public String getOptionValue() {
        return optionValue;
    }

    @JsonProperty("optionValue")
    public void setOptionValue(String optionValue) {
        this.optionValue = optionValue;
    }
    public GreaterThanOperator()
    {
        majorVersion = OptionProfileTypesManifest.getInstance().MajorVersion;
        typeName = "greaterThanOperator";
        typeGUN = "com.hp.ext.types.optionProfile.version.1.type.greaterThanOperator";
    }
}
