/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.optionProfile;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A condition operator used to negate the result of a contained inner operator.
 */
public class NotOperator extends E2Type
{
    private com.hp.ext.types.optionProfile.ConditionOperator _operator;
    
    @JsonProperty("operator")
    public com.hp.ext.types.optionProfile.ConditionOperator getOperator() {
        return _operator;
    }

    @JsonProperty("operator")
    public void setOperator(com.hp.ext.types.optionProfile.ConditionOperator _operator) {
        this._operator = _operator;
    }
    public NotOperator()
    {
        majorVersion = OptionProfileTypesManifest.getInstance().MajorVersion;
        typeName = "notOperator";
        typeGUN = "com.hp.ext.types.optionProfile.version.1.type.notOperator";
    }
}
