/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.optionProfile;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * An option rule used to provide the total possible set of values for a given option.
 */
public class PossibleValuesRule extends E2Type
{
    private com.hp.ext.types.optionProfile.ConditionOperator condition;
    private String message;
    private java.util.List<String> optionValues;
    
    @JsonProperty("condition")
    public com.hp.ext.types.optionProfile.ConditionOperator getCondition() {
        return condition;
    }

    @JsonProperty("condition")
    public void setCondition(com.hp.ext.types.optionProfile.ConditionOperator condition) {
        this.condition = condition;
    }
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    @JsonProperty("message")
    public void setMessage(String message) {
        this.message = message;
    }
    @JsonProperty("optionValues")
    public java.util.List<String> getOptionValues() {
        return optionValues;
    }

    @JsonProperty("optionValues")
    public void setOptionValues(java.util.List<String> optionValues) {
        this.optionValues = optionValues;
    }
    public PossibleValuesRule()
    {
        majorVersion = OptionProfileTypesManifest.getInstance().MajorVersion;
        typeName = "possibleValuesRule";
        typeGUN = "com.hp.ext.types.optionProfile.version.1.type.possibleValuesRule";
    }
}
