/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.agent;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Common fields for asset registrations.
 */
public class AssetRegistrationCommon extends E2Type
{
    private com.hp.ext.types.agent.AssetId assetId;
    
    @JsonProperty("assetId")
    public com.hp.ext.types.agent.AssetId getAssetId() {
        return assetId;
    }

    @JsonProperty("assetId")
    public void setAssetId(com.hp.ext.types.agent.AssetId assetId) {
        this.assetId = assetId;
    }
    public AssetRegistrationCommon()
    {
        majorVersion = AgentTypesManifest.getInstance().MajorVersion;
        typeName = "assetRegistrationCommon";
        typeGUN = "com.hp.ext.types.agentTypes.version.1.type.assetRegistrationCommon";
    }
}
