/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.fax;

import com.hp.ext.types.common.E2Alias;

/**
 * A SIP URI for Fax Over IP calls.
 */
public class SipUri extends E2Alias<String> 
{
    public SipUri() 
    {
        this(null);
    }

    public SipUri(String value)
    {
        super(value);
        majorVersion = FaxTypesManifest.getInstance().MajorVersion;
        typeName = "sipUri";
        typeGUN = "com.hp.ext.types.fax.version.1.type.sipUri";
    }

    public SipUri valueOf(String value) { return new SipUri(value); }

    @Override public String toString() { return value.toString(); }
}
