
package com.hp.ws.cdm.jobmanagement;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;


/**
 * generic job details
 * 
 */
public class JobInfo {

    @SerializedName("connectionType")
    @Expose
    private JobInfo.ConnectionType connectionType;
    /**
     * standard date and time format - according to RFC 3339. The date/time when the event was produced (according to the service).  It is of the form YYYY-MM-DD'T':HH:mm:SS.sssZ, for example '2012-04-21T08:15:13.511Z'
     * 
     */
    @SerializedName("creationTime")
    @Expose
    private Date creationTime;
    /**
     * standard date and time format - according to RFC 3339. The date/time when the event was produced (according to the service).  It is of the form YYYY-MM-DD'T':HH:mm:SS.sssZ, for example '2012-04-21T08:15:13.511Z'
     * 
     */
    @SerializedName("endTime")
    @Expose
    private Date endTime;
    /**
     * Printer firmware version when the job information is captured
     * 
     */
    @SerializedName("firmwareVersion")
    @Expose
    private String firmwareVersion;
    /**
     * category of the job
     * 
     */
    @SerializedName("jobCategory")
    @Expose
    private JobInfo.JobCategory jobCategory;
    /**
     * reasons for unsuccessful completion states
     * 
     */
    @SerializedName("jobCompletionDetail")
    @Expose
    private JobInfo.JobCompletionDetail jobCompletionDetail;
    /**
     * completion state of the job
     * 
     */
    @SerializedName("jobCompletionState")
    @Expose
    private com.hp.ws.cdm.jobmanagement.Job.JobCompletionState jobCompletionState;
    /**
     * Source/Application where the job originated
     * 
     */
    @SerializedName("jobDataSource")
    @Expose
    private JobInfo.JobDataSource jobDataSource;
    @SerializedName("jobDestinations")
    @Expose
    private List<JobDestinationTypes> jobDestinations = new ArrayList<JobDestinationTypes>();
    /**
     * name of the running job
     * 
     */
    @SerializedName("jobName")
    @Expose
    private String jobName;
    /**
     * googleCloudPrintCloud and googleCloudPrintLocal values are obsolete and no longer supported
     * 
     */
    @SerializedName("jobProtocolType")
    @Expose
    private JobInfo.JobProtocolType jobProtocolType;
    /**
     * unique job identifier, as generated by print device
     * 
     */
    @SerializedName("jobUuid")
    @Expose
    private String jobUuid;
    /**
     * The reason why a job was paused
     * 
     */
    @SerializedName("pauseReason")
    @Expose
    private com.hp.ws.cdm.jobmanagement.Job.PauseReason pauseReason;
    /**
     * standard date and time format - according to RFC 3339. The date/time when the event was produced (according to the service).  It is of the form YYYY-MM-DD'T':HH:mm:SS.sssZ, for example '2012-04-21T08:15:13.511Z'
     * 
     */
    @SerializedName("startTime")
    @Expose
    private Date startTime;
    /**
     * This number is incremented for every new job completed at the device.  This property will not be set for active jobs.
     * 
     */
    @SerializedName("jobSequenceId")
    @Expose
    private Integer jobSequenceId;
    @SerializedName("state")
    @Expose
    private com.hp.ws.cdm.jobmanagement.Job.State state;
    @SerializedName("processingSubState")
    @Expose
    private com.hp.ws.cdm.jobmanagement.Job.ProcessingSubState processingSubState;
    /**
     * The username of the person who owns this job.
     * 
     */
    @SerializedName("userName")
    @Expose
    private String userName;
    /**
     * Clients can use this property to sort active jobs in the queue.  Higher priority jobs will have a smaller sortOrder value.  This property will not be set for completed jobs.  Use the jobSequenceId instead
     * 
     */
    @SerializedName("sortOrder")
    @Expose
    private Integer sortOrder;

    public JobInfo.ConnectionType getConnectionType() {
        return connectionType;
    }

    public void setConnectionType(JobInfo.ConnectionType connectionType) {
        this.connectionType = connectionType;
    }

    /**
     * standard date and time format - according to RFC 3339. The date/time when the event was produced (according to the service).  It is of the form YYYY-MM-DD'T':HH:mm:SS.sssZ, for example '2012-04-21T08:15:13.511Z'
     * 
     */
    public Date getCreationTime() {
        return creationTime;
    }

    /**
     * standard date and time format - according to RFC 3339. The date/time when the event was produced (according to the service).  It is of the form YYYY-MM-DD'T':HH:mm:SS.sssZ, for example '2012-04-21T08:15:13.511Z'
     * 
     */
    public void setCreationTime(Date creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * standard date and time format - according to RFC 3339. The date/time when the event was produced (according to the service).  It is of the form YYYY-MM-DD'T':HH:mm:SS.sssZ, for example '2012-04-21T08:15:13.511Z'
     * 
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * standard date and time format - according to RFC 3339. The date/time when the event was produced (according to the service).  It is of the form YYYY-MM-DD'T':HH:mm:SS.sssZ, for example '2012-04-21T08:15:13.511Z'
     * 
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * Printer firmware version when the job information is captured
     * 
     */
    public String getFirmwareVersion() {
        return firmwareVersion;
    }

    /**
     * Printer firmware version when the job information is captured
     * 
     */
    public void setFirmwareVersion(String firmwareVersion) {
        this.firmwareVersion = firmwareVersion;
    }

    /**
     * category of the job
     * 
     */
    public JobInfo.JobCategory getJobCategory() {
        return jobCategory;
    }

    /**
     * category of the job
     * 
     */
    public void setJobCategory(JobInfo.JobCategory jobCategory) {
        this.jobCategory = jobCategory;
    }

    /**
     * reasons for unsuccessful completion states
     * 
     */
    public JobInfo.JobCompletionDetail getJobCompletionDetail() {
        return jobCompletionDetail;
    }

    /**
     * reasons for unsuccessful completion states
     * 
     */
    public void setJobCompletionDetail(JobInfo.JobCompletionDetail jobCompletionDetail) {
        this.jobCompletionDetail = jobCompletionDetail;
    }

    /**
     * completion state of the job
     * 
     */
    public com.hp.ws.cdm.jobmanagement.Job.JobCompletionState getJobCompletionState() {
        return jobCompletionState;
    }

    /**
     * completion state of the job
     * 
     */
    public void setJobCompletionState(com.hp.ws.cdm.jobmanagement.Job.JobCompletionState jobCompletionState) {
        this.jobCompletionState = jobCompletionState;
    }

    /**
     * Source/Application where the job originated
     * 
     */
    public JobInfo.JobDataSource getJobDataSource() {
        return jobDataSource;
    }

    /**
     * Source/Application where the job originated
     * 
     */
    public void setJobDataSource(JobInfo.JobDataSource jobDataSource) {
        this.jobDataSource = jobDataSource;
    }

    public List<JobDestinationTypes> getJobDestinations() {
        return jobDestinations;
    }

    public void setJobDestinations(List<JobDestinationTypes> jobDestinations) {
        this.jobDestinations = jobDestinations;
    }

    /**
     * name of the running job
     * 
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * name of the running job
     * 
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * googleCloudPrintCloud and googleCloudPrintLocal values are obsolete and no longer supported
     * 
     */
    public JobInfo.JobProtocolType getJobProtocolType() {
        return jobProtocolType;
    }

    /**
     * googleCloudPrintCloud and googleCloudPrintLocal values are obsolete and no longer supported
     * 
     */
    public void setJobProtocolType(JobInfo.JobProtocolType jobProtocolType) {
        this.jobProtocolType = jobProtocolType;
    }

    /**
     * unique job identifier, as generated by print device
     * 
     */
    public String getJobUuid() {
        return jobUuid;
    }

    /**
     * unique job identifier, as generated by print device
     * 
     */
    public void setJobUuid(String jobUuid) {
        this.jobUuid = jobUuid;
    }

    /**
     * The reason why a job was paused
     * 
     */
    public com.hp.ws.cdm.jobmanagement.Job.PauseReason getPauseReason() {
        return pauseReason;
    }

    /**
     * The reason why a job was paused
     * 
     */
    public void setPauseReason(com.hp.ws.cdm.jobmanagement.Job.PauseReason pauseReason) {
        this.pauseReason = pauseReason;
    }

    /**
     * standard date and time format - according to RFC 3339. The date/time when the event was produced (according to the service).  It is of the form YYYY-MM-DD'T':HH:mm:SS.sssZ, for example '2012-04-21T08:15:13.511Z'
     * 
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * standard date and time format - according to RFC 3339. The date/time when the event was produced (according to the service).  It is of the form YYYY-MM-DD'T':HH:mm:SS.sssZ, for example '2012-04-21T08:15:13.511Z'
     * 
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This number is incremented for every new job completed at the device.  This property will not be set for active jobs.
     * 
     */
    public Integer getJobSequenceId() {
        return jobSequenceId;
    }

    /**
     * This number is incremented for every new job completed at the device.  This property will not be set for active jobs.
     * 
     */
    public void setJobSequenceId(Integer jobSequenceId) {
        this.jobSequenceId = jobSequenceId;
    }

    public com.hp.ws.cdm.jobmanagement.Job.State getState() {
        return state;
    }

    public void setState(com.hp.ws.cdm.jobmanagement.Job.State state) {
        this.state = state;
    }

    public com.hp.ws.cdm.jobmanagement.Job.ProcessingSubState getProcessingSubState() {
        return processingSubState;
    }

    public void setProcessingSubState(com.hp.ws.cdm.jobmanagement.Job.ProcessingSubState processingSubState) {
        this.processingSubState = processingSubState;
    }

    /**
     * The username of the person who owns this job.
     * 
     */
    public String getUserName() {
        return userName;
    }

    /**
     * The username of the person who owns this job.
     * 
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Clients can use this property to sort active jobs in the queue.  Higher priority jobs will have a smaller sortOrder value.  This property will not be set for completed jobs.  Use the jobSequenceId instead
     * 
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * Clients can use this property to sort active jobs in the queue.  Higher priority jobs will have a smaller sortOrder value.  This property will not be set for completed jobs.  Use the jobSequenceId instead
     * 
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    public enum ConnectionType {

        @SerializedName("usbDevice")
        USB_DEVICE("usbDevice"),
        @SerializedName("ethernet")
        ETHERNET("ethernet"),
        @SerializedName("wifi")
        WIFI("wifi"),
        @SerializedName("wifiDirect")
        WIFI_DIRECT("wifiDirect"),
        @SerializedName("bluetooth")
        BLUETOOTH("bluetooth"),
        @SerializedName("other")
        OTHER("other");
        private final String value;
        private final static Map<String, JobInfo.ConnectionType> CONSTANTS = new HashMap<String, JobInfo.ConnectionType>();

        static {
            for (JobInfo.ConnectionType c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        ConnectionType(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        public String value() {
            return this.value;
        }

        public static JobInfo.ConnectionType fromValue(String value) {
            JobInfo.ConnectionType constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }


    /**
     * category of the job
     * 
     */
    public enum JobCategory {

        @SerializedName("print")
        PRINT("print"),
        @SerializedName("scan")
        SCAN("scan"),
        @SerializedName("stored")
        STORED("stored"),
        @SerializedName("service")
        SERVICE("service"),
        @SerializedName("digitalSend")
        DIGITAL_SEND("digitalSend"),
        @SerializedName("copy")
        COPY("copy"),
        @SerializedName("fax")
        FAX("fax"),
        @SerializedName("reports")
        REPORTS("reports"),
        @SerializedName("mixed")
        MIXED("mixed"),
        @SerializedName("notification")
        NOTIFICATION("notification"),
        @SerializedName("other")
        OTHER("other");
        private final String value;
        private final static Map<String, JobInfo.JobCategory> CONSTANTS = new HashMap<String, JobInfo.JobCategory>();

        static {
            for (JobInfo.JobCategory c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        JobCategory(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        public String value() {
            return this.value;
        }

        public static JobInfo.JobCategory fromValue(String value) {
            JobInfo.JobCategory constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }


    /**
     * reasons for unsuccessful completion states
     * 
     */
    public enum JobCompletionDetail {

        @SerializedName("memoryOut")
        MEMORY_OUT("memoryOut"),
        @SerializedName("dirtyPowerUp")
        DIRTY_POWER_UP("dirtyPowerUp"),
        @SerializedName("aborted")
        ABORTED("aborted"),
        @SerializedName("userCancelled")
        USER_CANCELLED("userCancelled"),
        @SerializedName("systemCancelled")
        SYSTEM_CANCELLED("systemCancelled"),
        @SerializedName("printingSystemFailure")
        PRINTING_SYSTEM_FAILURE("printingSystemFailure"),
        @SerializedName("paperJam")
        PAPER_JAM("paperJam"),
        @SerializedName("quotaCancelled")
        QUOTA_CANCELLED("quotaCancelled"),
        @SerializedName("scanHwFailure")
        SCAN_HW_FAILURE("scanHwFailure");
        private final String value;
        private final static Map<String, JobInfo.JobCompletionDetail> CONSTANTS = new HashMap<String, JobInfo.JobCompletionDetail>();

        static {
            for (JobInfo.JobCompletionDetail c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        JobCompletionDetail(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        public String value() {
            return this.value;
        }

        public static JobInfo.JobCompletionDetail fromValue(String value) {
            JobInfo.JobCompletionDetail constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }


    /**
     * Source/Application where the job originated
     * 
     */
    public enum JobDataSource {

        @SerializedName("networkIo")
        NETWORK_IO("networkIo"),
        @SerializedName("directIo")
        DIRECT_IO("directIo"),
        @SerializedName("internalStorage")
        INTERNAL_STORAGE("internalStorage"),
        @SerializedName("removableStorage")
        REMOVABLE_STORAGE("removableStorage"),
        @SerializedName("embeddedWebSource")
        EMBEDDED_WEB_SOURCE("embeddedWebSource"),
        @SerializedName("scanner")
        SCANNER("scanner"),
        @SerializedName("system")
        SYSTEM("system"),
        @SerializedName("faxCard")
        FAX_CARD("faxCard"),
        @SerializedName("networkFolder")
        NETWORK_FOLDER("networkFolder"),
        @SerializedName("ldap")
        LDAP("ldap");
        private final String value;
        private final static Map<String, JobInfo.JobDataSource> CONSTANTS = new HashMap<String, JobInfo.JobDataSource>();

        static {
            for (JobInfo.JobDataSource c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        JobDataSource(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        public String value() {
            return this.value;
        }

        public static JobInfo.JobDataSource fromValue(String value) {
            JobInfo.JobDataSource constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }


    /**
     * googleCloudPrintCloud and googleCloudPrintLocal values are obsolete and no longer supported
     * 
     */
    public enum JobProtocolType {

        @SerializedName("ipp")
        IPP("ipp"),
        @SerializedName("googleCloudPrintCloud")
        GOOGLE_CLOUD_PRINT_CLOUD("googleCloudPrintCloud"),
        @SerializedName("googleCloudPrintLocal")
        GOOGLE_CLOUD_PRINT_LOCAL("googleCloudPrintLocal"),
        @SerializedName("wsPrint")
        WS_PRINT("wsPrint"),
        @SerializedName("wsScan")
        WS_SCAN("wsScan"),
        @SerializedName("port9100")
        PORT_9100("port9100"),
        @SerializedName("eSCL")
        E_SCL("eSCL"),
        @SerializedName("other")
        OTHER("other");
        private final String value;
        private final static Map<String, JobInfo.JobProtocolType> CONSTANTS = new HashMap<String, JobInfo.JobProtocolType>();

        static {
            for (JobInfo.JobProtocolType c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        JobProtocolType(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        public String value() {
            return this.value;
        }

        public static JobInfo.JobProtocolType fromValue(String value) {
            JobInfo.JobProtocolType constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }

    }

}
