/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.supply;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Represents a single device supply/consumable.
 */
public class Supply extends E2Type
{
    private com.hp.ext.types.usage.Counter approximatePagesRemaining;
    private com.hp.ext.types.supply.ApproximationDisplaySymbol approximatePagesRemainingSymbol;
    private String batchId;
    private String brand;
    private com.hp.ext.types.usage.UnitCounter capacity;
    private String cartridgeApplication;
    private java.util.List<com.hp.ext.types.supply.SupplyColorCode> colors;
    private String firstInstallDate;
    private com.hp.ext.types.supply.SupplySlotIdentifier group;
    private Long healthGaugeLevel;
    private String installDate;
    private String lastErrorCode;
    private String lastErrorTimestamp;
    private String lastRecoveryDate;
    private String lastUsedDate;
    private com.hp.ext.types.supply.SupplyLevelState levelState;
    private String manufactureDate;
    private java.lang.Byte percentLifeRemaining;
    private com.hp.ext.types.supply.ApproximationDisplaySymbol percentLifeRemainingSymbol;
    private com.hp.ext.types.supply.SupplyProductNumber productNumber;
    private String serialNumber;
    private com.hp.ext.types.supply.SupplySlotIdentifier slotId;
    private com.hp.ext.types.supply.SupplySlotRole slotRole;
    private java.util.List<com.hp.ext.types.supply.SupplySlotIdentifier> slotsInGroup;
    private com.hp.ext.types.supply.SupplyState state;
    private java.util.List<com.hp.ext.types.supply.SupplyStateReason> stateReasons;
    private com.hp.ext.types.supply.SupplyAgentType supplyAgentType;
    private com.hp.ext.types.supply.SupplyColorCode supplyColor;
    private String supplyDescription;
    private com.hp.ext.types.supply.SupplyType supplyType;
    private com.hp.ext.types.supply.SupplyUniqueIdentifier supplyUniqueId;
    private com.hp.ext.types.usage.Counter usageTimeHours;
    
    @JsonProperty("approximatePagesRemaining")
    public com.hp.ext.types.usage.Counter getApproximatePagesRemaining() {
        return approximatePagesRemaining;
    }

    @JsonProperty("approximatePagesRemaining")
    public void setApproximatePagesRemaining(com.hp.ext.types.usage.Counter approximatePagesRemaining) {
        this.approximatePagesRemaining = approximatePagesRemaining;
    }
    @JsonProperty("approximatePagesRemainingSymbol")
    public com.hp.ext.types.supply.ApproximationDisplaySymbol getApproximatePagesRemainingSymbol() {
        return approximatePagesRemainingSymbol;
    }

    @JsonProperty("approximatePagesRemainingSymbol")
    public void setApproximatePagesRemainingSymbol(com.hp.ext.types.supply.ApproximationDisplaySymbol approximatePagesRemainingSymbol) {
        this.approximatePagesRemainingSymbol = approximatePagesRemainingSymbol;
    }
    @JsonProperty("batchId")
    public String getBatchId() {
        return batchId;
    }

    @JsonProperty("batchId")
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }
    @JsonProperty("brand")
    public String getBrand() {
        return brand;
    }

    @JsonProperty("brand")
    public void setBrand(String brand) {
        this.brand = brand;
    }
    @JsonProperty("capacity")
    public com.hp.ext.types.usage.UnitCounter getCapacity() {
        return capacity;
    }

    @JsonProperty("capacity")
    public void setCapacity(com.hp.ext.types.usage.UnitCounter capacity) {
        this.capacity = capacity;
    }
    @JsonProperty("cartridgeApplication")
    public String getCartridgeApplication() {
        return cartridgeApplication;
    }

    @JsonProperty("cartridgeApplication")
    public void setCartridgeApplication(String cartridgeApplication) {
        this.cartridgeApplication = cartridgeApplication;
    }
    @JsonProperty("colors")
    public java.util.List<com.hp.ext.types.supply.SupplyColorCode> getColors() {
        return colors;
    }

    @JsonProperty("colors")
    public void setColors(java.util.List<com.hp.ext.types.supply.SupplyColorCode> colors) {
        this.colors = colors;
    }
    @JsonProperty("firstInstallDate")
    public String getFirstInstallDate() {
        return firstInstallDate;
    }

    @JsonProperty("firstInstallDate")
    public void setFirstInstallDate(String firstInstallDate) {
        this.firstInstallDate = firstInstallDate;
    }
    @JsonProperty("group")
    public com.hp.ext.types.supply.SupplySlotIdentifier getGroup() {
        return group;
    }

    @JsonProperty("group")
    public void setGroup(com.hp.ext.types.supply.SupplySlotIdentifier group) {
        this.group = group;
    }
    @JsonProperty("healthGaugeLevel")
    public Long getHealthGaugeLevel() {
        return healthGaugeLevel;
    }

    @JsonProperty("healthGaugeLevel")
    public void setHealthGaugeLevel(Long healthGaugeLevel) {
        this.healthGaugeLevel = healthGaugeLevel;
    }
    @JsonProperty("installDate")
    public String getInstallDate() {
        return installDate;
    }

    @JsonProperty("installDate")
    public void setInstallDate(String installDate) {
        this.installDate = installDate;
    }
    @JsonProperty("lastErrorCode")
    public String getLastErrorCode() {
        return lastErrorCode;
    }

    @JsonProperty("lastErrorCode")
    public void setLastErrorCode(String lastErrorCode) {
        this.lastErrorCode = lastErrorCode;
    }
    @JsonProperty("lastErrorTimestamp")
    public String getLastErrorTimestamp() {
        return lastErrorTimestamp;
    }

    @JsonProperty("lastErrorTimestamp")
    public void setLastErrorTimestamp(String lastErrorTimestamp) {
        this.lastErrorTimestamp = lastErrorTimestamp;
    }
    @JsonProperty("lastRecoveryDate")
    public String getLastRecoveryDate() {
        return lastRecoveryDate;
    }

    @JsonProperty("lastRecoveryDate")
    public void setLastRecoveryDate(String lastRecoveryDate) {
        this.lastRecoveryDate = lastRecoveryDate;
    }
    @JsonProperty("lastUsedDate")
    public String getLastUsedDate() {
        return lastUsedDate;
    }

    @JsonProperty("lastUsedDate")
    public void setLastUsedDate(String lastUsedDate) {
        this.lastUsedDate = lastUsedDate;
    }
    @JsonProperty("levelState")
    public com.hp.ext.types.supply.SupplyLevelState getLevelState() {
        return levelState;
    }

    @JsonProperty("levelState")
    public void setLevelState(com.hp.ext.types.supply.SupplyLevelState levelState) {
        this.levelState = levelState;
    }
    @JsonProperty("manufactureDate")
    public String getManufactureDate() {
        return manufactureDate;
    }

    @JsonProperty("manufactureDate")
    public void setManufactureDate(String manufactureDate) {
        this.manufactureDate = manufactureDate;
    }
    @JsonProperty("percentLifeRemaining")
    public java.lang.Byte getPercentLifeRemaining() {
        return percentLifeRemaining;
    }

    @JsonProperty("percentLifeRemaining")
    public void setPercentLifeRemaining(java.lang.Byte percentLifeRemaining) {
        this.percentLifeRemaining = percentLifeRemaining;
    }
    @JsonProperty("percentLifeRemainingSymbol")
    public com.hp.ext.types.supply.ApproximationDisplaySymbol getPercentLifeRemainingSymbol() {
        return percentLifeRemainingSymbol;
    }

    @JsonProperty("percentLifeRemainingSymbol")
    public void setPercentLifeRemainingSymbol(com.hp.ext.types.supply.ApproximationDisplaySymbol percentLifeRemainingSymbol) {
        this.percentLifeRemainingSymbol = percentLifeRemainingSymbol;
    }
    @JsonProperty("productNumber")
    public com.hp.ext.types.supply.SupplyProductNumber getProductNumber() {
        return productNumber;
    }

    @JsonProperty("productNumber")
    public void setProductNumber(com.hp.ext.types.supply.SupplyProductNumber productNumber) {
        this.productNumber = productNumber;
    }
    @JsonProperty("serialNumber")
    public String getSerialNumber() {
        return serialNumber;
    }

    @JsonProperty("serialNumber")
    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }
    @JsonProperty("slotId")
    public com.hp.ext.types.supply.SupplySlotIdentifier getSlotId() {
        return slotId;
    }

    @JsonProperty("slotId")
    public void setSlotId(com.hp.ext.types.supply.SupplySlotIdentifier slotId) {
        this.slotId = slotId;
    }
    @JsonProperty("slotRole")
    public com.hp.ext.types.supply.SupplySlotRole getSlotRole() {
        return slotRole;
    }

    @JsonProperty("slotRole")
    public void setSlotRole(com.hp.ext.types.supply.SupplySlotRole slotRole) {
        this.slotRole = slotRole;
    }
    @JsonProperty("slotsInGroup")
    public java.util.List<com.hp.ext.types.supply.SupplySlotIdentifier> getSlotsInGroup() {
        return slotsInGroup;
    }

    @JsonProperty("slotsInGroup")
    public void setSlotsInGroup(java.util.List<com.hp.ext.types.supply.SupplySlotIdentifier> slotsInGroup) {
        this.slotsInGroup = slotsInGroup;
    }
    @JsonProperty("state")
    public com.hp.ext.types.supply.SupplyState getState() {
        return state;
    }

    @JsonProperty("state")
    public void setState(com.hp.ext.types.supply.SupplyState state) {
        this.state = state;
    }
    @JsonProperty("stateReasons")
    public java.util.List<com.hp.ext.types.supply.SupplyStateReason> getStateReasons() {
        return stateReasons;
    }

    @JsonProperty("stateReasons")
    public void setStateReasons(java.util.List<com.hp.ext.types.supply.SupplyStateReason> stateReasons) {
        this.stateReasons = stateReasons;
    }
    @JsonProperty("supplyAgentType")
    public com.hp.ext.types.supply.SupplyAgentType getSupplyAgentType() {
        return supplyAgentType;
    }

    @JsonProperty("supplyAgentType")
    public void setSupplyAgentType(com.hp.ext.types.supply.SupplyAgentType supplyAgentType) {
        this.supplyAgentType = supplyAgentType;
    }
    @JsonProperty("supplyColor")
    public com.hp.ext.types.supply.SupplyColorCode getSupplyColor() {
        return supplyColor;
    }

    @JsonProperty("supplyColor")
    public void setSupplyColor(com.hp.ext.types.supply.SupplyColorCode supplyColor) {
        this.supplyColor = supplyColor;
    }
    @JsonProperty("supplyDescription")
    public String getSupplyDescription() {
        return supplyDescription;
    }

    @JsonProperty("supplyDescription")
    public void setSupplyDescription(String supplyDescription) {
        this.supplyDescription = supplyDescription;
    }
    @JsonProperty("supplyType")
    public com.hp.ext.types.supply.SupplyType getSupplyType() {
        return supplyType;
    }

    @JsonProperty("supplyType")
    public void setSupplyType(com.hp.ext.types.supply.SupplyType supplyType) {
        this.supplyType = supplyType;
    }
    @JsonProperty("supplyUniqueId")
    public com.hp.ext.types.supply.SupplyUniqueIdentifier getSupplyUniqueId() {
        return supplyUniqueId;
    }

    @JsonProperty("supplyUniqueId")
    public void setSupplyUniqueId(com.hp.ext.types.supply.SupplyUniqueIdentifier supplyUniqueId) {
        this.supplyUniqueId = supplyUniqueId;
    }
    @JsonProperty("usageTimeHours")
    public com.hp.ext.types.usage.Counter getUsageTimeHours() {
        return usageTimeHours;
    }

    @JsonProperty("usageTimeHours")
    public void setUsageTimeHours(com.hp.ext.types.usage.Counter usageTimeHours) {
        this.usageTimeHours = usageTimeHours;
    }
    public Supply()
    {
        majorVersion = SupplyTypesManifest.getInstance().MajorVersion;
        typeName = "supply";
        typeGUN = "com.hp.ext.types.supply.version.1.type.supply";
    }
}
