/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.supply;

import com.hp.ext.types.common.E2Alias;

/**
 * The product number of a supply.
 */
public class SupplyProductNumber extends E2Alias<String> 
{
    public SupplyProductNumber() 
    {
        this(null);
    }

    public SupplyProductNumber(String value)
    {
        super(value);
        majorVersion = SupplyTypesManifest.getInstance().MajorVersion;
        typeName = "supplyProductNumber";
        typeGUN = "com.hp.ext.types.supply.version.1.type.supplyProductNumber";
    }

    public SupplyProductNumber valueOf(String value) { return new SupplyProductNumber(value); }

    @Override public String toString() { return value.toString(); }
}
