/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A Type used to encapsulate the description and identification of the currently active application.
 */
public class ActiveApplication extends E2Type
{
    private java.util.UUID applicationId;
    private String name;
    private com.hp.ext.types.agent.SolutionId solutionId;
    
    @JsonProperty("applicationId")
    public java.util.UUID getApplicationId() {
        return applicationId;
    }

    @JsonProperty("applicationId")
    public void setApplicationId(java.util.UUID applicationId) {
        this.applicationId = applicationId;
    }
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("name")
    public void setName(String name) {
        this.name = name;
    }
    @JsonProperty("solutionId")
    public com.hp.ext.types.agent.SolutionId getSolutionId() {
        return solutionId;
    }

    @JsonProperty("solutionId")
    public void setSolutionId(com.hp.ext.types.agent.SolutionId solutionId) {
        this.solutionId = solutionId;
    }
    public ActiveApplication()
    {
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "activeApplication";
        typeGUN = "com.hp.ext.types.application.version.1.type.activeApplication";
    }
}
