/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Defines the content of the application resource. Primarily consists of data that was provided in the application registration record with the solution manifest.
 */
public class ApplicationContent extends E2Type
{
    private com.hp.ext.types.application.ApplicationCategory category;
    private com.hp.ext.types.application.ApplicationChrome chrome;
    private com.hp.ext.types.application.ApplicationContent_Enabled_Binding enabled;
    private com.hp.ext.types.application.ApplicationFailureBehavior failureBehavior;
    private com.hp.ext.types.application.ApplicationImage icon;
    private java.util.List<com.hp.ext.types.application.KeyedApplicationImage> iconSet;
    private com.hp.ext.types.application.ApplicationIntentDefinition intentProfile;
    private com.hp.ext.types.localization.LocalizedStringReference localizedTitle;
    private com.hp.ext.types.application.ApplicationPlatform platform;
    private com.hp.ext.types.application.ApplicationTarget target;
    private com.hp.ext.types.agent.AgentId agentId;
    private com.hp.ext.types.localization.LocalizedStringReference localizedDescription;
    private com.hp.ext.types.localization.LocalizedStringReference localizedName;
    private com.hp.ext.types.agent.AgentName name;
    
    @JsonProperty("category")
    public com.hp.ext.types.application.ApplicationCategory getCategory() {
        return category;
    }

    @JsonProperty("category")
    public void setCategory(com.hp.ext.types.application.ApplicationCategory category) {
        this.category = category;
    }
    @JsonProperty("chrome")
    public com.hp.ext.types.application.ApplicationChrome getChrome() {
        return chrome;
    }

    @JsonProperty("chrome")
    public void setChrome(com.hp.ext.types.application.ApplicationChrome chrome) {
        this.chrome = chrome;
    }
    @JsonProperty("enabled")
    public com.hp.ext.types.application.ApplicationContent_Enabled_Binding getEnabled() {
        return enabled;
    }

    @JsonProperty("enabled")
    public void setEnabled(com.hp.ext.types.application.ApplicationContent_Enabled_Binding enabled) {
        this.enabled = enabled;
    }
    @JsonProperty("failureBehavior")
    public com.hp.ext.types.application.ApplicationFailureBehavior getFailureBehavior() {
        return failureBehavior;
    }

    @JsonProperty("failureBehavior")
    public void setFailureBehavior(com.hp.ext.types.application.ApplicationFailureBehavior failureBehavior) {
        this.failureBehavior = failureBehavior;
    }
    @JsonProperty("icon")
    public com.hp.ext.types.application.ApplicationImage getIcon() {
        return icon;
    }

    @JsonProperty("icon")
    public void setIcon(com.hp.ext.types.application.ApplicationImage icon) {
        this.icon = icon;
    }
    @JsonProperty("iconSet")
    public java.util.List<com.hp.ext.types.application.KeyedApplicationImage> getIconSet() {
        return iconSet;
    }

    @JsonProperty("iconSet")
    public void setIconSet(java.util.List<com.hp.ext.types.application.KeyedApplicationImage> iconSet) {
        this.iconSet = iconSet;
    }
    @JsonProperty("intentProfile")
    public com.hp.ext.types.application.ApplicationIntentDefinition getIntentProfile() {
        return intentProfile;
    }

    @JsonProperty("intentProfile")
    public void setIntentProfile(com.hp.ext.types.application.ApplicationIntentDefinition intentProfile) {
        this.intentProfile = intentProfile;
    }
    @JsonProperty("localizedTitle")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedTitle() {
        return localizedTitle;
    }

    @JsonProperty("localizedTitle")
    public void setLocalizedTitle(com.hp.ext.types.localization.LocalizedStringReference localizedTitle) {
        this.localizedTitle = localizedTitle;
    }
    @JsonProperty("platform")
    public com.hp.ext.types.application.ApplicationPlatform getPlatform() {
        return platform;
    }

    @JsonProperty("platform")
    public void setPlatform(com.hp.ext.types.application.ApplicationPlatform platform) {
        this.platform = platform;
    }
    @JsonProperty("target")
    public com.hp.ext.types.application.ApplicationTarget getTarget() {
        return target;
    }

    @JsonProperty("target")
    public void setTarget(com.hp.ext.types.application.ApplicationTarget target) {
        this.target = target;
    }
    @JsonProperty("agentId")
    public com.hp.ext.types.agent.AgentId getAgentId() {
        return agentId;
    }

    @JsonProperty("agentId")
    public void setAgentId(com.hp.ext.types.agent.AgentId agentId) {
        this.agentId = agentId;
    }
    @JsonProperty("localizedDescription")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedDescription() {
        return localizedDescription;
    }

    @JsonProperty("localizedDescription")
    public void setLocalizedDescription(com.hp.ext.types.localization.LocalizedStringReference localizedDescription) {
        this.localizedDescription = localizedDescription;
    }
    @JsonProperty("localizedName")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedName() {
        return localizedName;
    }

    @JsonProperty("localizedName")
    public void setLocalizedName(com.hp.ext.types.localization.LocalizedStringReference localizedName) {
        this.localizedName = localizedName;
    }
    @JsonProperty("name")
    public com.hp.ext.types.agent.AgentName getName() {
        return name;
    }

    @JsonProperty("name")
    public void setName(com.hp.ext.types.agent.AgentName name) {
        this.name = name;
    }
    public ApplicationContent()
    {
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "applicationContent";
        typeGUN = "com.hp.ext.types.application.version.1.type.applicationContent";
    }
}
