/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Defines the failure-behavior for an application.
 */
public class ApplicationFailureBehavior extends E2Type
{
    private Boolean isDismissible;
    private com.hp.ext.types.localization.LocalizedStringReference localizedMessage;
    private com.hp.ext.types.localization.LocalizedStringReference localizedTitle;
    private com.hp.ext.types.common.RgbColor titleBackgroundColor;
    private com.hp.ext.types.common.RgbColor titleForegroundColor;
    
    @JsonProperty("isDismissible")
    public Boolean getIsDismissible() {
        return isDismissible;
    }

    @JsonProperty("isDismissible")
    public void setIsDismissible(Boolean isDismissible) {
        this.isDismissible = isDismissible;
    }
    @JsonProperty("localizedMessage")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedMessage() {
        return localizedMessage;
    }

    @JsonProperty("localizedMessage")
    public void setLocalizedMessage(com.hp.ext.types.localization.LocalizedStringReference localizedMessage) {
        this.localizedMessage = localizedMessage;
    }
    @JsonProperty("localizedTitle")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedTitle() {
        return localizedTitle;
    }

    @JsonProperty("localizedTitle")
    public void setLocalizedTitle(com.hp.ext.types.localization.LocalizedStringReference localizedTitle) {
        this.localizedTitle = localizedTitle;
    }
    @JsonProperty("titleBackgroundColor")
    public com.hp.ext.types.common.RgbColor getTitleBackgroundColor() {
        return titleBackgroundColor;
    }

    @JsonProperty("titleBackgroundColor")
    public void setTitleBackgroundColor(com.hp.ext.types.common.RgbColor titleBackgroundColor) {
        this.titleBackgroundColor = titleBackgroundColor;
    }
    @JsonProperty("titleForegroundColor")
    public com.hp.ext.types.common.RgbColor getTitleForegroundColor() {
        return titleForegroundColor;
    }

    @JsonProperty("titleForegroundColor")
    public void setTitleForegroundColor(com.hp.ext.types.common.RgbColor titleForegroundColor) {
        this.titleForegroundColor = titleForegroundColor;
    }
    public ApplicationFailureBehavior()
    {
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "applicationFailureBehavior";
        typeGUN = "com.hp.ext.types.application.version.1.type.applicationFailureBehavior";
    }
}
