/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;
import com.hp.ext.types.common.IE2Polymorph;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;

/**
 * This type is used to represent an application image, typically used as the icon for the application when displayed as a button or panel on the user interface
 */
@JsonSerialize(using = ApplicationImage.Serializer.class)
public class ApplicationImage extends E2Type implements IE2Polymorph
{
    private Object polymorphInstance;

    public Object getInstance() {
        return polymorphInstance;
    }

    public void setInstance(Object o) {
        polymorphInstance = o;
    }

    public boolean isInlineImage()
    { 
        return polymorphInstance instanceof com.hp.ext.types.application.InlineImage;
    }

    public void setInlineImage(com.hp.ext.types.application.InlineImage value) {
        polymorphInstance = value;
    }

    public com.hp.ext.types.application.InlineImage getInlineImage() {
        return (com.hp.ext.types.application.InlineImage)polymorphInstance;
    }
    public boolean isLocalImage()
    { 
        return polymorphInstance instanceof com.hp.ext.types.application.LocalImage;
    }

    public void setLocalImage(com.hp.ext.types.application.LocalImage value) {
        polymorphInstance = value;
    }

    public com.hp.ext.types.application.LocalImage getLocalImage() {
        return (com.hp.ext.types.application.LocalImage)polymorphInstance;
    }

    public ApplicationImage()
    {
        this(null);
    }

    public ApplicationImage(Object obj)
    {
        polymorphInstance = obj;
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "applicationImage";
        typeGUN = "com.hp.ext.types.application.version.1.type.applicationImage";
    }

    public static class Serializer extends StdSerializer<ApplicationImage> {
    
        public Serializer() {
            this(null);
        }
      
        public Serializer(Class<ApplicationImage> t) {
            super(t);
        }
    
        @Override
        public void serialize(ApplicationImage value, JsonGenerator jgen, SerializerProvider provider) 
          throws IOException, JsonProcessingException {
     
            jgen.writeStartObject();
            if (value.isInlineImage()) {
                jgen.writeObjectField("inlineImage", value.getInlineImage());
            }
            if (value.isLocalImage()) {
                jgen.writeObjectField("localImage", value.getLocalImage());
            }
            jgen.writeEndObject();
        }
    }
};
