/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Defines the readable content of the application resource.
 */
public class ApplicationContentReadable extends E2Type
{
    private com.hp.ext.types.agent.AgentId agentId;
    private com.hp.ext.types.localization.LocalizedStringReference localizedDescription;
    private com.hp.ext.types.localization.LocalizedStringReference localizedName;
    private com.hp.ext.types.agent.AgentName name;
    
    @JsonProperty("agentId")
    public com.hp.ext.types.agent.AgentId getAgentId() {
        return agentId;
    }

    @JsonProperty("agentId")
    public void setAgentId(com.hp.ext.types.agent.AgentId agentId) {
        this.agentId = agentId;
    }
    @JsonProperty("localizedDescription")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedDescription() {
        return localizedDescription;
    }

    @JsonProperty("localizedDescription")
    public void setLocalizedDescription(com.hp.ext.types.localization.LocalizedStringReference localizedDescription) {
        this.localizedDescription = localizedDescription;
    }
    @JsonProperty("localizedName")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedName() {
        return localizedName;
    }

    @JsonProperty("localizedName")
    public void setLocalizedName(com.hp.ext.types.localization.LocalizedStringReference localizedName) {
        this.localizedName = localizedName;
    }
    @JsonProperty("name")
    public com.hp.ext.types.agent.AgentName getName() {
        return name;
    }

    @JsonProperty("name")
    public void setName(com.hp.ext.types.agent.AgentName name) {
        this.name = name;
    }
    public ApplicationContentReadable()
    {
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "applicationContentReadable";
        typeGUN = "com.hp.ext.types.application.version.1.type.applicationContentReadable";
    }
}
