/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;
import com.hp.ext.types.common.IE2Polymorph;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;

/**
 * The runtime "chrome" for an application. It's a polymorph in order to support various application types.
 */
@JsonSerialize(using = ApplicationRuntimeChrome.Serializer.class)
public class ApplicationRuntimeChrome extends E2Type implements IE2Polymorph
{
    private Object polymorphInstance;

    public Object getInstance() {
        return polymorphInstance;
    }

    public void setInstance(Object o) {
        polymorphInstance = o;
    }

    public boolean isWebApplicationRuntimeChrome()
    { 
        return polymorphInstance instanceof com.hp.ext.types.application.WebApplicationRuntimeChrome;
    }

    public void setWebApplicationRuntimeChrome(com.hp.ext.types.application.WebApplicationRuntimeChrome value) {
        polymorphInstance = value;
    }

    public com.hp.ext.types.application.WebApplicationRuntimeChrome getWebApplicationRuntimeChrome() {
        return (com.hp.ext.types.application.WebApplicationRuntimeChrome)polymorphInstance;
    }
    public boolean isWorkpathApplicationRuntimeChrome()
    { 
        return polymorphInstance instanceof com.hp.ext.types.application.WorkpathApplicationRuntimeChrome;
    }

    public void setWorkpathApplicationRuntimeChrome(com.hp.ext.types.application.WorkpathApplicationRuntimeChrome value) {
        polymorphInstance = value;
    }

    public com.hp.ext.types.application.WorkpathApplicationRuntimeChrome getWorkpathApplicationRuntimeChrome() {
        return (com.hp.ext.types.application.WorkpathApplicationRuntimeChrome)polymorphInstance;
    }

    public ApplicationRuntimeChrome()
    {
        this(null);
    }

    public ApplicationRuntimeChrome(Object obj)
    {
        polymorphInstance = obj;
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "applicationRuntimeChrome";
        typeGUN = "com.hp.ext.types.application.version.1.type.applicationRuntimeChrome";
    }

    public static class Serializer extends StdSerializer<ApplicationRuntimeChrome> {
    
        public Serializer() {
            this(null);
        }
      
        public Serializer(Class<ApplicationRuntimeChrome> t) {
            super(t);
        }
    
        @Override
        public void serialize(ApplicationRuntimeChrome value, JsonGenerator jgen, SerializerProvider provider) 
          throws IOException, JsonProcessingException {
     
            jgen.writeStartObject();
            if (value.isWebApplicationRuntimeChrome()) {
                jgen.writeObjectField("webApplicationRuntimeChrome", value.getWebApplicationRuntimeChrome());
            }
            if (value.isWorkpathApplicationRuntimeChrome()) {
                jgen.writeObjectField("workpathApplicationRuntimeChrome", value.getWorkpathApplicationRuntimeChrome());
            }
            jgen.writeEndObject();
        }
    }
};
