/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Alias;

/**
 * Access point names are limited to 255 characters.
 */
public class ApplicationAccessPointTitle extends E2Alias<String> 
{
    public ApplicationAccessPointTitle() 
    {
        this(null);
    }

    public ApplicationAccessPointTitle(String value)
    {
        super(value);
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "applicationAccessPointTitle";
        typeGUN = "com.hp.ext.types.application.version.1.type.applicationAccessPointTitle";
    }

    public ApplicationAccessPointTitle valueOf(String value) { return new ApplicationAccessPointTitle(value); }

    @Override public String toString() { return value.toString(); }
}
