/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;

/**
 * The application context is unable to be reserved because the device's UI is already in use.
 */
public class ConcurrencyError extends E2Type
{
    
    public ConcurrencyError()
    {
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "concurrencyError";
        typeGUN = "com.hp.ext.types.application.version.1.type.concurrencyError";
    }
}
