/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * An in-line localized message to be persistently displayed on the device homescreen.
 */
public class HomescreenInlineMessage extends E2Type
{
    private com.hp.ext.types.localization.LocalizedString message;
    
    @JsonProperty("message")
    public com.hp.ext.types.localization.LocalizedString getMessage() {
        return message;
    }

    @JsonProperty("message")
    public void setMessage(com.hp.ext.types.localization.LocalizedString message) {
        this.message = message;
    }
    public HomescreenInlineMessage()
    {
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "homescreenInlineMessage";
        typeGUN = "com.hp.ext.types.application.version.1.type.homescreenInlineMessage";
    }
}
