/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Defines a custom "card" to be displayed on the device homescreen.
 */
public class HomescreenCard extends E2Type
{
    private java.util.UUID actionAccessPoint;
    private com.hp.ext.types.localization.LocalizedStringReference actionLabel;
    private Boolean actionable;
    private com.hp.ext.types.localization.LocalizedStringReference content;
    private Boolean enabled;
    private com.hp.ext.types.application.ApplicationImage icon;
    private com.hp.ext.types.application.ApplicationImage image;
    private com.hp.ext.types.localization.LocalizedStringReference title;
    
    @JsonProperty("actionAccessPoint")
    public java.util.UUID getActionAccessPoint() {
        return actionAccessPoint;
    }

    @JsonProperty("actionAccessPoint")
    public void setActionAccessPoint(java.util.UUID actionAccessPoint) {
        this.actionAccessPoint = actionAccessPoint;
    }
    @JsonProperty("actionLabel")
    public com.hp.ext.types.localization.LocalizedStringReference getActionLabel() {
        return actionLabel;
    }

    @JsonProperty("actionLabel")
    public void setActionLabel(com.hp.ext.types.localization.LocalizedStringReference actionLabel) {
        this.actionLabel = actionLabel;
    }
    @JsonProperty("actionable")
    public Boolean getActionable() {
        return actionable;
    }

    @JsonProperty("actionable")
    public void setActionable(Boolean actionable) {
        this.actionable = actionable;
    }
    @JsonProperty("content")
    public com.hp.ext.types.localization.LocalizedStringReference getContent() {
        return content;
    }

    @JsonProperty("content")
    public void setContent(com.hp.ext.types.localization.LocalizedStringReference content) {
        this.content = content;
    }
    @JsonProperty("enabled")
    public Boolean getEnabled() {
        return enabled;
    }

    @JsonProperty("enabled")
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
    @JsonProperty("icon")
    public com.hp.ext.types.application.ApplicationImage getIcon() {
        return icon;
    }

    @JsonProperty("icon")
    public void setIcon(com.hp.ext.types.application.ApplicationImage icon) {
        this.icon = icon;
    }
    @JsonProperty("image")
    public com.hp.ext.types.application.ApplicationImage getImage() {
        return image;
    }

    @JsonProperty("image")
    public void setImage(com.hp.ext.types.application.ApplicationImage image) {
        this.image = image;
    }
    @JsonProperty("title")
    public com.hp.ext.types.localization.LocalizedStringReference getTitle() {
        return title;
    }

    @JsonProperty("title")
    public void setTitle(com.hp.ext.types.localization.LocalizedStringReference title) {
        this.title = title;
    }
    public HomescreenCard()
    {
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "homescreenCard";
        typeGUN = "com.hp.ext.types.application.version.1.type.homescreenCard";
    }
}
