/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The I18nAsset Resource definition.
 */
public class I18nAssetContentReadable extends E2Type
{
    private com.hp.ext.types.agent.AssetId assetId;
    
    @JsonProperty("assetId")
    public com.hp.ext.types.agent.AssetId getAssetId() {
        return assetId;
    }

    @JsonProperty("assetId")
    public void setAssetId(com.hp.ext.types.agent.AssetId assetId) {
        this.assetId = assetId;
    }
    public I18nAssetContentReadable()
    {
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "i18nAssetContentReadable";
        typeGUN = "com.hp.ext.types.application.version.1.type.i18nAssetContentReadable";
    }
}
