/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The payload posted to the resultIntentNotficationTarget if the target property is used in an initiateLaunchRequest operation.
 */
public class ResultIntentNotificationContent extends E2Type
{
    private Object resultIntent;
    
    @JsonProperty("resultIntent")
    public Object getResultIntent() {
        return resultIntent;
    }

    @JsonProperty("resultIntent")
    public void setResultIntent(Object resultIntent) {
        this.resultIntent = resultIntent;
    }
    public ResultIntentNotificationContent()
    {
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "resultIntentNotificationContent";
        typeGUN = "com.hp.ext.types.application.version.1.type.resultIntentNotificationContent";
    }
}
