/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * An enumeration of defined soft keyboard types
 */
@JsonDeserialize(using = SoftKeyboardType.Deserializer.class)
public class SoftKeyboardType extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * Identifies the absence of a soft keyboard.
    */
    public static SoftKeyboardType SktNone = new SoftKeyboardType("sktNone");
    /**
     * Identifies a standard soft QWERTY keyboard.
    */
    public static SoftKeyboardType SktStandard = new SoftKeyboardType("sktStandard");
    /**
     * Phone keypad that includes # and * keys.
    */
    public static SoftKeyboardType SktFax = new SoftKeyboardType("sktFax");
    /**
     * Number key (includes decimal, + and - signs).
    */
    public static SoftKeyboardType SktFraction = new SoftKeyboardType("sktFraction");
    /**
     * 0-9 and A-F keys only keyboard.
    */
    public static SoftKeyboardType SktHex = new SoftKeyboardType("sktHex");
    /**
     * A numbers only keyboard.
    */
    public static SoftKeyboardType SktPin = new SoftKeyboardType("sktPin");

    protected static Hashtable<String, SoftKeyboardType> definitions;
    
    static {
        definitions = new Hashtable<String, SoftKeyboardType> ();
        definitions.put(SktNone.getValue(), SktNone);
        definitions.put(SktStandard.getValue(), SktStandard);
        definitions.put(SktFax.getValue(), SktFax);
        definitions.put(SktFraction.getValue(), SktFraction);
        definitions.put(SktHex.getValue(), SktHex);
        definitions.put(SktPin.getValue(), SktPin);
    }

    private SoftKeyboardType() {
        this(null);
    }

    private SoftKeyboardType(String name) {
        this(name, name);
    }

    private SoftKeyboardType(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "softKeyboardType";
        typeGUN = "com.hp.ext.types.application.version.1.type.softKeyboardType";
    }

    public static SoftKeyboardType Parse(String name)
    {
        SoftKeyboardType instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  SoftKeyboardType(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<SoftKeyboardType> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public SoftKeyboardType deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return SoftKeyboardType.Parse(node.asText());
        }
    }
}
