/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;

/**
 * The applicationId provided in the request could not be found.
 */
public class UnknownApplicationError extends E2Type
{
    
    public UnknownApplicationError()
    {
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "unknownApplicationError";
        typeGUN = "com.hp.ext.types.application.version.1.type.unknownApplicationError";
    }
}
