/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A collection of UI and control-panel attributes of interest to a solution provider.
 */
public class UserInterfaceAttributes extends E2Type
{
    private java.util.List<com.hp.ext.types.common.InternetMediaType> applicationIconFormats;
    private com.hp.ext.types.protocol.Unsigned16 applicationIconHeight;
    private com.hp.ext.types.protocol.Unsigned16 applicationIconWidth;
    private com.hp.ext.types.protocol.Unsigned16 displayResolutionX;
    private com.hp.ext.types.protocol.Unsigned16 displayResolutionY;
    private String displaySize;
    private com.hp.ext.types.protocol.Unsigned16 footerHeight;
    private com.hp.ext.types.application.HardKeyboardType hardKeyboardType;
    private Boolean hasHardBackKey;
    private Boolean hasHardHomeKey;
    private com.hp.ext.types.protocol.Unsigned16 headerHeight;
    private String nativeTheme;
    private java.util.List<com.hp.ext.types.application.SoftKeyboardType> softKeyboardTypes;
    
    @JsonProperty("applicationIconFormats")
    public java.util.List<com.hp.ext.types.common.InternetMediaType> getApplicationIconFormats() {
        return applicationIconFormats;
    }

    @JsonProperty("applicationIconFormats")
    public void setApplicationIconFormats(java.util.List<com.hp.ext.types.common.InternetMediaType> applicationIconFormats) {
        this.applicationIconFormats = applicationIconFormats;
    }
    @JsonProperty("applicationIconHeight")
    public com.hp.ext.types.protocol.Unsigned16 getApplicationIconHeight() {
        return applicationIconHeight;
    }

    @JsonProperty("applicationIconHeight")
    public void setApplicationIconHeight(com.hp.ext.types.protocol.Unsigned16 applicationIconHeight) {
        this.applicationIconHeight = applicationIconHeight;
    }
    @JsonProperty("applicationIconWidth")
    public com.hp.ext.types.protocol.Unsigned16 getApplicationIconWidth() {
        return applicationIconWidth;
    }

    @JsonProperty("applicationIconWidth")
    public void setApplicationIconWidth(com.hp.ext.types.protocol.Unsigned16 applicationIconWidth) {
        this.applicationIconWidth = applicationIconWidth;
    }
    @JsonProperty("displayResolutionX")
    public com.hp.ext.types.protocol.Unsigned16 getDisplayResolutionX() {
        return displayResolutionX;
    }

    @JsonProperty("displayResolutionX")
    public void setDisplayResolutionX(com.hp.ext.types.protocol.Unsigned16 displayResolutionX) {
        this.displayResolutionX = displayResolutionX;
    }
    @JsonProperty("displayResolutionY")
    public com.hp.ext.types.protocol.Unsigned16 getDisplayResolutionY() {
        return displayResolutionY;
    }

    @JsonProperty("displayResolutionY")
    public void setDisplayResolutionY(com.hp.ext.types.protocol.Unsigned16 displayResolutionY) {
        this.displayResolutionY = displayResolutionY;
    }
    @JsonProperty("displaySize")
    public String getDisplaySize() {
        return displaySize;
    }

    @JsonProperty("displaySize")
    public void setDisplaySize(String displaySize) {
        this.displaySize = displaySize;
    }
    @JsonProperty("footerHeight")
    public com.hp.ext.types.protocol.Unsigned16 getFooterHeight() {
        return footerHeight;
    }

    @JsonProperty("footerHeight")
    public void setFooterHeight(com.hp.ext.types.protocol.Unsigned16 footerHeight) {
        this.footerHeight = footerHeight;
    }
    @JsonProperty("hardKeyboardType")
    public com.hp.ext.types.application.HardKeyboardType getHardKeyboardType() {
        return hardKeyboardType;
    }

    @JsonProperty("hardKeyboardType")
    public void setHardKeyboardType(com.hp.ext.types.application.HardKeyboardType hardKeyboardType) {
        this.hardKeyboardType = hardKeyboardType;
    }
    @JsonProperty("hasHardBackKey")
    public Boolean getHasHardBackKey() {
        return hasHardBackKey;
    }

    @JsonProperty("hasHardBackKey")
    public void setHasHardBackKey(Boolean hasHardBackKey) {
        this.hasHardBackKey = hasHardBackKey;
    }
    @JsonProperty("hasHardHomeKey")
    public Boolean getHasHardHomeKey() {
        return hasHardHomeKey;
    }

    @JsonProperty("hasHardHomeKey")
    public void setHasHardHomeKey(Boolean hasHardHomeKey) {
        this.hasHardHomeKey = hasHardHomeKey;
    }
    @JsonProperty("headerHeight")
    public com.hp.ext.types.protocol.Unsigned16 getHeaderHeight() {
        return headerHeight;
    }

    @JsonProperty("headerHeight")
    public void setHeaderHeight(com.hp.ext.types.protocol.Unsigned16 headerHeight) {
        this.headerHeight = headerHeight;
    }
    @JsonProperty("nativeTheme")
    public String getNativeTheme() {
        return nativeTheme;
    }

    @JsonProperty("nativeTheme")
    public void setNativeTheme(String nativeTheme) {
        this.nativeTheme = nativeTheme;
    }
    @JsonProperty("softKeyboardTypes")
    public java.util.List<com.hp.ext.types.application.SoftKeyboardType> getSoftKeyboardTypes() {
        return softKeyboardTypes;
    }

    @JsonProperty("softKeyboardTypes")
    public void setSoftKeyboardTypes(java.util.List<com.hp.ext.types.application.SoftKeyboardType> softKeyboardTypes) {
        this.softKeyboardTypes = softKeyboardTypes;
    }
    public UserInterfaceAttributes()
    {
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "userInterfaceAttributes";
        typeGUN = "com.hp.ext.types.application.version.1.type.userInterfaceAttributes";
    }
}
