/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.application;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * This type defines the target for a web application to be loaded in the device's embedded browser.
 */
public class WebApplicationTarget extends E2Type
{
    private com.hp.ext.types.application.WebApplicationTargetIntent applicationIntent;
    private com.hp.ext.types.target.HttpAuthorization authorization;
    private com.hp.ext.types.target.Headers headers;
    private com.hp.ext.types.target.HttpStyleHostCommon_Host_Binding host;
    private com.hp.ext.types.target.HttpStyleClientCommon_Path_Binding path;
    private com.hp.ext.types.target.RetryBehavior retry;
    private String scheme;
    
    @JsonProperty("applicationIntent")
    public com.hp.ext.types.application.WebApplicationTargetIntent getApplicationIntent() {
        return applicationIntent;
    }

    @JsonProperty("applicationIntent")
    public void setApplicationIntent(com.hp.ext.types.application.WebApplicationTargetIntent applicationIntent) {
        this.applicationIntent = applicationIntent;
    }
    @JsonProperty("authorization")
    public com.hp.ext.types.target.HttpAuthorization getAuthorization() {
        return authorization;
    }

    @JsonProperty("authorization")
    public void setAuthorization(com.hp.ext.types.target.HttpAuthorization authorization) {
        this.authorization = authorization;
    }
    @JsonProperty("headers")
    public com.hp.ext.types.target.Headers getHeaders() {
        return headers;
    }

    @JsonProperty("headers")
    public void setHeaders(com.hp.ext.types.target.Headers headers) {
        this.headers = headers;
    }
    @JsonProperty("host")
    public com.hp.ext.types.target.HttpStyleHostCommon_Host_Binding getHost() {
        return host;
    }

    @JsonProperty("host")
    public void setHost(com.hp.ext.types.target.HttpStyleHostCommon_Host_Binding host) {
        this.host = host;
    }
    @JsonProperty("path")
    public com.hp.ext.types.target.HttpStyleClientCommon_Path_Binding getPath() {
        return path;
    }

    @JsonProperty("path")
    public void setPath(com.hp.ext.types.target.HttpStyleClientCommon_Path_Binding path) {
        this.path = path;
    }
    @JsonProperty("retry")
    public com.hp.ext.types.target.RetryBehavior getRetry() {
        return retry;
    }

    @JsonProperty("retry")
    public void setRetry(com.hp.ext.types.target.RetryBehavior retry) {
        this.retry = retry;
    }
    @JsonProperty("scheme")
    public String getScheme() {
        return scheme;
    }

    @JsonProperty("scheme")
    public void setScheme(String scheme) {
        this.scheme = scheme;
    }
    public WebApplicationTarget()
    {
        majorVersion = ApplicationTypesManifest.getInstance().MajorVersion;
        typeName = "webApplicationTarget";
        typeGUN = "com.hp.ext.types.application.version.1.type.webApplicationTarget";
    }
}
