/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.webHook;

import com.hp.ext.types.common.E2Type;
import com.hp.ext.types.common.IE2Polymorph;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;

/**
 * The solution hosted web hook target.
 */
@JsonSerialize(using = WebHookTarget.Serializer.class)
public class WebHookTarget extends E2Type implements IE2Polymorph
{
    private Object polymorphInstance;

    public Object getInstance() {
        return polymorphInstance;
    }

    public void setInstance(Object o) {
        polymorphInstance = o;
    }

    public boolean isWorkpath()
    { 
        return polymorphInstance instanceof com.hp.ext.service.webHook.WorkpathWebHookTarget;
    }

    public void setWorkpath(com.hp.ext.service.webHook.WorkpathWebHookTarget value) {
        polymorphInstance = value;
    }

    public com.hp.ext.service.webHook.WorkpathWebHookTarget getWorkpath() {
        return (com.hp.ext.service.webHook.WorkpathWebHookTarget)polymorphInstance;
    }

    public WebHookTarget()
    {
        this(null);
    }

    public WebHookTarget(Object obj)
    {
        polymorphInstance = obj;
        majorVersion = WebHookManifest.getInstance().MajorVersion;
        typeName = "webHookTarget";
        typeGUN = "com.hp.ext.service.webHook.version.1.type.webHookTarget";
    }

    public static class Serializer extends StdSerializer<WebHookTarget> {
    
        public Serializer() {
            this(null);
        }
      
        public Serializer(Class<WebHookTarget> t) {
            super(t);
        }
    
        @Override
        public void serialize(WebHookTarget value, JsonGenerator jgen, SerializerProvider provider) 
          throws IOException, JsonProcessingException {
     
            jgen.writeStartObject();
            if (value.isWorkpath()) {
                jgen.writeObjectField("workpath", value.getWorkpath());
            }
            jgen.writeEndObject();
        }
    }
};
