/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.webHook;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A workpath solution web hook target.
 */
public class WorkpathWebHookTarget extends E2Type
{
    private String absolutePath;
    private com.hp.ext.types.target.AndroidPackageName _package;
    
    @JsonProperty("absolutePath")
    public String getAbsolutePath() {
        return absolutePath;
    }

    @JsonProperty("absolutePath")
    public void setAbsolutePath(String absolutePath) {
        this.absolutePath = absolutePath;
    }
    @JsonProperty("package")
    public com.hp.ext.types.target.AndroidPackageName getPackage() {
        return _package;
    }

    @JsonProperty("package")
    public void setPackage(com.hp.ext.types.target.AndroidPackageName _package) {
        this._package = _package;
    }
    public WorkpathWebHookTarget()
    {
        majorVersion = WebHookManifest.getInstance().MajorVersion;
        typeName = "workpathWebHookTarget";
        typeGUN = "com.hp.ext.service.webHook.version.1.type.workpathWebHookTarget";
    }
}
