/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.media;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Enumeration of media families.
 */
@JsonDeserialize(using = MediaFamilyId.Deserializer.class)
public class MediaFamilyId extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * Adhesive
    */
    public static MediaFamilyId MfAdhesive = new MediaFamilyId("mfAdhesive");
    /**
     * Backlit
    */
    public static MediaFamilyId MfBacklit = new MediaFamilyId("mfBacklit");
    /**
     * Banner and Sign
    */
    public static MediaFamilyId MfBannerAndSign = new MediaFamilyId("mfBannerAndSign");
    /**
     * Bond and Coated
    */
    public static MediaFamilyId MfBondAndCoated = new MediaFamilyId("mfBondAndCoated");
    /**
     * Blueprint
    */
    public static MediaFamilyId MfBlueprint = new MediaFamilyId("mfBlueprint");
    /**
     * Canvas
    */
    public static MediaFamilyId MfCanvas = new MediaFamilyId("mfCanvas");
    /**
     * Custom
    */
    public static MediaFamilyId MfCustom = new MediaFamilyId("mfCustom");
    /**
     * Film
    */
    public static MediaFamilyId MfFilm = new MediaFamilyId("mfFilm");
    /**
     * Heat Transfer
    */
    public static MediaFamilyId MfHeatTransfer = new MediaFamilyId("mfHeatTransfer");
    /**
     * Plain
    */
    public static MediaFamilyId MfPlain = new MediaFamilyId("mfPlain");
    /**
     * Photo
    */
    public static MediaFamilyId MfPhoto = new MediaFamilyId("mfPhoto");
    /**
     * Technical
    */
    public static MediaFamilyId MfTechnical = new MediaFamilyId("mfTechnical");
    /**
     * Textile
    */
    public static MediaFamilyId MfTextile = new MediaFamilyId("mfTextile");
    /**
     * Wall Covering
    */
    public static MediaFamilyId MfWallcovering = new MediaFamilyId("mfWallcovering");
    /**
     * Fine Art
    */
    public static MediaFamilyId MfFineArt = new MediaFamilyId("mfFineArt");
    /**
     * Proofing
    */
    public static MediaFamilyId MfProofing = new MediaFamilyId("mfProofing");
    /**
     * Fabric
    */
    public static MediaFamilyId MfFabric = new MediaFamilyId("mfFabric");
    /**
     * Other Inkjet Media
    */
    public static MediaFamilyId MfOtherInkjetMedia = new MediaFamilyId("mfOtherInkjetMedia");
    /**
     * HP Extended Media
    */
    public static MediaFamilyId MfHpExtendedMedia = new MediaFamilyId("mfHpExtendedMedia");
    /**
     * Family
    */
    public static MediaFamilyId MfFamily = new MediaFamilyId("mfFamily");
    /**
     * PVC Banner
    */
    public static MediaFamilyId MfPvcBanner = new MediaFamilyId("mfPvcBanner");
    /**
     * PP/PE Synthetics
    */
    public static MediaFamilyId MfPpPeSynthetics = new MediaFamilyId("mfPpPeSynthetics");
    /**
     * PET Synthetics
    */
    public static MediaFamilyId MfPetSynthetics = new MediaFamilyId("mfPetSynthetics");
    /**
     * Any
    */
    public static MediaFamilyId MfAny = new MediaFamilyId("mfAny");
    /**
     * Poster
    */
    public static MediaFamilyId MfPoster = new MediaFamilyId("mfPoster");
    /**
     * Folding Paper (Advanced)
    */
    public static MediaFamilyId MfAdvancedFoldingPaper = new MediaFamilyId("mfAdvancedFoldingPaper");
    /**
     * Unknown
    */
    public static MediaFamilyId MfUknown = new MediaFamilyId("mfUknown");

    protected static Hashtable<String, MediaFamilyId> definitions;
    
    static {
        definitions = new Hashtable<String, MediaFamilyId> ();
        definitions.put(MfAdhesive.getValue(), MfAdhesive);
        definitions.put(MfBacklit.getValue(), MfBacklit);
        definitions.put(MfBannerAndSign.getValue(), MfBannerAndSign);
        definitions.put(MfBondAndCoated.getValue(), MfBondAndCoated);
        definitions.put(MfBlueprint.getValue(), MfBlueprint);
        definitions.put(MfCanvas.getValue(), MfCanvas);
        definitions.put(MfCustom.getValue(), MfCustom);
        definitions.put(MfFilm.getValue(), MfFilm);
        definitions.put(MfHeatTransfer.getValue(), MfHeatTransfer);
        definitions.put(MfPlain.getValue(), MfPlain);
        definitions.put(MfPhoto.getValue(), MfPhoto);
        definitions.put(MfTechnical.getValue(), MfTechnical);
        definitions.put(MfTextile.getValue(), MfTextile);
        definitions.put(MfWallcovering.getValue(), MfWallcovering);
        definitions.put(MfFineArt.getValue(), MfFineArt);
        definitions.put(MfProofing.getValue(), MfProofing);
        definitions.put(MfFabric.getValue(), MfFabric);
        definitions.put(MfOtherInkjetMedia.getValue(), MfOtherInkjetMedia);
        definitions.put(MfHpExtendedMedia.getValue(), MfHpExtendedMedia);
        definitions.put(MfFamily.getValue(), MfFamily);
        definitions.put(MfPvcBanner.getValue(), MfPvcBanner);
        definitions.put(MfPpPeSynthetics.getValue(), MfPpPeSynthetics);
        definitions.put(MfPetSynthetics.getValue(), MfPetSynthetics);
        definitions.put(MfAny.getValue(), MfAny);
        definitions.put(MfPoster.getValue(), MfPoster);
        definitions.put(MfAdvancedFoldingPaper.getValue(), MfAdvancedFoldingPaper);
        definitions.put(MfUknown.getValue(), MfUknown);
    }

    private MediaFamilyId() {
        this(null);
    }

    private MediaFamilyId(String name) {
        this(name, name);
    }

    private MediaFamilyId(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = MediaTypesManifest.getInstance().MajorVersion;
        typeName = "mediaFamilyId";
        typeGUN = "com.hp.ext.types.media.version.1.type.mediaFamilyId";
    }

    public static MediaFamilyId Parse(String name)
    {
        MediaFamilyId instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  MediaFamilyId(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<MediaFamilyId> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public MediaFamilyId deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return MediaFamilyId.Parse(node.asText());
        }
    }
}
