/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.media;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Enumeration of media outputs.
 */
@JsonDeserialize(using = MediaOutputId.Deserializer.class)
public class MediaOutputId extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * Accessory bin
    */
    public static MediaOutputId MoAccessory = new MediaOutputId("moAccessory");
    /**
     * ADF output bin
    */
    public static MediaOutputId MoAdf = new MediaOutputId("moAdf");
    /**
     * Printer selected output bin
    */
    public static MediaOutputId MoAuto = new MediaOutputId("moAuto");
    /**
     * Booklet bin
    */
    public static MediaOutputId MoBooklet = new MediaOutputId("moBooklet");
    /**
     * Default bin
    */
    public static MediaOutputId MoDefault = new MediaOutputId("moDefault");
    /**
     * Document feeder output bin
    */
    public static MediaOutputId MoDocumentFeeder = new MediaOutputId("moDocumentFeeder");
    /**
     * External bin
    */
    public static MediaOutputId MoExternal = new MediaOutputId("moExternal");
    /**
     * Face down bin
    */
    public static MediaOutputId MoFaceDown = new MediaOutputId("moFaceDown");
    /**
     * Face down bin correct order
    */
    public static MediaOutputId MoFaceDownCorrectOrder = new MediaOutputId("moFaceDownCorrectOrder");
    /**
     * Face up bin
    */
    public static MediaOutputId MoFaceUp = new MediaOutputId("moFaceUp");
    /**
     * Face up bin with the straightest path
    */
    public static MediaOutputId MoFaceUpStraightestPath = new MediaOutputId("moFaceUpStraightestPath");
    /**
     * Fax output bin
    */
    public static MediaOutputId MoFax = new MediaOutputId("moFax");
    /**
     * Folded output bin
    */
    public static MediaOutputId MoFolded = new MediaOutputId("moFolded");
    /**
     * Left bin
    */
    public static MediaOutputId MoLeft = new MediaOutputId("moLeft");
    /**
     * Left bin with the straightest path
    */
    public static MediaOutputId MoLeftStraightestPath = new MediaOutputId("moLeftStraightestPath");
    /**
     * Lower bin
    */
    public static MediaOutputId MoLower = new MediaOutputId("moLower");
    /**
     * Lower booklet bin
    */
    public static MediaOutputId MoLowerBooklet = new MediaOutputId("moLowerBooklet");
    /**
     * Lower left bin
    */
    public static MediaOutputId MoLowerLeft = new MediaOutputId("moLowerLeft");
    /**
     * Lower left highest capacity bin
    */
    public static MediaOutputId MoLowerLeftHighestCapacity = new MediaOutputId("moLowerLeftHighestCapacity");
    /**
     * Lower stacker bin
    */
    public static MediaOutputId MoLowerStacker = new MediaOutputId("moLowerStacker");
    /**
     * Main copier bin
    */
    public static MediaOutputId MoMainCopier = new MediaOutputId("moMainCopier");
    /**
     * Middle bin
    */
    public static MediaOutputId MoMiddle = new MediaOutputId("moMiddle");
    /**
     * Middle left bin
    */
    public static MediaOutputId MoMiddleLeft = new MediaOutputId("moMiddleLeft");
    /**
     * Output bin 1
    */
    public static MediaOutputId MoOutputBin1 = new MediaOutputId("moOutputBin1");
    /**
     * Output bin 2
    */
    public static MediaOutputId MoOutputBin2 = new MediaOutputId("moOutputBin2");
    /**
     * Output bin 3
    */
    public static MediaOutputId MoOutputBin3 = new MediaOutputId("moOutputBin3");
    /**
     * Output bin 4
    */
    public static MediaOutputId MoOutputBin4 = new MediaOutputId("moOutputBin4");
    /**
     * Output bin 5
    */
    public static MediaOutputId MoOutputBin5 = new MediaOutputId("moOutputBin5");
    /**
     * Output bin 6
    */
    public static MediaOutputId MoOutputBin6 = new MediaOutputId("moOutputBin6");
    /**
     * Output bin 7
    */
    public static MediaOutputId MoOutputBin7 = new MediaOutputId("moOutputBin7");
    /**
     * Output bin 8
    */
    public static MediaOutputId MoOutputBin8 = new MediaOutputId("moOutputBin8");
    /**
     * Output bin 9
    */
    public static MediaOutputId MoOutputBin9 = new MediaOutputId("moOutputBin9");
    /**
     * Output bin 10
    */
    public static MediaOutputId MoOutputBin10 = new MediaOutputId("moOutputBin10");
    /**
     * Output bin 11
    */
    public static MediaOutputId MoOutputBin11 = new MediaOutputId("moOutputBin11");
    /**
     * Output bin 12
    */
    public static MediaOutputId MoOutputBin12 = new MediaOutputId("moOutputBin12");
    /**
     * Output bin 13
    */
    public static MediaOutputId MoOutputBin13 = new MediaOutputId("moOutputBin13");
    /**
     * Output bin 14
    */
    public static MediaOutputId MoOutputBin14 = new MediaOutputId("moOutputBin14");
    /**
     * Output bin 15
    */
    public static MediaOutputId MoOutputBin15 = new MediaOutputId("moOutputBin15");
    /**
     * Output bin 16
    */
    public static MediaOutputId MoOutputBin16 = new MediaOutputId("moOutputBin16");
    /**
     * Rear bin
    */
    public static MediaOutputId MoRear = new MediaOutputId("moRear");
    /**
     * Rear face up bin
    */
    public static MediaOutputId MoRearFaceUp = new MediaOutputId("moRearFaceUp");
    /**
     * Rear bin with the straightest path
    */
    public static MediaOutputId MoRearStraightestPath = new MediaOutputId("moRearStraightestPath");
    /**
     * Stacker
    */
    public static MediaOutputId MoStacker = new MediaOutputId("moStacker");
    /**
     * Standard bin
    */
    public static MediaOutputId MoStandard = new MediaOutputId("moStandard");
    /**
     * Standard bin correct order
    */
    public static MediaOutputId MoStandardCorrectOrder = new MediaOutputId("moStandardCorrectOrder");
    /**
     * Standard top bin
    */
    public static MediaOutputId MoStandardTop = new MediaOutputId("moStandardTop");
    /**
     * Top bin
    */
    public static MediaOutputId MoTop = new MediaOutputId("moTop");
    /**
     * Upper bin
    */
    public static MediaOutputId MoUpper = new MediaOutputId("moUpper");
    /**
     * Upper face up bin
    */
    public static MediaOutputId MoUpperFaceUp = new MediaOutputId("moUpperFaceUp");
    /**
     * Upper left bin
    */
    public static MediaOutputId MoUpperLeft = new MediaOutputId("moUpperLeft");
    /**
     * Upper left bins
    */
    public static MediaOutputId MoUpperLeftBins = new MediaOutputId("moUpperLeftBins");
    /**
     * Upper left bin with the straightest path
    */
    public static MediaOutputId MoUpperLeftStraightestPath = new MediaOutputId("moUpperLeftStraightestPath");
    /**
     * Bins 1 to 3 (virtual bin)
    */
    public static MediaOutputId MoVirtualBins1To3 = new MediaOutputId("moVirtualBins1To3");
    /**
     * Bins 1 to 5 (virtual bin)
    */
    public static MediaOutputId MoVirtualBins1To5 = new MediaOutputId("moVirtualBins1To5");
    /**
     * Bins 1 to 8 (virtual bin)
    */
    public static MediaOutputId MoVirtualBins1To8 = new MediaOutputId("moVirtualBins1To8");
    /**
     * Bins 1 to 10 (virtual bin)
    */
    public static MediaOutputId MoVirtualBins1To10 = new MediaOutputId("moVirtualBins1To10");
    /**
     * Bins 2 to 8 (virtual bin)
    */
    public static MediaOutputId MoVirtualBins2To8 = new MediaOutputId("moVirtualBins2To8");
    /**
     * Finisher Bins (virtual bin)
    */
    public static MediaOutputId MoVirtualFinisherBins = new MediaOutputId("moVirtualFinisherBins");
    /**
     * Left Bins (virtual bin)
    */
    public static MediaOutputId MoVirtualLeftBins = new MediaOutputId("moVirtualLeftBins");
    /**
     * An output bin not represented by another value in this enumeration.
    */
    public static MediaOutputId MoOther = new MediaOutputId("moOther");
    /**
     * An alternate output bin
    */
    public static MediaOutputId MoAlternate = new MediaOutputId("moAlternate");
    /**
     * The bottom output bin
    */
    public static MediaOutputId MoBottom = new MediaOutputId("moBottom");
    /**
     * The center output bin
    */
    public static MediaOutputId MoCenter = new MediaOutputId("moCenter");
    /**
     * A collator output bin
    */
    public static MediaOutputId MoCollator = new MediaOutputId("moCollator");
    /**
     * A duplexer output bin
    */
    public static MediaOutputId MoDuplexer = new MediaOutputId("moDuplexer");
    /**
     * Engine optional bin 1
    */
    public static MediaOutputId MoEngineOptionalBin1 = new MediaOutputId("moEngineOptionalBin1");
    /**
     * Large capacity bin
    */
    public static MediaOutputId MoLargeCapacity = new MediaOutputId("moLargeCapacity");
    /**
     * A custom mailbox bin
    */
    public static MediaOutputId MoMyMailbox = new MediaOutputId("moMyMailbox");
    /**
     * The righ output bin
    */
    public static MediaOutputId MoRight = new MediaOutputId("moRight");
    /**
     * The side output bin
    */
    public static MediaOutputId MoSide = new MediaOutputId("moSide");
    /**
     * Stacker bin 2
    */
    public static MediaOutputId MoStacker2 = new MediaOutputId("moStacker2");
    /**
     * Stacker bin 3
    */
    public static MediaOutputId MoStacker3 = new MediaOutputId("moStacker3");
    /**
     * Stacker bin 4
    */
    public static MediaOutputId MoStacker4 = new MediaOutputId("moStacker4");
    /**
     * Stacker face down
    */
    public static MediaOutputId MoStackerFacedown = new MediaOutputId("moStackerFacedown");
    /**
     * Stacker face up
    */
    public static MediaOutputId MoStackerFaceUp = new MediaOutputId("moStackerFaceUp");
    /**
     * Stacker staples
    */
    public static MediaOutputId MoStackerStaples = new MediaOutputId("moStackerStaples");
    /**
     * Universal output bin
    */
    public static MediaOutputId MoUniversalOutputBin = new MediaOutputId("moUniversalOutputBin");
    /**
     * Stapler
    */
    public static MediaOutputId MoStapler = new MediaOutputId("moStapler");
    /**
     * Folder
    */
    public static MediaOutputId MoFolder = new MediaOutputId("moFolder");
    /**
     * Folder 2
    */
    public static MediaOutputId MoFolder2 = new MediaOutputId("moFolder2");
    /**
     * Folder 3
    */
    public static MediaOutputId MoFolder3 = new MediaOutputId("moFolder3");
    /**
     * Folder 4
    */
    public static MediaOutputId MoFolder4 = new MediaOutputId("moFolder4");
    /**
     * Accessory stacker
    */
    public static MediaOutputId MoAccessoryStacker = new MediaOutputId("moAccessoryStacker");
    /**
     * Generic accessory
    */
    public static MediaOutputId MoGenericAccessory = new MediaOutputId("moGenericAccessory");
    /**
     * Take-up reel
    */
    public static MediaOutputId MoTakeUpReel = new MediaOutputId("moTakeUpReel");
    /**
     * Horizontal cutter
    */
    public static MediaOutputId MoHorizontalCutter = new MediaOutputId("moHorizontalCutter");
    /**
     * Vertical cutter
    */
    public static MediaOutputId MoVerticalCutter = new MediaOutputId("moVerticalCutter");
    /**
     * Generic output bin
    */
    public static MediaOutputId MoBin = new MediaOutputId("moBin");

    protected static Hashtable<String, MediaOutputId> definitions;
    
    static {
        definitions = new Hashtable<String, MediaOutputId> ();
        definitions.put(MoAccessory.getValue(), MoAccessory);
        definitions.put(MoAdf.getValue(), MoAdf);
        definitions.put(MoAuto.getValue(), MoAuto);
        definitions.put(MoBooklet.getValue(), MoBooklet);
        definitions.put(MoDefault.getValue(), MoDefault);
        definitions.put(MoDocumentFeeder.getValue(), MoDocumentFeeder);
        definitions.put(MoExternal.getValue(), MoExternal);
        definitions.put(MoFaceDown.getValue(), MoFaceDown);
        definitions.put(MoFaceDownCorrectOrder.getValue(), MoFaceDownCorrectOrder);
        definitions.put(MoFaceUp.getValue(), MoFaceUp);
        definitions.put(MoFaceUpStraightestPath.getValue(), MoFaceUpStraightestPath);
        definitions.put(MoFax.getValue(), MoFax);
        definitions.put(MoFolded.getValue(), MoFolded);
        definitions.put(MoLeft.getValue(), MoLeft);
        definitions.put(MoLeftStraightestPath.getValue(), MoLeftStraightestPath);
        definitions.put(MoLower.getValue(), MoLower);
        definitions.put(MoLowerBooklet.getValue(), MoLowerBooklet);
        definitions.put(MoLowerLeft.getValue(), MoLowerLeft);
        definitions.put(MoLowerLeftHighestCapacity.getValue(), MoLowerLeftHighestCapacity);
        definitions.put(MoLowerStacker.getValue(), MoLowerStacker);
        definitions.put(MoMainCopier.getValue(), MoMainCopier);
        definitions.put(MoMiddle.getValue(), MoMiddle);
        definitions.put(MoMiddleLeft.getValue(), MoMiddleLeft);
        definitions.put(MoOutputBin1.getValue(), MoOutputBin1);
        definitions.put(MoOutputBin2.getValue(), MoOutputBin2);
        definitions.put(MoOutputBin3.getValue(), MoOutputBin3);
        definitions.put(MoOutputBin4.getValue(), MoOutputBin4);
        definitions.put(MoOutputBin5.getValue(), MoOutputBin5);
        definitions.put(MoOutputBin6.getValue(), MoOutputBin6);
        definitions.put(MoOutputBin7.getValue(), MoOutputBin7);
        definitions.put(MoOutputBin8.getValue(), MoOutputBin8);
        definitions.put(MoOutputBin9.getValue(), MoOutputBin9);
        definitions.put(MoOutputBin10.getValue(), MoOutputBin10);
        definitions.put(MoOutputBin11.getValue(), MoOutputBin11);
        definitions.put(MoOutputBin12.getValue(), MoOutputBin12);
        definitions.put(MoOutputBin13.getValue(), MoOutputBin13);
        definitions.put(MoOutputBin14.getValue(), MoOutputBin14);
        definitions.put(MoOutputBin15.getValue(), MoOutputBin15);
        definitions.put(MoOutputBin16.getValue(), MoOutputBin16);
        definitions.put(MoRear.getValue(), MoRear);
        definitions.put(MoRearFaceUp.getValue(), MoRearFaceUp);
        definitions.put(MoRearStraightestPath.getValue(), MoRearStraightestPath);
        definitions.put(MoStacker.getValue(), MoStacker);
        definitions.put(MoStandard.getValue(), MoStandard);
        definitions.put(MoStandardCorrectOrder.getValue(), MoStandardCorrectOrder);
        definitions.put(MoStandardTop.getValue(), MoStandardTop);
        definitions.put(MoTop.getValue(), MoTop);
        definitions.put(MoUpper.getValue(), MoUpper);
        definitions.put(MoUpperFaceUp.getValue(), MoUpperFaceUp);
        definitions.put(MoUpperLeft.getValue(), MoUpperLeft);
        definitions.put(MoUpperLeftBins.getValue(), MoUpperLeftBins);
        definitions.put(MoUpperLeftStraightestPath.getValue(), MoUpperLeftStraightestPath);
        definitions.put(MoVirtualBins1To3.getValue(), MoVirtualBins1To3);
        definitions.put(MoVirtualBins1To5.getValue(), MoVirtualBins1To5);
        definitions.put(MoVirtualBins1To8.getValue(), MoVirtualBins1To8);
        definitions.put(MoVirtualBins1To10.getValue(), MoVirtualBins1To10);
        definitions.put(MoVirtualBins2To8.getValue(), MoVirtualBins2To8);
        definitions.put(MoVirtualFinisherBins.getValue(), MoVirtualFinisherBins);
        definitions.put(MoVirtualLeftBins.getValue(), MoVirtualLeftBins);
        definitions.put(MoOther.getValue(), MoOther);
        definitions.put(MoAlternate.getValue(), MoAlternate);
        definitions.put(MoBottom.getValue(), MoBottom);
        definitions.put(MoCenter.getValue(), MoCenter);
        definitions.put(MoCollator.getValue(), MoCollator);
        definitions.put(MoDuplexer.getValue(), MoDuplexer);
        definitions.put(MoEngineOptionalBin1.getValue(), MoEngineOptionalBin1);
        definitions.put(MoLargeCapacity.getValue(), MoLargeCapacity);
        definitions.put(MoMyMailbox.getValue(), MoMyMailbox);
        definitions.put(MoRight.getValue(), MoRight);
        definitions.put(MoSide.getValue(), MoSide);
        definitions.put(MoStacker2.getValue(), MoStacker2);
        definitions.put(MoStacker3.getValue(), MoStacker3);
        definitions.put(MoStacker4.getValue(), MoStacker4);
        definitions.put(MoStackerFacedown.getValue(), MoStackerFacedown);
        definitions.put(MoStackerFaceUp.getValue(), MoStackerFaceUp);
        definitions.put(MoStackerStaples.getValue(), MoStackerStaples);
        definitions.put(MoUniversalOutputBin.getValue(), MoUniversalOutputBin);
        definitions.put(MoStapler.getValue(), MoStapler);
        definitions.put(MoFolder.getValue(), MoFolder);
        definitions.put(MoFolder2.getValue(), MoFolder2);
        definitions.put(MoFolder3.getValue(), MoFolder3);
        definitions.put(MoFolder4.getValue(), MoFolder4);
        definitions.put(MoAccessoryStacker.getValue(), MoAccessoryStacker);
        definitions.put(MoGenericAccessory.getValue(), MoGenericAccessory);
        definitions.put(MoTakeUpReel.getValue(), MoTakeUpReel);
        definitions.put(MoHorizontalCutter.getValue(), MoHorizontalCutter);
        definitions.put(MoVerticalCutter.getValue(), MoVerticalCutter);
        definitions.put(MoBin.getValue(), MoBin);
    }

    private MediaOutputId() {
        this(null);
    }

    private MediaOutputId(String name) {
        this(name, name);
    }

    private MediaOutputId(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = MediaTypesManifest.getInstance().MajorVersion;
        typeName = "mediaOutputId";
        typeGUN = "com.hp.ext.types.media.version.1.type.mediaOutputId";
    }

    public static MediaOutputId Parse(String name)
    {
        MediaOutputId instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  MediaOutputId(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<MediaOutputId> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public MediaOutputId deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return MediaOutputId.Parse(node.asText());
        }
    }
}
