/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * An enumeration of defined solution archive types
 */
@JsonDeserialize(using = ArchiveType.Deserializer.class)
public class ArchiveType extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * Identifies a Solution archive
    */
    public static ArchiveType AtSolutionArchive = new ArchiveType("atSolutionArchive");
    /**
     * Identifies a Solution-Modification archive
    */
    public static ArchiveType AtModificationArchive = new ArchiveType("atModificationArchive");
    /**
     * Identifies a remote archive target hosted by a deployment server
    */
    public static ArchiveType AtRemoteArchive = new ArchiveType("atRemoteArchive");

    protected static Hashtable<String, ArchiveType> definitions;
    
    static {
        definitions = new Hashtable<String, ArchiveType> ();
        definitions.put(AtSolutionArchive.getValue(), AtSolutionArchive);
        definitions.put(AtModificationArchive.getValue(), AtModificationArchive);
        definitions.put(AtRemoteArchive.getValue(), AtRemoteArchive);
    }

    private ArchiveType() {
        this(null);
    }

    private ArchiveType(String name) {
        this(name, name);
    }

    private ArchiveType(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "archiveType";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.archiveType";
    }

    public static ArchiveType Parse(String name)
    {
        ArchiveType instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  ArchiveType(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<ArchiveType> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public ArchiveType deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return ArchiveType.Parse(node.asText());
        }
    }
}
