/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The notification payload for a certificate authority addition/deletion
 */
public class CertificateAuthoritiesNotificationPayload extends E2Type
{
    private com.hp.ext.types.solutionManager.CertificateContent certificate;
    
    @JsonProperty("certificate")
    public com.hp.ext.types.solutionManager.CertificateContent getCertificate() {
        return certificate;
    }

    @JsonProperty("certificate")
    public void setCertificate(com.hp.ext.types.solutionManager.CertificateContent certificate) {
        this.certificate = certificate;
    }
    public CertificateAuthoritiesNotificationPayload()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "certificateAuthoritiesNotificationPayload";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.certificateAuthoritiesNotificationPayload";
    }
}
