/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Used within the solution context to define an individual item
 */
public class ContextDataWritable extends E2Type
{
    private com.hp.ext.types.solutionManager.ContextKey key;
    private com.hp.ext.types.solutionManager.ContextValue value;
    
    @JsonProperty("key")
    public com.hp.ext.types.solutionManager.ContextKey getKey() {
        return key;
    }

    @JsonProperty("key")
    public void setKey(com.hp.ext.types.solutionManager.ContextKey key) {
        this.key = key;
    }
    @JsonProperty("value")
    public com.hp.ext.types.solutionManager.ContextValue getValue() {
        return value;
    }

    @JsonProperty("value")
    public void setValue(com.hp.ext.types.solutionManager.ContextValue value) {
        this.value = value;
    }
    public ContextDataWritable()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "contextDataWritable";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.contextDataWritable";
    }
}
