/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The notification payload for a completed installer operation.
 */
public class InstallerOperationNotificationPayload extends E2Type
{
    private com.hp.ext.types.solutionManager.ArchiveType archiveType;
    private String completedTimestamp;
    private java.util.UUID modificationId;
    private java.util.UUID operationId;
    private com.hp.ext.types.solutionManager.InstallerOperationType operationType;
    private com.hp.ext.types.agent.SolutionId solutionId;
    
    @JsonProperty("archiveType")
    public com.hp.ext.types.solutionManager.ArchiveType getArchiveType() {
        return archiveType;
    }

    @JsonProperty("archiveType")
    public void setArchiveType(com.hp.ext.types.solutionManager.ArchiveType archiveType) {
        this.archiveType = archiveType;
    }
    @JsonProperty("completedTimestamp")
    public String getCompletedTimestamp() {
        return completedTimestamp;
    }

    @JsonProperty("completedTimestamp")
    public void setCompletedTimestamp(String completedTimestamp) {
        this.completedTimestamp = completedTimestamp;
    }
    @JsonProperty("modificationId")
    public java.util.UUID getModificationId() {
        return modificationId;
    }

    @JsonProperty("modificationId")
    public void setModificationId(java.util.UUID modificationId) {
        this.modificationId = modificationId;
    }
    @JsonProperty("operationId")
    public java.util.UUID getOperationId() {
        return operationId;
    }

    @JsonProperty("operationId")
    public void setOperationId(java.util.UUID operationId) {
        this.operationId = operationId;
    }
    @JsonProperty("operationType")
    public com.hp.ext.types.solutionManager.InstallerOperationType getOperationType() {
        return operationType;
    }

    @JsonProperty("operationType")
    public void setOperationType(com.hp.ext.types.solutionManager.InstallerOperationType operationType) {
        this.operationType = operationType;
    }
    @JsonProperty("solutionId")
    public com.hp.ext.types.agent.SolutionId getSolutionId() {
        return solutionId;
    }

    @JsonProperty("solutionId")
    public void setSolutionId(com.hp.ext.types.agent.SolutionId solutionId) {
        this.solutionId = solutionId;
    }
    public InstallerOperationNotificationPayload()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "installerOperationNotificationPayload";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.installerOperationNotificationPayload";
    }
}
