/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Description of a installation event in detail
 */
public class InstallEventDetails extends E2Type
{
    private String eventCode;
    private String eventDescription;
    
    @JsonProperty("eventCode")
    public String getEventCode() {
        return eventCode;
    }

    @JsonProperty("eventCode")
    public void setEventCode(String eventCode) {
        this.eventCode = eventCode;
    }
    @JsonProperty("eventDescription")
    public String getEventDescription() {
        return eventDescription;
    }

    @JsonProperty("eventDescription")
    public void setEventDescription(String eventDescription) {
        this.eventDescription = eventDescription;
    }
    public InstallEventDetails()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "installEventDetails";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.installEventDetails";
    }
}
