/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * Installer operation states.
 */
@JsonDeserialize(using = InstallerOperationState.Deserializer.class)
public class InstallerOperationState extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * The operation is scheduled.
    */
    public static InstallerOperationState IosScheduled = new InstallerOperationState("iosScheduled");
    /**
     * The operation is currently in progress.
    */
    public static InstallerOperationState IosInProgress = new InstallerOperationState("iosInProgress");
    /**
     * The operation has not failed, but requires a reboot to complete.
    */
    public static InstallerOperationState IosRebootRequired = new InstallerOperationState("iosRebootRequired");
    /**
     * The operation was successfully completed.
    */
    public static InstallerOperationState IosSucceeded = new InstallerOperationState("iosSucceeded");
    /**
     * The operation failed.
    */
    public static InstallerOperationState IosFailed = new InstallerOperationState("iosFailed");
    /**
     * Portions of the operation did not succeed, but the solution is installed or uninstalled.
    */
    public static InstallerOperationState IosPartialSuccess = new InstallerOperationState("iosPartialSuccess");
    /**
     * The operation is currently prompting for permissions.
    */
    public static InstallerOperationState IosPermissionsPrompt = new InstallerOperationState("iosPermissionsPrompt");

    protected static Hashtable<String, InstallerOperationState> definitions;
    
    static {
        definitions = new Hashtable<String, InstallerOperationState> ();
        definitions.put(IosScheduled.getValue(), IosScheduled);
        definitions.put(IosInProgress.getValue(), IosInProgress);
        definitions.put(IosRebootRequired.getValue(), IosRebootRequired);
        definitions.put(IosSucceeded.getValue(), IosSucceeded);
        definitions.put(IosFailed.getValue(), IosFailed);
        definitions.put(IosPartialSuccess.getValue(), IosPartialSuccess);
        definitions.put(IosPermissionsPrompt.getValue(), IosPermissionsPrompt);
    }

    private InstallerOperationState() {
        this(null);
    }

    private InstallerOperationState(String name) {
        this(name, name);
    }

    private InstallerOperationState(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "installerOperationState";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.installerOperationState";
    }

    public static InstallerOperationState Parse(String name)
    {
        InstallerOperationState instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  InstallerOperationState(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<InstallerOperationState> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public InstallerOperationState deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return InstallerOperationState.Parse(node.asText());
        }
    }
}
