/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The vendor provided details describing the solution modification. Only shown for modification operations.
 */
public class ModificationDescription extends E2Type
{
    private String description;
    private String name;
    private String version;
    
    @JsonProperty("description")
    public String getDescription() {
        return description;
    }

    @JsonProperty("description")
    public void setDescription(String description) {
        this.description = description;
    }
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("name")
    public void setName(String name) {
        this.name = name;
    }
    @JsonProperty("version")
    public String getVersion() {
        return version;
    }

    @JsonProperty("version")
    public void setVersion(String version) {
        this.version = version;
    }
    public ModificationDescription()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "modificationDescription";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.modificationDescription";
    }
}
