/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.hp.ext.types.common.IE2Polymorph;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;

/**
 * The Modification Package object is a polymorph to support specific Workpath, OXPd, or Container settings
 */
@JsonSerialize(using = ModificationPackage.Serializer.class)
public class ModificationPackage extends E2Type implements IE2Polymorph
{
    private Object polymorphInstance;

    public Object getInstance() {
        return polymorphInstance;
    }

    public void setInstance(Object o) {
        polymorphInstance = o;
    }

    public boolean isWorkpathModificationPackage()
    { 
        return polymorphInstance instanceof com.hp.ext.types.solutionManager.WorkpathModificationPackage;
    }

    public void setWorkpathModificationPackage(com.hp.ext.types.solutionManager.WorkpathModificationPackage value) {
        polymorphInstance = value;
    }

    public com.hp.ext.types.solutionManager.WorkpathModificationPackage getWorkpathModificationPackage() {
        return (com.hp.ext.types.solutionManager.WorkpathModificationPackage)polymorphInstance;
    }
    public boolean isOxpdModificationPackage()
    { 
        return polymorphInstance instanceof com.hp.ext.types.solutionManager.OxpdModificationPackage;
    }

    public void setOxpdModificationPackage(com.hp.ext.types.solutionManager.OxpdModificationPackage value) {
        polymorphInstance = value;
    }

    public com.hp.ext.types.solutionManager.OxpdModificationPackage getOxpdModificationPackage() {
        return (com.hp.ext.types.solutionManager.OxpdModificationPackage)polymorphInstance;
    }
    public boolean isContainerModificationPackage()
    { 
        return polymorphInstance instanceof com.hp.ext.types.solutionManager.ContainerModificationPackage;
    }

    public void setContainerModificationPackage(com.hp.ext.types.solutionManager.ContainerModificationPackage value) {
        polymorphInstance = value;
    }

    public com.hp.ext.types.solutionManager.ContainerModificationPackage getContainerModificationPackage() {
        return (com.hp.ext.types.solutionManager.ContainerModificationPackage)polymorphInstance;
    }

    public ModificationPackage()
    {
        this(null);
    }

    public ModificationPackage(Object obj)
    {
        polymorphInstance = obj;
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "modificationPackage";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.modificationPackage";
    }

    public static class Serializer extends StdSerializer<ModificationPackage> {
    
        public Serializer() {
            this(null);
        }
      
        public Serializer(Class<ModificationPackage> t) {
            super(t);
        }
    
        @Override
        public void serialize(ModificationPackage value, JsonGenerator jgen, SerializerProvider provider) 
          throws IOException, JsonProcessingException {
     
            jgen.writeStartObject();
            if (value.isWorkpathModificationPackage()) {
                jgen.writeObjectField("workpathModificationPackage", value.getWorkpathModificationPackage());
            }
            if (value.isOxpdModificationPackage()) {
                jgen.writeObjectField("oxpdModificationPackage", value.getOxpdModificationPackage());
            }
            if (value.isContainerModificationPackage()) {
                jgen.writeObjectField("containerModificationPackage", value.getContainerModificationPackage());
            }
            jgen.writeEndObject();
        }
    }
};
