/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;

/**
 * The modification Package for an OXPd (2.0) solution
 */
public class OxpdModificationPackage extends E2Type
{
    
    public OxpdModificationPackage()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "oxpdModificationPackage";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.oxpdModificationPackage";
    }
}
