/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.hp.ext.types.common.IE2Polymorph;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;

/**
 * The Platform Package object is a polymorph to support specific platform package settings
 */
@JsonSerialize(using = PlatformPackage.Serializer.class)
public class PlatformPackage extends E2Type implements IE2Polymorph
{
    private Object polymorphInstance;

    public Object getInstance() {
        return polymorphInstance;
    }

    public void setInstance(Object o) {
        polymorphInstance = o;
    }

    public boolean isWorkpathPlatformPackage()
    { 
        return polymorphInstance instanceof com.hp.ext.types.solutionManager.WorkpathPlatformPackage;
    }

    public void setWorkpathPlatformPackage(com.hp.ext.types.solutionManager.WorkpathPlatformPackage value) {
        polymorphInstance = value;
    }

    public com.hp.ext.types.solutionManager.WorkpathPlatformPackage getWorkpathPlatformPackage() {
        return (com.hp.ext.types.solutionManager.WorkpathPlatformPackage)polymorphInstance;
    }
    public boolean isOxpdPlatformPackage()
    { 
        return polymorphInstance instanceof com.hp.ext.types.solutionManager.OxpdPlatformPackage;
    }

    public void setOxpdPlatformPackage(com.hp.ext.types.solutionManager.OxpdPlatformPackage value) {
        polymorphInstance = value;
    }

    public com.hp.ext.types.solutionManager.OxpdPlatformPackage getOxpdPlatformPackage() {
        return (com.hp.ext.types.solutionManager.OxpdPlatformPackage)polymorphInstance;
    }
    public boolean isContainerPlatformPackage()
    { 
        return polymorphInstance instanceof com.hp.ext.types.solutionManager.ContainerPlatformPackage;
    }

    public void setContainerPlatformPackage(com.hp.ext.types.solutionManager.ContainerPlatformPackage value) {
        polymorphInstance = value;
    }

    public com.hp.ext.types.solutionManager.ContainerPlatformPackage getContainerPlatformPackage() {
        return (com.hp.ext.types.solutionManager.ContainerPlatformPackage)polymorphInstance;
    }

    public PlatformPackage()
    {
        this(null);
    }

    public PlatformPackage(Object obj)
    {
        polymorphInstance = obj;
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "platformPackage";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.platformPackage";
    }

    public static class Serializer extends StdSerializer<PlatformPackage> {
    
        public Serializer() {
            this(null);
        }
      
        public Serializer(Class<PlatformPackage> t) {
            super(t);
        }
    
        @Override
        public void serialize(PlatformPackage value, JsonGenerator jgen, SerializerProvider provider) 
          throws IOException, JsonProcessingException {
     
            jgen.writeStartObject();
            if (value.isWorkpathPlatformPackage()) {
                jgen.writeObjectField("workpathPlatformPackage", value.getWorkpathPlatformPackage());
            }
            if (value.isOxpdPlatformPackage()) {
                jgen.writeObjectField("oxpdPlatformPackage", value.getOxpdPlatformPackage());
            }
            if (value.isContainerPlatformPackage()) {
                jgen.writeObjectField("containerPlatformPackage", value.getContainerPlatformPackage());
            }
            jgen.writeEndObject();
        }
    }
};
