/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The notification payload for a device shutdown notification.
 * <i>Note: if a notification includes a shutdown payload, configured retry logic for that 
 *     notification may not be observed. A fixed strategy for retries may be used instead.
 *     this ensures that device shutdown is not arbitrarily delayed by delivery of the notification.
 */
public class ShutdownNotificationPayload extends E2Type
{
    private com.hp.ext.types.solutionManager.ShutdownReason reason;
    
    @JsonProperty("reason")
    public com.hp.ext.types.solutionManager.ShutdownReason getReason() {
        return reason;
    }

    @JsonProperty("reason")
    public void setReason(com.hp.ext.types.solutionManager.ShutdownReason reason) {
        this.reason = reason;
    }
    public ShutdownNotificationPayload()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "shutdownNotificationPayload";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.shutdownNotificationPayload";
    }
}
