/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Used in the solution archive manifest to identify a set of solution hosts and related fail-over/fault-tolerance configuration
 */
public class SolutionHostSet extends E2Type
{
    private com.hp.ext.types.solutionManager.SolutionHealthTarget healthTarget;
    private com.hp.ext.types.solutionManager.SolutionHostSet_Hosts_Binding hosts;
    private String name;
    
    @JsonProperty("healthTarget")
    public com.hp.ext.types.solutionManager.SolutionHealthTarget getHealthTarget() {
        return healthTarget;
    }

    @JsonProperty("healthTarget")
    public void setHealthTarget(com.hp.ext.types.solutionManager.SolutionHealthTarget healthTarget) {
        this.healthTarget = healthTarget;
    }
    @JsonProperty("hosts")
    public com.hp.ext.types.solutionManager.SolutionHostSet_Hosts_Binding getHosts() {
        return hosts;
    }

    @JsonProperty("hosts")
    public void setHosts(com.hp.ext.types.solutionManager.SolutionHostSet_Hosts_Binding hosts) {
        this.hosts = hosts;
    }
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonProperty("name")
    public void setName(String name) {
        this.name = name;
    }
    public SolutionHostSet()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "solutionHostSet";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.solutionHostSet";
    }
}
