/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The solution resource is the representation of an installed solution. It primarily consists 
 * of data that was provided in the solution "manifest" from the solution archive, as well 
 * as device generated content specific to the installation state. Note that all properties 
 * are read-only.
 */
public class SolutionContent extends E2Type
{
    private com.hp.ext.types.solutionManager.ContextProfile contextProfile;
    private com.hp.ext.types.solutionManager.SolutionDependencies dependencies;
    private com.hp.ext.types.solutionManager.SolutionDescription description;
    private java.util.List<com.hp.ext.types.solutionManager.SolutionHostSet> hostSets;
    private com.hp.ext.types.solutionManager.InitializedState initializedState;
    private java.util.List<com.hp.ext.types.solutionManager.Action> installActions;
    private com.hp.ext.types.solutionManager.InstallCodeState installCodeState;
    private com.hp.ext.types.solutionManager.InstallationDetails installationDetails;
    private java.util.List<com.hp.ext.types.solutionManager.PlatformPackage> packages;
    private java.util.List<com.hp.ext.types.solutionManager.RegistrationRecord> registrations;
    private com.hp.ext.types.solutionManager.SolutionId solutionId;
    private com.hp.ext.types.solutionManager.SolutionState state;
    private com.hp.ext.types.solutionManager.TrustedSitesContent trustedSites;
    private java.util.List<com.hp.ext.types.solutionManager.Action> uninstallActions;
    
    @JsonProperty("contextProfile")
    public com.hp.ext.types.solutionManager.ContextProfile getContextProfile() {
        return contextProfile;
    }

    @JsonProperty("contextProfile")
    public void setContextProfile(com.hp.ext.types.solutionManager.ContextProfile contextProfile) {
        this.contextProfile = contextProfile;
    }
    @JsonProperty("dependencies")
    public com.hp.ext.types.solutionManager.SolutionDependencies getDependencies() {
        return dependencies;
    }

    @JsonProperty("dependencies")
    public void setDependencies(com.hp.ext.types.solutionManager.SolutionDependencies dependencies) {
        this.dependencies = dependencies;
    }
    @JsonProperty("description")
    public com.hp.ext.types.solutionManager.SolutionDescription getDescription() {
        return description;
    }

    @JsonProperty("description")
    public void setDescription(com.hp.ext.types.solutionManager.SolutionDescription description) {
        this.description = description;
    }
    @JsonProperty("hostSets")
    public java.util.List<com.hp.ext.types.solutionManager.SolutionHostSet> getHostSets() {
        return hostSets;
    }

    @JsonProperty("hostSets")
    public void setHostSets(java.util.List<com.hp.ext.types.solutionManager.SolutionHostSet> hostSets) {
        this.hostSets = hostSets;
    }
    @JsonProperty("initializedState")
    public com.hp.ext.types.solutionManager.InitializedState getInitializedState() {
        return initializedState;
    }

    @JsonProperty("initializedState")
    public void setInitializedState(com.hp.ext.types.solutionManager.InitializedState initializedState) {
        this.initializedState = initializedState;
    }
    @JsonProperty("installActions")
    public java.util.List<com.hp.ext.types.solutionManager.Action> getInstallActions() {
        return installActions;
    }

    @JsonProperty("installActions")
    public void setInstallActions(java.util.List<com.hp.ext.types.solutionManager.Action> installActions) {
        this.installActions = installActions;
    }
    @JsonProperty("installCodeState")
    public com.hp.ext.types.solutionManager.InstallCodeState getInstallCodeState() {
        return installCodeState;
    }

    @JsonProperty("installCodeState")
    public void setInstallCodeState(com.hp.ext.types.solutionManager.InstallCodeState installCodeState) {
        this.installCodeState = installCodeState;
    }
    @JsonProperty("installationDetails")
    public com.hp.ext.types.solutionManager.InstallationDetails getInstallationDetails() {
        return installationDetails;
    }

    @JsonProperty("installationDetails")
    public void setInstallationDetails(com.hp.ext.types.solutionManager.InstallationDetails installationDetails) {
        this.installationDetails = installationDetails;
    }
    @JsonProperty("packages")
    public java.util.List<com.hp.ext.types.solutionManager.PlatformPackage> getPackages() {
        return packages;
    }

    @JsonProperty("packages")
    public void setPackages(java.util.List<com.hp.ext.types.solutionManager.PlatformPackage> packages) {
        this.packages = packages;
    }
    @JsonProperty("registrations")
    public java.util.List<com.hp.ext.types.solutionManager.RegistrationRecord> getRegistrations() {
        return registrations;
    }

    @JsonProperty("registrations")
    public void setRegistrations(java.util.List<com.hp.ext.types.solutionManager.RegistrationRecord> registrations) {
        this.registrations = registrations;
    }
    @JsonProperty("solutionId")
    public com.hp.ext.types.solutionManager.SolutionId getSolutionId() {
        return solutionId;
    }

    @JsonProperty("solutionId")
    public void setSolutionId(com.hp.ext.types.solutionManager.SolutionId solutionId) {
        this.solutionId = solutionId;
    }
    @JsonProperty("state")
    public com.hp.ext.types.solutionManager.SolutionState getState() {
        return state;
    }

    @JsonProperty("state")
    public void setState(com.hp.ext.types.solutionManager.SolutionState state) {
        this.state = state;
    }
    @JsonProperty("trustedSites")
    public com.hp.ext.types.solutionManager.TrustedSitesContent getTrustedSites() {
        return trustedSites;
    }

    @JsonProperty("trustedSites")
    public void setTrustedSites(com.hp.ext.types.solutionManager.TrustedSitesContent trustedSites) {
        this.trustedSites = trustedSites;
    }
    @JsonProperty("uninstallActions")
    public java.util.List<com.hp.ext.types.solutionManager.Action> getUninstallActions() {
        return uninstallActions;
    }

    @JsonProperty("uninstallActions")
    public void setUninstallActions(java.util.List<com.hp.ext.types.solutionManager.Action> uninstallActions) {
        this.uninstallActions = uninstallActions;
    }
    public SolutionContent()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "solutionContent";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.solutionContent";
    }
}
