/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.IE2NamespaceManifest;
public class SolutionManagerTypesManifest implements IE2NamespaceManifest
{
    public final String ToolVersion = "2.19.0.202505142133";
    public final String Name = "SolutionManagerTypes";
    public final String Description = "General types defined for use with the Solution Manager Service";
    public final String Title = "Solution Manager Service Types";
    public final short MajorVersion = 1;
    public final String Revision = "";
    public final String ReleaseLevel = "";
    public final String ReleaseSequence = "";
    public final String RevisionDetail = String.format("%s (%s %s)", this.Revision, this.ReleaseLevel, this.ReleaseSequence);
    public final String BaseGUN = "com.hp.ext.types.solutionManager";
    public final String VersionedGUN = String.format("%s.%s", this.BaseGUN, this.MajorVersion);

    private static SolutionManagerTypesManifest instance;

    private SolutionManagerTypesManifest() { }

    public static SolutionManagerTypesManifest getInstance()
    {
            if (null == instance)
            {
                instance = new SolutionManagerTypesManifest();
            }
            return instance;
    }
}