/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Enumeration;

import java.io.IOException;
import java.util.Hashtable;

import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;

/**
 * An enumeration of solution host health types
 */
@JsonDeserialize(using = SolutionHealthType.Deserializer.class)
public class SolutionHealthType extends E2Enumeration {

    public static boolean isSealed() { return false; }

    /**
     * Solution host health is good
    */
    public static SolutionHealthType ShtGood = new SolutionHealthType("shtGood");
    /**
     * Solution host health is poor
    */
    public static SolutionHealthType ShtPoor = new SolutionHealthType("shtPoor");

    protected static Hashtable<String, SolutionHealthType> definitions;
    
    static {
        definitions = new Hashtable<String, SolutionHealthType> ();
        definitions.put(ShtGood.getValue(), ShtGood);
        definitions.put(ShtPoor.getValue(), ShtPoor);
    }

    private SolutionHealthType() {
        this(null);
    }

    private SolutionHealthType(String name) {
        this(name, name);
    }

    private SolutionHealthType(String name, String jsonLiteral) {
        super(name, jsonLiteral);
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "solutionHealthType";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.solutionHealthType";
    }

    public static SolutionHealthType Parse(String name)
    {
        SolutionHealthType instance = definitions.get(name);
        if (instance == null && !isSealed()) {
            instance = new  SolutionHealthType(name);
        }
        return instance;
    }

    public static class Deserializer extends StdDeserializer<SolutionHealthType> { 

        public Deserializer() { 
            this(null); 
        } 
    
        public Deserializer(Class<?> vc) { 
            super(vc); 
        }
    
        @Override
        public SolutionHealthType deserialize(JsonParser jp, DeserializationContext ctxt) 
            throws IOException, JsonProcessingException {
            ObjectMapper mapper = (ObjectMapper) jp.getCodec();
            JsonNode node = mapper.readTree(jp);
            
            return SolutionHealthType.Parse(node.asText());
        }
    }
}
