/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The Solution Manifest is a variation of the Solution resource, and is used to define a solution contained within a Solution Package
 */
public class SolutionManifest extends E2Type
{
    private String archiveVersion;
    private java.util.List<com.hp.ext.types.solutionManager.CertificateReference> certificateAuthorities;
    private com.hp.ext.types.solutionManager.ConfigurationManifestContent configuration;
    private com.hp.ext.types.solutionManager.ContextProfile contextProfile;
    private com.hp.ext.types.solutionManager.SolutionDependencies dependencies;
    private com.hp.ext.types.solutionManager.SolutionDescription description;
    private java.util.List<com.hp.ext.types.solutionManager.SolutionHostSet> hostSets;
    private java.util.List<com.hp.ext.types.solutionManager.Action> installActions;
    private java.util.List<com.hp.ext.types.solutionManager.PlatformPackage> packages;
    private java.util.List<com.hp.ext.types.solutionManager.RegistrationRecord> registrations;
    private com.hp.ext.types.agent.SolutionId solutionId;
    private com.hp.ext.types.solutionManager.TrustedSitesContent trustedSites;
    private java.util.List<com.hp.ext.types.solutionManager.Action> uninstallActions;
    
    @JsonProperty("archiveVersion")
    public String getArchiveVersion() {
        return archiveVersion;
    }

    @JsonProperty("archiveVersion")
    public void setArchiveVersion(String archiveVersion) {
        this.archiveVersion = archiveVersion;
    }
    @JsonProperty("certificateAuthorities")
    public java.util.List<com.hp.ext.types.solutionManager.CertificateReference> getCertificateAuthorities() {
        return certificateAuthorities;
    }

    @JsonProperty("certificateAuthorities")
    public void setCertificateAuthorities(java.util.List<com.hp.ext.types.solutionManager.CertificateReference> certificateAuthorities) {
        this.certificateAuthorities = certificateAuthorities;
    }
    @JsonProperty("configuration")
    public com.hp.ext.types.solutionManager.ConfigurationManifestContent getConfiguration() {
        return configuration;
    }

    @JsonProperty("configuration")
    public void setConfiguration(com.hp.ext.types.solutionManager.ConfigurationManifestContent configuration) {
        this.configuration = configuration;
    }
    @JsonProperty("contextProfile")
    public com.hp.ext.types.solutionManager.ContextProfile getContextProfile() {
        return contextProfile;
    }

    @JsonProperty("contextProfile")
    public void setContextProfile(com.hp.ext.types.solutionManager.ContextProfile contextProfile) {
        this.contextProfile = contextProfile;
    }
    @JsonProperty("dependencies")
    public com.hp.ext.types.solutionManager.SolutionDependencies getDependencies() {
        return dependencies;
    }

    @JsonProperty("dependencies")
    public void setDependencies(com.hp.ext.types.solutionManager.SolutionDependencies dependencies) {
        this.dependencies = dependencies;
    }
    @JsonProperty("description")
    public com.hp.ext.types.solutionManager.SolutionDescription getDescription() {
        return description;
    }

    @JsonProperty("description")
    public void setDescription(com.hp.ext.types.solutionManager.SolutionDescription description) {
        this.description = description;
    }
    @JsonProperty("hostSets")
    public java.util.List<com.hp.ext.types.solutionManager.SolutionHostSet> getHostSets() {
        return hostSets;
    }

    @JsonProperty("hostSets")
    public void setHostSets(java.util.List<com.hp.ext.types.solutionManager.SolutionHostSet> hostSets) {
        this.hostSets = hostSets;
    }
    @JsonProperty("installActions")
    public java.util.List<com.hp.ext.types.solutionManager.Action> getInstallActions() {
        return installActions;
    }

    @JsonProperty("installActions")
    public void setInstallActions(java.util.List<com.hp.ext.types.solutionManager.Action> installActions) {
        this.installActions = installActions;
    }
    @JsonProperty("packages")
    public java.util.List<com.hp.ext.types.solutionManager.PlatformPackage> getPackages() {
        return packages;
    }

    @JsonProperty("packages")
    public void setPackages(java.util.List<com.hp.ext.types.solutionManager.PlatformPackage> packages) {
        this.packages = packages;
    }
    @JsonProperty("registrations")
    public java.util.List<com.hp.ext.types.solutionManager.RegistrationRecord> getRegistrations() {
        return registrations;
    }

    @JsonProperty("registrations")
    public void setRegistrations(java.util.List<com.hp.ext.types.solutionManager.RegistrationRecord> registrations) {
        this.registrations = registrations;
    }
    @JsonProperty("solutionId")
    public com.hp.ext.types.agent.SolutionId getSolutionId() {
        return solutionId;
    }

    @JsonProperty("solutionId")
    public void setSolutionId(com.hp.ext.types.agent.SolutionId solutionId) {
        this.solutionId = solutionId;
    }
    @JsonProperty("trustedSites")
    public com.hp.ext.types.solutionManager.TrustedSitesContent getTrustedSites() {
        return trustedSites;
    }

    @JsonProperty("trustedSites")
    public void setTrustedSites(com.hp.ext.types.solutionManager.TrustedSitesContent trustedSites) {
        this.trustedSites = trustedSites;
    }
    @JsonProperty("uninstallActions")
    public java.util.List<com.hp.ext.types.solutionManager.Action> getUninstallActions() {
        return uninstallActions;
    }

    @JsonProperty("uninstallActions")
    public void setUninstallActions(java.util.List<com.hp.ext.types.solutionManager.Action> uninstallActions) {
        this.uninstallActions = uninstallActions;
    }
    public SolutionManifest()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "solutionManifest";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.solutionManifest";
    }
}
