/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * This variant holds an explicit value for the bindable parameter.
 */
public class SolutionHostSet_Hosts_Value extends E2Type
{
    private java.util.List<String> explicitValue;
    
    @JsonProperty("explicitValue")
    public java.util.List<String> getExplicitValue() {
        return explicitValue;
    }

    @JsonProperty("explicitValue")
    public void setExplicitValue(java.util.List<String> explicitValue) {
        this.explicitValue = explicitValue;
    }
    public SolutionHostSet_Hosts_Value()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "solutionHostSet_hosts_value";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.solutionHostSet_hosts_value";
    }
}
