/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * This variant holds a macro value for the bindable parameter.
 */
public class SolutionHealthTarget_HealthyThreshold_Expression extends E2Type
{
    private java.lang.Byte expressedValue;
    private String expressionPattern;
    
    @JsonProperty("expressedValue")
    public java.lang.Byte getExpressedValue() {
        return expressedValue;
    }

    @JsonProperty("expressedValue")
    public void setExpressedValue(java.lang.Byte expressedValue) {
        this.expressedValue = expressedValue;
    }
    @JsonProperty("expressionPattern")
    public String getExpressionPattern() {
        return expressionPattern;
    }

    @JsonProperty("expressionPattern")
    public void setExpressionPattern(String expressionPattern) {
        this.expressionPattern = expressionPattern;
    }
    public SolutionHealthTarget_HealthyThreshold_Expression()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "solutionHealthTarget_healthyThreshold_expression";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.solutionHealthTarget_healthyThreshold_expression";
    }
}
