/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * This variant holds an explicit value for the bindable parameter.
 */
public class TrustedSitesContent_Sites_Value extends E2Type
{
    private String explicitValue;
    
    @JsonProperty("explicitValue")
    public String getExplicitValue() {
        return explicitValue;
    }

    @JsonProperty("explicitValue")
    public void setExplicitValue(String explicitValue) {
        this.explicitValue = explicitValue;
    }
    public TrustedSitesContent_Sites_Value()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "trustedSitesContent_sites_value";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.trustedSitesContent_sites_value";
    }
}
