/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.types.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The Platform Package for a Workpath solution
 */
public class WorkpathPlatformPackage extends E2Type
{
    private String platformVersion;
    private String workpathPackagePath;
    
    @JsonProperty("platformVersion")
    public String getPlatformVersion() {
        return platformVersion;
    }

    @JsonProperty("platformVersion")
    public void setPlatformVersion(String platformVersion) {
        this.platformVersion = platformVersion;
    }
    @JsonProperty("workpathPackagePath")
    public String getWorkpathPackagePath() {
        return workpathPackagePath;
    }

    @JsonProperty("workpathPackagePath")
    public void setWorkpathPackagePath(String workpathPackagePath) {
        this.workpathPackagePath = workpathPackagePath;
    }
    public WorkpathPlatformPackage()
    {
        majorVersion = SolutionManagerTypesManifest.getInstance().MajorVersion;
        typeName = "workpathPlatformPackage";
        typeGUN = "com.hp.ext.types.solutionManager.version.1.type.workpathPlatformPackage";
    }
}
