/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the JSON body parameters for the Create operation of the <solutions>/{solutionId}/runtimeRegistrations/{recordId} resource.
 */
public class RuntimeRegistration_Create extends E2Type
{
    private com.hp.ext.types.common.TypedObject record;
    private com.hp.ext.types.solutionManager.RuntimeRegistrationRecordId recordId;
    
    @JsonProperty("record")
    public com.hp.ext.types.common.TypedObject getRecord() {
        return record;
    }

    @JsonProperty("record")
    public void setRecord(com.hp.ext.types.common.TypedObject record) {
        this.record = record;
    }
    @JsonProperty("recordId")
    public com.hp.ext.types.solutionManager.RuntimeRegistrationRecordId getRecordId() {
        return recordId;
    }

    @JsonProperty("recordId")
    public void setRecordId(com.hp.ext.types.solutionManager.RuntimeRegistrationRecordId recordId) {
        this.recordId = recordId;
    }
    public RuntimeRegistration_Create()
    {
        majorVersion = SolutionManagerManifest.getInstance().MajorVersion;
        typeName = "runtimeRegistration_create";
        typeGUN = "com.hp.ext.service.solutionManager.version.1.type.runtimeRegistration_create";
    }
}
