/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the <solutions>/{solutionId}/runtimeRegistrations/{recordId} resource.
 */
public class RuntimeRegistration extends E2Type
{
    private com.hp.ext.types.base.OperationMeta opMeta;
    private java.util.List<com.hp.ext.types.base.Link> links;
    private com.hp.ext.types.solutionManager.RuntimeRegistrationRecordId resourceId;
    private com.hp.ext.types.common.TypedObject record;
    private com.hp.ext.types.solutionManager.RuntimeRegistrationRecordId recordId;
    
    @JsonProperty("$opMeta")
    public com.hp.ext.types.base.OperationMeta getopMeta() {
        return opMeta;
    }

    @JsonProperty("$opMeta")
    public void setopMeta(com.hp.ext.types.base.OperationMeta opMeta) {
        this.opMeta = opMeta;
    }
    @JsonProperty("links")
    public java.util.List<com.hp.ext.types.base.Link> getLinks() {
        return links;
    }

    @JsonProperty("links")
    public void setLinks(java.util.List<com.hp.ext.types.base.Link> links) {
        this.links = links;
    }
    @JsonProperty("resourceId")
    public com.hp.ext.types.solutionManager.RuntimeRegistrationRecordId getResourceId() {
        return resourceId;
    }

    @JsonProperty("resourceId")
    public void setResourceId(com.hp.ext.types.solutionManager.RuntimeRegistrationRecordId resourceId) {
        this.resourceId = resourceId;
    }
    @JsonProperty("record")
    public com.hp.ext.types.common.TypedObject getRecord() {
        return record;
    }

    @JsonProperty("record")
    public void setRecord(com.hp.ext.types.common.TypedObject record) {
        this.record = record;
    }
    @JsonProperty("recordId")
    public com.hp.ext.types.solutionManager.RuntimeRegistrationRecordId getRecordId() {
        return recordId;
    }

    @JsonProperty("recordId")
    public void setRecordId(com.hp.ext.types.solutionManager.RuntimeRegistrationRecordId recordId) {
        this.recordId = recordId;
    }
    public RuntimeRegistration()
    {
        majorVersion = SolutionManagerManifest.getInstance().MajorVersion;
        typeName = "runtimeRegistration";
        typeGUN = "com.hp.ext.service.solutionManager.version.1.type.runtimeRegistration";
    }
}
