/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the <solutions> resource.
 */
public class Solutions extends E2Type
{
    private com.hp.ext.types.base.OperationMeta opMeta;
    private java.util.List<com.hp.ext.types.base.Link> links;
    private java.util.List<com.hp.ext.types.solutionManager.SolutionId> memberIds;
    private java.util.List<com.hp.ext.service.solutionManager.Solution> members;
    private Long offset;
    private Long selectedCount;
    private Long totalCount;
    
    @JsonProperty("$opMeta")
    public com.hp.ext.types.base.OperationMeta getopMeta() {
        return opMeta;
    }

    @JsonProperty("$opMeta")
    public void setopMeta(com.hp.ext.types.base.OperationMeta opMeta) {
        this.opMeta = opMeta;
    }
    @JsonProperty("links")
    public java.util.List<com.hp.ext.types.base.Link> getLinks() {
        return links;
    }

    @JsonProperty("links")
    public void setLinks(java.util.List<com.hp.ext.types.base.Link> links) {
        this.links = links;
    }
    @JsonProperty("memberIds")
    public java.util.List<com.hp.ext.types.solutionManager.SolutionId> getMemberIds() {
        return memberIds;
    }

    @JsonProperty("memberIds")
    public void setMemberIds(java.util.List<com.hp.ext.types.solutionManager.SolutionId> memberIds) {
        this.memberIds = memberIds;
    }
    @JsonProperty("members")
    public java.util.List<com.hp.ext.service.solutionManager.Solution> getMembers() {
        return members;
    }

    @JsonProperty("members")
    public void setMembers(java.util.List<com.hp.ext.service.solutionManager.Solution> members) {
        this.members = members;
    }
    @JsonProperty("offset")
    public Long getOffset() {
        return offset;
    }

    @JsonProperty("offset")
    public void setOffset(Long offset) {
        this.offset = offset;
    }
    @JsonProperty("selectedCount")
    public Long getSelectedCount() {
        return selectedCount;
    }

    @JsonProperty("selectedCount")
    public void setSelectedCount(Long selectedCount) {
        this.selectedCount = selectedCount;
    }
    @JsonProperty("totalCount")
    public Long getTotalCount() {
        return totalCount;
    }

    @JsonProperty("totalCount")
    public void setTotalCount(Long totalCount) {
        this.totalCount = totalCount;
    }
    public Solutions()
    {
        majorVersion = SolutionManagerManifest.getInstance().MajorVersion;
        typeName = "solutions";
        typeGUN = "com.hp.ext.service.solutionManager.version.1.type.solutions";
    }
}
