/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Used to initiate the removal of a solution modification
 */
public class UninstallModificationRequest extends E2Type
{
    private java.util.UUID modificationId;
    
    @JsonProperty("modificationId")
    public java.util.UUID getModificationId() {
        return modificationId;
    }

    @JsonProperty("modificationId")
    public void setModificationId(java.util.UUID modificationId) {
        this.modificationId = modificationId;
    }
    public UninstallModificationRequest()
    {
        majorVersion = SolutionManagerManifest.getInstance().MajorVersion;
        typeName = "uninstallModificationRequest";
        typeGUN = "com.hp.ext.service.solutionManager.version.1.type.uninstallModificationRequest";
    }
}
