/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Used to initiate the removal of an installed solution
 */
public class UninstallSolutionRequest extends E2Type
{
    private com.hp.ext.types.agent.SolutionId solutionId;
    
    @JsonProperty("solutionId")
    public com.hp.ext.types.agent.SolutionId getSolutionId() {
        return solutionId;
    }

    @JsonProperty("solutionId")
    public void setSolutionId(com.hp.ext.types.agent.SolutionId solutionId) {
        this.solutionId = solutionId;
    }
    public UninstallSolutionRequest()
    {
        majorVersion = SolutionManagerManifest.getInstance().MajorVersion;
        typeName = "uninstallSolutionRequest";
        typeGUN = "com.hp.ext.service.solutionManager.version.1.type.uninstallSolutionRequest";
    }
}
