/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.solutionManager;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * Indicates that a specified key was not defined in the context profile.
 */
public class UnknownKeyError extends E2Type
{
    private com.hp.ext.types.solutionManager.ContextKey key;
    
    @JsonProperty("key")
    public com.hp.ext.types.solutionManager.ContextKey getKey() {
        return key;
    }

    @JsonProperty("key")
    public void setKey(com.hp.ext.types.solutionManager.ContextKey key) {
        this.key = key;
    }
    public UnknownKeyError()
    {
        majorVersion = SolutionManagerManifest.getInstance().MajorVersion;
        typeName = "unknownKeyError";
        typeGUN = "com.hp.ext.service.solutionManager.version.1.type.unknownKeyError";
    }
}
