/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.authentication;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * A registration record for an authentication provider.
 */
public class AuthenticationAgentRegistrationRecord extends E2Type
{
    private com.hp.ext.types.authentication.AuthenticationTarget authenticationTarget;
    private Boolean enablePrePromptCheck;
    private Boolean enableSignoutNotification;
    private java.util.List<com.hp.ext.types.security.WritableAuthenticatedUserDetailsAttributes> modifiedUserAttributes;
    private com.hp.ext.types.agent.AgentId agentId;
    private com.hp.ext.types.localization.LocalizedStringReference localizedDescription;
    private com.hp.ext.types.localization.LocalizedStringReference localizedName;
    private com.hp.ext.types.agent.AgentName name;
    
    @JsonProperty("authenticationTarget")
    public com.hp.ext.types.authentication.AuthenticationTarget getAuthenticationTarget() {
        return authenticationTarget;
    }

    @JsonProperty("authenticationTarget")
    public void setAuthenticationTarget(com.hp.ext.types.authentication.AuthenticationTarget authenticationTarget) {
        this.authenticationTarget = authenticationTarget;
    }
    @JsonProperty("enablePrePromptCheck")
    public Boolean getEnablePrePromptCheck() {
        return enablePrePromptCheck;
    }

    @JsonProperty("enablePrePromptCheck")
    public void setEnablePrePromptCheck(Boolean enablePrePromptCheck) {
        this.enablePrePromptCheck = enablePrePromptCheck;
    }
    @JsonProperty("enableSignoutNotification")
    public Boolean getEnableSignoutNotification() {
        return enableSignoutNotification;
    }

    @JsonProperty("enableSignoutNotification")
    public void setEnableSignoutNotification(Boolean enableSignoutNotification) {
        this.enableSignoutNotification = enableSignoutNotification;
    }
    @JsonProperty("modifiedUserAttributes")
    public java.util.List<com.hp.ext.types.security.WritableAuthenticatedUserDetailsAttributes> getModifiedUserAttributes() {
        return modifiedUserAttributes;
    }

    @JsonProperty("modifiedUserAttributes")
    public void setModifiedUserAttributes(java.util.List<com.hp.ext.types.security.WritableAuthenticatedUserDetailsAttributes> modifiedUserAttributes) {
        this.modifiedUserAttributes = modifiedUserAttributes;
    }
    @JsonProperty("agentId")
    public com.hp.ext.types.agent.AgentId getAgentId() {
        return agentId;
    }

    @JsonProperty("agentId")
    public void setAgentId(com.hp.ext.types.agent.AgentId agentId) {
        this.agentId = agentId;
    }
    @JsonProperty("localizedDescription")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedDescription() {
        return localizedDescription;
    }

    @JsonProperty("localizedDescription")
    public void setLocalizedDescription(com.hp.ext.types.localization.LocalizedStringReference localizedDescription) {
        this.localizedDescription = localizedDescription;
    }
    @JsonProperty("localizedName")
    public com.hp.ext.types.localization.LocalizedStringReference getLocalizedName() {
        return localizedName;
    }

    @JsonProperty("localizedName")
    public void setLocalizedName(com.hp.ext.types.localization.LocalizedStringReference localizedName) {
        this.localizedName = localizedName;
    }
    @JsonProperty("name")
    public com.hp.ext.types.agent.AgentName getName() {
        return name;
    }

    @JsonProperty("name")
    public void setName(com.hp.ext.types.agent.AgentName name) {
        this.name = name;
    }
    public AuthenticationAgentRegistrationRecord()
    {
        majorVersion = AuthenticationManifest.getInstance().MajorVersion;
        typeName = "authenticationAgentRegistrationRecord";
        typeGUN = "com.hp.ext.service.authentication.version.1.type.authenticationAgentRegistrationRecord";
    }
}
