/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.authentication;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type returned by the login operation of the <authenticationAgents>/{agentId} resource.
 */
public class AuthenticationAgent_Login extends E2Type
{
    private com.hp.ext.types.base.OperationMeta opMeta;
    private java.util.List<com.hp.ext.types.base.Link> links;
    private com.hp.ext.types.authentication.SessionToken sessionAccessToken;
    private com.hp.ext.types.authentication.SessionId sessionId;
    
    @JsonProperty("$opMeta")
    public com.hp.ext.types.base.OperationMeta getopMeta() {
        return opMeta;
    }

    @JsonProperty("$opMeta")
    public void setopMeta(com.hp.ext.types.base.OperationMeta opMeta) {
        this.opMeta = opMeta;
    }
    @JsonProperty("links")
    public java.util.List<com.hp.ext.types.base.Link> getLinks() {
        return links;
    }

    @JsonProperty("links")
    public void setLinks(java.util.List<com.hp.ext.types.base.Link> links) {
        this.links = links;
    }
    @JsonProperty("sessionAccessToken")
    public com.hp.ext.types.authentication.SessionToken getSessionAccessToken() {
        return sessionAccessToken;
    }

    @JsonProperty("sessionAccessToken")
    public void setSessionAccessToken(com.hp.ext.types.authentication.SessionToken sessionAccessToken) {
        this.sessionAccessToken = sessionAccessToken;
    }
    @JsonProperty("sessionId")
    public com.hp.ext.types.authentication.SessionId getSessionId() {
        return sessionId;
    }

    @JsonProperty("sessionId")
    public void setSessionId(com.hp.ext.types.authentication.SessionId sessionId) {
        this.sessionId = sessionId;
    }
    public AuthenticationAgent_Login()
    {
        majorVersion = AuthenticationManifest.getInstance().MajorVersion;
        typeName = "authenticationAgent_login";
        typeGUN = "com.hp.ext.service.authentication.version.1.type.authenticationAgent_login";
    }
}
