/***********************************************************
 * (C) Copyright 2022 HP Development Company, L.P.
 * All rights reserved.
 *
 * This file is automatically generated. DO NOT EDIT.
 ***********************************************************/
package com.hp.ext.service.supplies;

import com.hp.ext.types.common.E2Type;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * The type of the <suppliesAgents>/{agentId}/suppliesUsage resource.
 */
public class SuppliesUsage extends E2Type
{
    private com.hp.ext.types.base.OperationMeta opMeta;
    private java.util.List<com.hp.ext.types.base.Link> links;
    private java.util.List<com.hp.ext.service.supplies.SupplyLifetimeCounter> supplyUsageBySlotId;
    
    @JsonProperty("$opMeta")
    public com.hp.ext.types.base.OperationMeta getopMeta() {
        return opMeta;
    }

    @JsonProperty("$opMeta")
    public void setopMeta(com.hp.ext.types.base.OperationMeta opMeta) {
        this.opMeta = opMeta;
    }
    @JsonProperty("links")
    public java.util.List<com.hp.ext.types.base.Link> getLinks() {
        return links;
    }

    @JsonProperty("links")
    public void setLinks(java.util.List<com.hp.ext.types.base.Link> links) {
        this.links = links;
    }
    @JsonProperty("supplyUsageBySlotId")
    public java.util.List<com.hp.ext.service.supplies.SupplyLifetimeCounter> getSupplyUsageBySlotId() {
        return supplyUsageBySlotId;
    }

    @JsonProperty("supplyUsageBySlotId")
    public void setSupplyUsageBySlotId(java.util.List<com.hp.ext.service.supplies.SupplyLifetimeCounter> supplyUsageBySlotId) {
        this.supplyUsageBySlotId = supplyUsageBySlotId;
    }
    public SuppliesUsage()
    {
        majorVersion = SuppliesManifest.getInstance().MajorVersion;
        typeName = "suppliesUsage";
        typeGUN = "com.hp.ext.service.supplies.version.1.type.suppliesUsage";
    }
}
